; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'alias_const_guard_match'
source_filename = "alias_const_guard_match.ql"
target triple = "x86_64-pc-windows-msvc"

define i64 @ql_2_main() {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %l2__t0 = alloca i64
  %l3__t1 = alloca i64
  %l4_other = alloca i64
  br label %bb0
bb0:
  store i64 2, ptr %l1_value
  %t0 = load i64, ptr %l1_value
  store i64 %t0, ptr %l3__t1
  %t1 = load i64, ptr %l3__t1
  %t2 = icmp eq i64 %t1, 2
  br i1 %t2, label %bb4, label %bb5
bb1:
  %t3 = load i64, ptr %l0__return
  ret i64 %t3
bb2:
  %t4 = load i64, ptr %l2__t0
  store i64 %t4, ptr %l0__return
  br label %bb1
bb3:
  store i64 10, ptr %l2__t0
  br label %bb2
bb4:
  store i64 20, ptr %l2__t0
  br label %bb2
bb5:
  %t5 = load i64, ptr %l3__t1
  store i64 %t5, ptr %l4_other
  %t6 = load i64, ptr %l4_other
  store i64 %t6, ptr %l2__t0
  br label %bb2
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_2_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
