; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'async_program_main_guard_refined_projected_dynamic_task_handle_reinit'
source_filename = "async_program_main_guard_refined_projected_dynamic_task_handle_reinit.ql"
target triple = "x86_64-pc-windows-msvc"

declare ptr @malloc(i64)
declare void @free(ptr)

define ptr @qlrt_async_frame_alloc(i64 %size, i64 %align) {
entry:
  %frame_is_zero = icmp eq i64 %size, 0
  %frame_alloc_size = select i1 %frame_is_zero, i64 1, i64 %size
  %frame = call ptr @malloc(i64 %frame_alloc_size)
  ret ptr %frame
}

define ptr @qlrt_async_task_create(ptr %entry_fn, ptr %frame) {
entry:
  %task_end = getelementptr { ptr, ptr, ptr }, ptr null, i32 1
  %task_size = ptrtoint ptr %task_end to i64
  %task = call ptr @malloc(i64 %task_size)
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  store ptr %entry_fn, ptr %task_entry_ptr
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  store ptr %frame, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr null, ptr %task_result_ptr
  ret ptr %task
}

define ptr @qlrt_executor_spawn(ptr %executor, ptr %task) {
entry:
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  %task_entry = load ptr, ptr %task_entry_ptr
  %task_started = icmp eq ptr %task_entry, null
  br i1 %task_started, label %done, label %start

start:
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  %task_frame = load ptr, ptr %task_frame_ptr
  %task_result = call ptr %task_entry(ptr %task_frame)
  call void @free(ptr %task_frame)
  store ptr null, ptr %task_entry_ptr
  store ptr null, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr %task_result, ptr %task_result_ptr
  br label %done

done:
  ret ptr %task
}

define ptr @qlrt_task_await(ptr %handle) {
entry:
  %started = call ptr @qlrt_executor_spawn(ptr null, ptr %handle)
  %result_ptr_slot = getelementptr inbounds { ptr, ptr, ptr }, ptr %started, i32 0, i32 2
  %result_ptr = load ptr, ptr %result_ptr_slot
  call void @free(ptr %started)
  ret ptr %result_ptr
}

define void @qlrt_task_result_release(ptr %result) {
entry:
  call void @free(ptr %result)
  ret void
}

define i64 @ql_1_worker__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %async_body_frame_field0 = getelementptr inbounds { i64 }, ptr %frame, i32 0, i32 0
  %async_body_frame_value0 = load i64, ptr %async_body_frame_field0
  store i64 %async_body_frame_value0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  store i64 %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load i64, ptr %l0__return
  ret i64 %t1
}

define ptr @ql_1_worker__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_1_worker__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_1_worker(i64 %arg0) {
entry:
  %async_frame = call ptr @qlrt_async_frame_alloc(i64 8, i64 8)
  %async_frame_field0 = getelementptr inbounds { i64 }, ptr %async_frame, i32 0, i32 0
  store i64 %arg0, ptr %async_frame_field0
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_1_worker__async_entry, ptr %async_frame)
  ret ptr %async_task
}

define i64 @ql_2_score(i64 %arg0) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  store i64 %arg0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  store i64 %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load i64, ptr %l0__return
  ret i64 %t1
}

define i64 @ql_3_main__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca ptr
  %l2__t1 = alloca ptr
  %l3__t2 = alloca [2 x ptr]
  %l4_tasks = alloca [2 x ptr]
  %l5__t3 = alloca { i64 }
  %l6_slot = alloca { i64 }
  %l8__t5 = alloca i1
  %l9__t6 = alloca i64
  %l10_first = alloca i64
  %l11__t7 = alloca i64
  %l12__t8 = alloca ptr
  %l13__t9 = alloca ptr
  %l14__t10 = alloca i64
  %l15_final_value = alloca i64
  %l16__t11 = alloca i64
  br label %bb0
bb0:
  %t0 = call ptr @ql_1_worker(i64 1)
  store ptr %t0, ptr %l1__t0
  %t1 = call ptr @ql_1_worker(i64 2)
  store ptr %t1, ptr %l2__t1
  %t2 = load ptr, ptr %l1__t0
  %t3 = load ptr, ptr %l2__t1
  %t4 = insertvalue [2 x ptr] undef, ptr %t2, 0
  %t5 = insertvalue [2 x ptr] %t4, ptr %t3, 1
  store [2 x ptr] %t5, ptr %l3__t2
  %t6 = load [2 x ptr], ptr %l3__t2
  store [2 x ptr] %t6, ptr %l4_tasks
  %t7 = insertvalue { i64 } undef, i64 0, 0
  store { i64 } %t7, ptr %l5__t3
  %t8 = load { i64 }, ptr %l5__t3
  store { i64 } %t8, ptr %l6_slot
  %t9 = getelementptr inbounds { i64 }, ptr %l6_slot, i32 0, i32 0
  %t10 = load i64, ptr %t9
  %t11 = icmp eq i64 %t10, 0
  store i1 %t11, ptr %l8__t5
  %t12 = load i1, ptr %l8__t5
  br i1 %t12, label %bb3, label %bb2
bb1:
  %t13 = load i64, ptr %l0__return
  ret i64 %t13
bb2:
  %t14 = getelementptr inbounds [2 x ptr], ptr %l4_tasks, i64 0, i64 0
  %t15 = load ptr, ptr %t14
  %t16 = call ptr @qlrt_task_await(ptr %t15)
  %t17 = load i64, ptr %t16
  call void @qlrt_task_result_release(ptr %t16)
  store i64 %t17, ptr %l14__t10
  %t18 = load i64, ptr %l14__t10
  store i64 %t18, ptr %l15_final_value
  %t19 = load i64, ptr %l15_final_value
  %t20 = call i64 @ql_2_score(i64 %t19)
  store i64 %t20, ptr %l16__t11
  %t21 = load i64, ptr %l16__t11
  store i64 %t21, ptr %l0__return
  br label %bb1
bb3:
  %t22 = getelementptr inbounds { i64 }, ptr %l6_slot, i32 0, i32 0
  %t23 = load i64, ptr %t22
  %t24 = getelementptr inbounds [2 x ptr], ptr %l4_tasks, i64 0, i64 %t23
  %t25 = load ptr, ptr %t24
  %t26 = call ptr @qlrt_task_await(ptr %t25)
  %t27 = load i64, ptr %t26
  call void @qlrt_task_result_release(ptr %t26)
  store i64 %t27, ptr %l9__t6
  %t28 = load i64, ptr %l9__t6
  store i64 %t28, ptr %l10_first
  %t29 = load i64, ptr %l10_first
  %t30 = add i64 %t29, 1
  store i64 %t30, ptr %l11__t7
  %t31 = load i64, ptr %l11__t7
  %t32 = call ptr @ql_1_worker(i64 %t31)
  store ptr %t32, ptr %l12__t8
  %t33 = load ptr, ptr %l12__t8
  %t34 = getelementptr inbounds [2 x ptr], ptr %l4_tasks, i64 0, i64 0
  store ptr %t33, ptr %t34
  %t35 = load ptr, ptr %l12__t8
  store ptr %t35, ptr %l13__t9
  %t36 = load ptr, ptr %l13__t9
  br label %bb2
}

define ptr @ql_3_main__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_3_main__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_3_main() {
entry:
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_3_main__async_entry, ptr null)
  ret ptr %async_task
}

define i32 @main() {
entry:
  %async_main_task = call ptr @ql_3_main()
  %async_main_join = call ptr @qlrt_executor_spawn(ptr null, ptr %async_main_task)
  %async_main_res = call ptr @qlrt_task_await(ptr %async_main_join)
  %async_main_ret = load i64, ptr %async_main_res
  call void @qlrt_task_result_release(ptr %async_main_res)
  %async_main_exit = trunc i64 %async_main_ret to i32
  ret i32 %async_main_exit
}
