; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'async_program_main_for_await_array'
source_filename = "async_program_main_for_await_array.ql"
target triple = "{{TARGET_TRIPLE}}"

declare ptr @malloc(i64)
declare void @free(ptr)

define ptr @qlrt_async_frame_alloc(i64 %size, i64 %align) {
entry:
  %frame_is_zero = icmp eq i64 %size, 0
  %frame_alloc_size = select i1 %frame_is_zero, i64 1, i64 %size
  %frame = call ptr @malloc(i64 %frame_alloc_size)
  ret ptr %frame
}

define ptr @qlrt_async_task_create(ptr %entry_fn, ptr %frame) {
entry:
  %task_end = getelementptr { ptr, ptr, ptr }, ptr null, i32 1
  %task_size = ptrtoint ptr %task_end to i64
  %task = call ptr @malloc(i64 %task_size)
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  store ptr %entry_fn, ptr %task_entry_ptr
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  store ptr %frame, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr null, ptr %task_result_ptr
  ret ptr %task
}

define ptr @qlrt_executor_spawn(ptr %executor, ptr %task) {
entry:
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  %task_entry = load ptr, ptr %task_entry_ptr
  %task_started = icmp eq ptr %task_entry, null
  br i1 %task_started, label %done, label %start

start:
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  %task_frame = load ptr, ptr %task_frame_ptr
  %task_result = call ptr %task_entry(ptr %task_frame)
  call void @free(ptr %task_frame)
  store ptr null, ptr %task_entry_ptr
  store ptr null, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr %task_result, ptr %task_result_ptr
  br label %done

done:
  ret ptr %task
}

define ptr @qlrt_task_await(ptr %handle) {
entry:
  %started = call ptr @qlrt_executor_spawn(ptr null, ptr %handle)
  %result_ptr_slot = getelementptr inbounds { ptr, ptr, ptr }, ptr %started, i32 0, i32 2
  %result_ptr = load ptr, ptr %result_ptr_slot
  call void @free(ptr %started)
  ret ptr %result_ptr
}

define void @qlrt_task_result_release(ptr %result) {
entry:
  call void @free(ptr %result)
  ret void
}

define ptr @qlrt_async_iter_next(ptr %iterator) {
entry:
  ret ptr null
}

define i64 @ql_0_main__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_total = alloca i64
  %l2__t0 = alloca [3 x i64]
  %l3__t1 = alloca i64
  %l4_value = alloca i64
  %l5__t2 = alloca i64
  %for_await_index_bb2 = alloca i64
  store i64 -1, ptr %for_await_index_bb2
  br label %bb0
bb0:
  store i64 0, ptr %l1_total
  %t0 = insertvalue [3 x i64] undef, i64 1, 0
  %t1 = insertvalue [3 x i64] %t0, i64 2, 1
  %t2 = insertvalue [3 x i64] %t1, i64 3, 2
  store [3 x i64] %t2, ptr %l2__t0
  %t3 = load i64, ptr %for_await_index_bb2
  %t4 = add i64 %t3, 1
  store i64 %t4, ptr %for_await_index_bb2
  br label %bb2
bb1:
  %t5 = load i64, ptr %l0__return
  ret i64 %t5
bb2:
  %t6 = load i64, ptr %for_await_index_bb2
  %t7 = icmp ult i64 %t6, 3
  br i1 %t7, label %bb2_for_await_setup, label %bb4
bb3:
  %t8 = load i64, ptr %l3__t1
  store i64 %t8, ptr %l4_value
  %t9 = load i64, ptr %l1_total
  %t10 = load i64, ptr %l4_value
  %t11 = add i64 %t9, %t10
  store i64 %t11, ptr %l5__t2
  %t12 = load i64, ptr %l5__t2
  store i64 %t12, ptr %l1_total
  %t13 = load i64, ptr %for_await_index_bb2
  %t14 = add i64 %t13, 1
  store i64 %t14, ptr %for_await_index_bb2
  br label %bb2
bb4:
  %t15 = load i64, ptr %l1_total
  store i64 %t15, ptr %l0__return
  br label %bb1
bb2_for_await_setup:
  %t16 = load i64, ptr %for_await_index_bb2
  %t17 = getelementptr inbounds [3 x i64], ptr %l2__t0, i64 0, i64 %t16
  %t18 = load i64, ptr %t17
  store i64 %t18, ptr %l3__t1
  br label %bb3
}

define ptr @ql_0_main__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_0_main__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_0_main() {
entry:
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_0_main__async_entry, ptr null)
  ret ptr %async_task
}

define i32 @main() {
entry:
  %async_main_task = call ptr @ql_0_main()
  %async_main_join = call ptr @qlrt_executor_spawn(ptr null, ptr %async_main_task)
  %async_main_res = call ptr @qlrt_task_await(ptr %async_main_join)
  %async_main_ret = load i64, ptr %async_main_res
  call void @qlrt_task_result_release(ptr %async_main_res)
  %async_main_exit = trunc i64 %async_main_ret to i32
  ret i32 %async_main_exit
}
