; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'async_program_main_guarded_alias_sourced_composed_dynamic_task_handle_nested_array_repackage_spawn'
source_filename = "async_program_main_guarded_alias_sourced_composed_dynamic_task_handle_nested_array_repackage_spawn.ql"
target triple = "x86_64-pc-windows-msvc"

declare ptr @malloc(i64)
declare void @free(ptr)

define ptr @qlrt_async_frame_alloc(i64 %size, i64 %align) {
entry:
  %frame_is_zero = icmp eq i64 %size, 0
  %frame_alloc_size = select i1 %frame_is_zero, i64 1, i64 %size
  %frame = call ptr @malloc(i64 %frame_alloc_size)
  ret ptr %frame
}

define ptr @qlrt_async_task_create(ptr %entry_fn, ptr %frame) {
entry:
  %task_end = getelementptr { ptr, ptr, ptr }, ptr null, i32 1
  %task_size = ptrtoint ptr %task_end to i64
  %task = call ptr @malloc(i64 %task_size)
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  store ptr %entry_fn, ptr %task_entry_ptr
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  store ptr %frame, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr null, ptr %task_result_ptr
  ret ptr %task
}

define ptr @qlrt_executor_spawn(ptr %executor, ptr %task) {
entry:
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  %task_entry = load ptr, ptr %task_entry_ptr
  %task_started = icmp eq ptr %task_entry, null
  br i1 %task_started, label %done, label %start

start:
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  %task_frame = load ptr, ptr %task_frame_ptr
  %task_result = call ptr %task_entry(ptr %task_frame)
  call void @free(ptr %task_frame)
  store ptr null, ptr %task_entry_ptr
  store ptr null, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr %task_result, ptr %task_result_ptr
  br label %done

done:
  ret ptr %task
}

define ptr @qlrt_task_await(ptr %handle) {
entry:
  %started = call ptr @qlrt_executor_spawn(ptr null, ptr %handle)
  %result_ptr_slot = getelementptr inbounds { ptr, ptr, ptr }, ptr %started, i32 0, i32 2
  %result_ptr = load ptr, ptr %result_ptr_slot
  call void @free(ptr %started)
  ret ptr %result_ptr
}

define void @qlrt_task_result_release(ptr %result) {
entry:
  call void @free(ptr %result)
  ret void
}

define i64 @ql_5_worker__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %async_body_frame_field0 = getelementptr inbounds { i64 }, ptr %frame, i32 0, i32 0
  %async_body_frame_value0 = load i64, ptr %async_body_frame_field0
  store i64 %async_body_frame_value0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  store i64 %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load i64, ptr %l0__return
  ret i64 %t1
}

define ptr @ql_5_worker__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_5_worker__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_5_worker(i64 %arg0) {
entry:
  %async_frame = call ptr @qlrt_async_frame_alloc(i64 8, i64 8)
  %async_frame_field0 = getelementptr inbounds { i64 }, ptr %async_frame, i32 0, i32 0
  store i64 %arg0, ptr %async_frame_field0
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_5_worker__async_entry, ptr %async_frame)
  ret ptr %async_task
}

define i64 @ql_6_choose() {
entry:
  %l0__return = alloca i64
  br label %bb0
bb0:
  store i64 0, ptr %l0__return
  br label %bb1
bb1:
  %t0 = load i64, ptr %l0__return
  ret i64 %t0
}

define i64 @ql_7_main__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca i64
  %l2_row = alloca i64
  %l3__t1 = alloca [2 x i64]
  %l4_slots = alloca [2 x i64]
  %l5_alias_slots = alloca [2 x i64]
  %l6__t2 = alloca ptr
  %l7__t3 = alloca ptr
  %l8__t4 = alloca [2 x ptr]
  %l9__t5 = alloca { [2 x ptr] }
  %l10_pending = alloca { [2 x ptr] }
  %l11_alias = alloca [2 x ptr]
  %l12__t6 = alloca { i64 }
  %l13_slot = alloca { i64 }
  %l15__t8 = alloca i1
  %l16__t9 = alloca i64
  %l17_first = alloca i64
  %l18__t10 = alloca i64
  %l19__t11 = alloca ptr
  %l20__t12 = alloca ptr
  %l21__t13 = alloca ptr
  %l22__t14 = alloca [2 x ptr]
  %l23__t15 = alloca { [2 x ptr] }
  %l24__t16 = alloca { { [2 x ptr] }, ptr }
  %l25_env = alloca { { [2 x ptr] }, ptr }
  %l26__t17 = alloca ptr
  %l27_running = alloca ptr
  %l28__t18 = alloca i64
  %l29_second = alloca i64
  %l30__t19 = alloca i64
  %l31_extra = alloca i64
  %l32__t20 = alloca i64
  %l33_tail = alloca i64
  %l34__t21 = alloca i64
  %l35__t22 = alloca i64
  br label %bb0
bb0:
  %t0 = call i64 @ql_6_choose()
  store i64 %t0, ptr %l1__t0
  %t1 = load i64, ptr %l1__t0
  store i64 %t1, ptr %l2_row
  %t2 = load i64, ptr %l2_row
  %t3 = load i64, ptr %l2_row
  %t4 = insertvalue [2 x i64] undef, i64 %t2, 0
  %t5 = insertvalue [2 x i64] %t4, i64 %t3, 1
  store [2 x i64] %t5, ptr %l3__t1
  %t6 = load [2 x i64], ptr %l3__t1
  store [2 x i64] %t6, ptr %l4_slots
  %t7 = load [2 x i64], ptr %l4_slots
  store [2 x i64] %t7, ptr %l5_alias_slots
  %t8 = call ptr @ql_5_worker(i64 8)
  store ptr %t8, ptr %l6__t2
  %t9 = call ptr @ql_5_worker(i64 14)
  store ptr %t9, ptr %l7__t3
  %t10 = load ptr, ptr %l6__t2
  %t11 = load ptr, ptr %l7__t3
  %t12 = insertvalue [2 x ptr] undef, ptr %t10, 0
  %t13 = insertvalue [2 x ptr] %t12, ptr %t11, 1
  store [2 x ptr] %t13, ptr %l8__t4
  %t14 = load [2 x ptr], ptr %l8__t4
  %t15 = insertvalue { [2 x ptr] } undef, [2 x ptr] %t14, 0
  store { [2 x ptr] } %t15, ptr %l9__t5
  %t16 = load { [2 x ptr] }, ptr %l9__t5
  store { [2 x ptr] } %t16, ptr %l10_pending
  %t17 = getelementptr inbounds { [2 x ptr] }, ptr %l10_pending, i32 0, i32 0
  %t18 = load [2 x ptr], ptr %t17
  store [2 x ptr] %t18, ptr %l11_alias
  %t19 = insertvalue { i64 } undef, i64 0, 0
  store { i64 } %t19, ptr %l12__t6
  %t20 = load { i64 }, ptr %l12__t6
  store { i64 } %t20, ptr %l13_slot
  %t21 = getelementptr inbounds { i64 }, ptr %l13_slot, i32 0, i32 0
  %t22 = load i64, ptr %t21
  %t23 = icmp eq i64 %t22, 0
  store i1 %t23, ptr %l15__t8
  %t24 = load i1, ptr %l15__t8
  br i1 %t24, label %bb3, label %bb2
bb1:
  %t25 = load i64, ptr %l0__return
  ret i64 %t25
bb2:
  %t26 = call ptr @ql_5_worker(i64 20)
  store ptr %t26, ptr %l21__t13
  %t27 = getelementptr inbounds { [2 x ptr] }, ptr %l10_pending, i32 0, i32 0
  %t28 = load i64, ptr %l2_row
  %t29 = getelementptr inbounds [2 x i64], ptr %l5_alias_slots, i64 0, i64 %t28
  %t30 = load i64, ptr %t29
  %t31 = getelementptr inbounds [2 x ptr], ptr %t27, i64 0, i64 %t30
  %t32 = load ptr, ptr %t31
  %t33 = load ptr, ptr %l21__t13
  %t34 = insertvalue [2 x ptr] undef, ptr %t32, 0
  %t35 = insertvalue [2 x ptr] %t34, ptr %t33, 1
  store [2 x ptr] %t35, ptr %l22__t14
  %t36 = load [2 x ptr], ptr %l22__t14
  %t37 = insertvalue { [2 x ptr] } undef, [2 x ptr] %t36, 0
  store { [2 x ptr] } %t37, ptr %l23__t15
  %t38 = load { [2 x ptr] }, ptr %l23__t15
  %t39 = getelementptr inbounds { [2 x ptr] }, ptr %l10_pending, i32 0, i32 0
  %t40 = getelementptr inbounds [2 x ptr], ptr %t39, i64 0, i64 1
  %t41 = load ptr, ptr %t40
  %t42 = insertvalue { { [2 x ptr] }, ptr } undef, { [2 x ptr] } %t38, 0
  %t43 = insertvalue { { [2 x ptr] }, ptr } %t42, ptr %t41, 1
  store { { [2 x ptr] }, ptr } %t43, ptr %l24__t16
  %t44 = load { { [2 x ptr] }, ptr }, ptr %l24__t16
  store { { [2 x ptr] }, ptr } %t44, ptr %l25_env
  %t45 = getelementptr inbounds { { [2 x ptr] }, ptr }, ptr %l24__t16, i32 0, i32 0
  %t46 = getelementptr inbounds { [2 x ptr] }, ptr %t45, i32 0, i32 0
  %t47 = getelementptr inbounds [2 x ptr], ptr %t46, i64 0, i64 0
  %t48 = load ptr, ptr %t47
  %t49 = call ptr @qlrt_executor_spawn(ptr null, ptr %t48)
  store ptr %t49, ptr %l26__t17
  %t50 = load ptr, ptr %l26__t17
  store ptr %t50, ptr %l27_running
  %t51 = load ptr, ptr %l26__t17
  %t52 = call ptr @qlrt_task_await(ptr %t51)
  %t53 = load i64, ptr %t52
  call void @qlrt_task_result_release(ptr %t52)
  store i64 %t53, ptr %l28__t18
  %t54 = load i64, ptr %l28__t18
  store i64 %t54, ptr %l29_second
  %t55 = getelementptr inbounds { { [2 x ptr] }, ptr }, ptr %l24__t16, i32 0, i32 0
  %t56 = getelementptr inbounds { [2 x ptr] }, ptr %t55, i32 0, i32 0
  %t57 = getelementptr inbounds [2 x ptr], ptr %t56, i64 0, i64 1
  %t58 = load ptr, ptr %t57
  %t59 = call ptr @qlrt_task_await(ptr %t58)
  %t60 = load i64, ptr %t59
  call void @qlrt_task_result_release(ptr %t59)
  store i64 %t60, ptr %l30__t19
  %t61 = load i64, ptr %l30__t19
  store i64 %t61, ptr %l31_extra
  %t62 = getelementptr inbounds { { [2 x ptr] }, ptr }, ptr %l24__t16, i32 0, i32 1
  %t63 = load ptr, ptr %t62
  %t64 = call ptr @qlrt_task_await(ptr %t63)
  %t65 = load i64, ptr %t64
  call void @qlrt_task_result_release(ptr %t64)
  store i64 %t65, ptr %l32__t20
  %t66 = load i64, ptr %l32__t20
  store i64 %t66, ptr %l33_tail
  %t67 = load i64, ptr %l29_second
  %t68 = load i64, ptr %l31_extra
  %t69 = add i64 %t67, %t68
  store i64 %t69, ptr %l34__t21
  %t70 = load i64, ptr %l34__t21
  %t71 = load i64, ptr %l33_tail
  %t72 = add i64 %t70, %t71
  store i64 %t72, ptr %l35__t22
  %t73 = load i64, ptr %l35__t22
  store i64 %t73, ptr %l0__return
  br label %bb1
bb3:
  %t74 = getelementptr inbounds { [2 x ptr] }, ptr %l10_pending, i32 0, i32 0
  %t75 = load i64, ptr %l2_row
  %t76 = getelementptr inbounds [2 x i64], ptr %l5_alias_slots, i64 0, i64 %t75
  %t77 = load i64, ptr %t76
  %t78 = getelementptr inbounds [2 x ptr], ptr %t74, i64 0, i64 %t77
  %t79 = load ptr, ptr %t78
  %t80 = call ptr @qlrt_task_await(ptr %t79)
  %t81 = load i64, ptr %t80
  call void @qlrt_task_result_release(ptr %t80)
  store i64 %t81, ptr %l16__t9
  %t82 = load i64, ptr %l16__t9
  store i64 %t82, ptr %l17_first
  %t83 = load i64, ptr %l17_first
  %t84 = add i64 %t83, 8
  store i64 %t84, ptr %l18__t10
  %t85 = load i64, ptr %l18__t10
  %t86 = call ptr @ql_5_worker(i64 %t85)
  store ptr %t86, ptr %l19__t11
  %t87 = load ptr, ptr %l19__t11
  %t88 = getelementptr inbounds { [2 x ptr] }, ptr %l10_pending, i32 0, i32 0
  %t89 = load i64, ptr %l2_row
  %t90 = getelementptr inbounds [2 x i64], ptr %l4_slots, i64 0, i64 %t89
  %t91 = load i64, ptr %t90
  %t92 = getelementptr inbounds [2 x ptr], ptr %t88, i64 0, i64 %t91
  store ptr %t87, ptr %t92
  %t93 = load ptr, ptr %l19__t11
  store ptr %t93, ptr %l20__t12
  %t94 = load ptr, ptr %l20__t12
  br label %bb2
}

define ptr @ql_7_main__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_7_main__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_7_main() {
entry:
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_7_main__async_entry, ptr null)
  ret ptr %async_task
}

define i32 @main() {
entry:
  %async_main_task = call ptr @ql_7_main()
  %async_main_join = call ptr @qlrt_executor_spawn(ptr null, ptr %async_main_task)
  %async_main_res = call ptr @qlrt_task_await(ptr %async_main_join)
  %async_main_ret = load i64, ptr %async_main_res
  call void @qlrt_task_result_release(ptr %async_main_res)
  %async_main_exit = trunc i64 %async_main_ret to i32
  ret i32 %async_main_exit
}
