; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'async_program_main_aliased_guard_refined_const_backed_projected_root_task_handle_nested_repackage_reinit'
source_filename = "async_program_main_aliased_guard_refined_const_backed_projected_root_task_handle_nested_repackage_reinit.ql"
target triple = "{{TARGET_TRIPLE}}"

declare ptr @malloc(i64)
declare void @free(ptr)

define ptr @qlrt_async_frame_alloc(i64 %size, i64 %align) {
entry:
  %frame_is_zero = icmp eq i64 %size, 0
  %frame_alloc_size = select i1 %frame_is_zero, i64 1, i64 %size
  %frame = call ptr @malloc(i64 %frame_alloc_size)
  ret ptr %frame
}

define ptr @qlrt_async_task_create(ptr %entry_fn, ptr %frame) {
entry:
  %task_end = getelementptr { ptr, ptr, ptr }, ptr null, i32 1
  %task_size = ptrtoint ptr %task_end to i64
  %task = call ptr @malloc(i64 %task_size)
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  store ptr %entry_fn, ptr %task_entry_ptr
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  store ptr %frame, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr null, ptr %task_result_ptr
  ret ptr %task
}

define ptr @qlrt_executor_spawn(ptr %executor, ptr %task) {
entry:
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  %task_entry = load ptr, ptr %task_entry_ptr
  %task_started = icmp eq ptr %task_entry, null
  br i1 %task_started, label %done, label %start

start:
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  %task_frame = load ptr, ptr %task_frame_ptr
  %task_result = call ptr %task_entry(ptr %task_frame)
  call void @free(ptr %task_frame)
  store ptr null, ptr %task_entry_ptr
  store ptr null, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr %task_result, ptr %task_result_ptr
  br label %done

done:
  ret ptr %task
}

define ptr @qlrt_task_await(ptr %handle) {
entry:
  %started = call ptr @qlrt_executor_spawn(ptr null, ptr %handle)
  %result_ptr_slot = getelementptr inbounds { ptr, ptr, ptr }, ptr %started, i32 0, i32 2
  %result_ptr = load ptr, ptr %result_ptr_slot
  call void @free(ptr %started)
  ret ptr %result_ptr
}

define void @qlrt_task_result_release(ptr %result) {
entry:
  call void @free(ptr %result)
  ret void
}

define i64 @ql_5_worker__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %async_body_frame_field0 = getelementptr inbounds { i64 }, ptr %frame, i32 0, i32 0
  %async_body_frame_value0 = load i64, ptr %async_body_frame_field0
  store i64 %async_body_frame_value0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  store i64 %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load i64, ptr %l0__return
  ret i64 %t1
}

define ptr @ql_5_worker__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_5_worker__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_5_worker(i64 %arg0) {
entry:
  %async_frame = call ptr @qlrt_async_frame_alloc(i64 8, i64 8)
  %async_frame_field0 = getelementptr inbounds { i64 }, ptr %async_frame, i32 0, i32 0
  store i64 %arg0, ptr %async_frame_field0
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_5_worker__async_entry, ptr %async_frame)
  ret ptr %async_task
}

define i64 @ql_6_main__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca ptr
  %l2__t1 = alloca ptr
  %l3__t2 = alloca [2 x ptr]
  %l4__t3 = alloca { [2 x ptr] }
  %l5_pending = alloca { [2 x ptr] }
  %l6_alias = alloca [2 x ptr]
  %l7__t4 = alloca { i64 }
  %l8_slot = alloca { i64 }
  %l10__t6 = alloca i1
  %l11__t7 = alloca i64
  %l12_first = alloca i64
  %l13__t8 = alloca i64
  %l14__t9 = alloca ptr
  %l15__t10 = alloca ptr
  %l16__t11 = alloca ptr
  %l17__t12 = alloca { ptr, ptr }
  %l18__t13 = alloca { { ptr, ptr }, ptr }
  %l19_env = alloca { { ptr, ptr }, ptr }
  %l20__t14 = alloca i64
  %l21_second = alloca i64
  %l22__t15 = alloca i64
  %l23_extra = alloca i64
  %l24__t16 = alloca i64
  %l25_tail = alloca i64
  %l26__t17 = alloca i64
  %l27__t18 = alloca i64
  br label %bb0
bb0:
  %t0 = call ptr @ql_5_worker(i64 8)
  store ptr %t0, ptr %l1__t0
  %t1 = call ptr @ql_5_worker(i64 14)
  store ptr %t1, ptr %l2__t1
  %t2 = load ptr, ptr %l1__t0
  %t3 = load ptr, ptr %l2__t1
  %t4 = insertvalue [2 x ptr] undef, ptr %t2, 0
  %t5 = insertvalue [2 x ptr] %t4, ptr %t3, 1
  store [2 x ptr] %t5, ptr %l3__t2
  %t6 = load [2 x ptr], ptr %l3__t2
  %t7 = insertvalue { [2 x ptr] } undef, [2 x ptr] %t6, 0
  store { [2 x ptr] } %t7, ptr %l4__t3
  %t8 = load { [2 x ptr] }, ptr %l4__t3
  store { [2 x ptr] } %t8, ptr %l5_pending
  %t9 = getelementptr inbounds { [2 x ptr] }, ptr %l5_pending, i32 0, i32 0
  %t10 = load [2 x ptr], ptr %t9
  store [2 x ptr] %t10, ptr %l6_alias
  %t11 = insertvalue { i64 } undef, i64 0, 0
  store { i64 } %t11, ptr %l7__t4
  %t12 = load { i64 }, ptr %l7__t4
  store { i64 } %t12, ptr %l8_slot
  %t13 = getelementptr inbounds { i64 }, ptr %l8_slot, i32 0, i32 0
  %t14 = load i64, ptr %t13
  %t15 = icmp eq i64 %t14, 0
  store i1 %t15, ptr %l10__t6
  %t16 = load i1, ptr %l10__t6
  br i1 %t16, label %bb3, label %bb2
bb1:
  %t17 = load i64, ptr %l0__return
  ret i64 %t17
bb2:
  %t18 = call ptr @ql_5_worker(i64 9)
  store ptr %t18, ptr %l16__t11
  %t19 = getelementptr inbounds { [2 x ptr] }, ptr %l5_pending, i32 0, i32 0
  %t20 = getelementptr inbounds [2 x ptr], ptr %t19, i64 0, i64 0
  %t21 = load ptr, ptr %t20
  %t22 = load ptr, ptr %l16__t11
  %t23 = insertvalue { ptr, ptr } undef, ptr %t21, 0
  %t24 = insertvalue { ptr, ptr } %t23, ptr %t22, 1
  store { ptr, ptr } %t24, ptr %l17__t12
  %t25 = load { ptr, ptr }, ptr %l17__t12
  %t26 = getelementptr inbounds { [2 x ptr] }, ptr %l5_pending, i32 0, i32 0
  %t27 = getelementptr inbounds [2 x ptr], ptr %t26, i64 0, i64 1
  %t28 = load ptr, ptr %t27
  %t29 = insertvalue { { ptr, ptr }, ptr } undef, { ptr, ptr } %t25, 0
  %t30 = insertvalue { { ptr, ptr }, ptr } %t29, ptr %t28, 1
  store { { ptr, ptr }, ptr } %t30, ptr %l18__t13
  %t31 = load { { ptr, ptr }, ptr }, ptr %l18__t13
  store { { ptr, ptr }, ptr } %t31, ptr %l19_env
  %t32 = getelementptr inbounds { { ptr, ptr }, ptr }, ptr %l18__t13, i32 0, i32 0
  %t33 = getelementptr inbounds { ptr, ptr }, ptr %t32, i32 0, i32 0
  %t34 = load ptr, ptr %t33
  %t35 = call ptr @qlrt_task_await(ptr %t34)
  %t36 = load i64, ptr %t35
  call void @qlrt_task_result_release(ptr %t35)
  store i64 %t36, ptr %l20__t14
  %t37 = load i64, ptr %l20__t14
  store i64 %t37, ptr %l21_second
  %t38 = getelementptr inbounds { { ptr, ptr }, ptr }, ptr %l18__t13, i32 0, i32 0
  %t39 = getelementptr inbounds { ptr, ptr }, ptr %t38, i32 0, i32 1
  %t40 = load ptr, ptr %t39
  %t41 = call ptr @qlrt_task_await(ptr %t40)
  %t42 = load i64, ptr %t41
  call void @qlrt_task_result_release(ptr %t41)
  store i64 %t42, ptr %l22__t15
  %t43 = load i64, ptr %l22__t15
  store i64 %t43, ptr %l23_extra
  %t44 = getelementptr inbounds { { ptr, ptr }, ptr }, ptr %l18__t13, i32 0, i32 1
  %t45 = load ptr, ptr %t44
  %t46 = call ptr @qlrt_task_await(ptr %t45)
  %t47 = load i64, ptr %t46
  call void @qlrt_task_result_release(ptr %t46)
  store i64 %t47, ptr %l24__t16
  %t48 = load i64, ptr %l24__t16
  store i64 %t48, ptr %l25_tail
  %t49 = load i64, ptr %l21_second
  %t50 = load i64, ptr %l23_extra
  %t51 = add i64 %t49, %t50
  store i64 %t51, ptr %l26__t17
  %t52 = load i64, ptr %l26__t17
  %t53 = load i64, ptr %l25_tail
  %t54 = add i64 %t52, %t53
  store i64 %t54, ptr %l27__t18
  %t55 = load i64, ptr %l27__t18
  store i64 %t55, ptr %l0__return
  br label %bb1
bb3:
  %t56 = getelementptr inbounds { [2 x ptr] }, ptr %l5_pending, i32 0, i32 0
  %t57 = getelementptr inbounds [2 x ptr], ptr %t56, i64 0, i64 0
  %t58 = load ptr, ptr %t57
  %t59 = call ptr @qlrt_task_await(ptr %t58)
  %t60 = load i64, ptr %t59
  call void @qlrt_task_result_release(ptr %t59)
  store i64 %t60, ptr %l11__t7
  %t61 = load i64, ptr %l11__t7
  store i64 %t61, ptr %l12_first
  %t62 = load i64, ptr %l12_first
  %t63 = add i64 %t62, 5
  store i64 %t63, ptr %l13__t8
  %t64 = load i64, ptr %l13__t8
  %t65 = call ptr @ql_5_worker(i64 %t64)
  store ptr %t65, ptr %l14__t9
  %t66 = load ptr, ptr %l14__t9
  %t67 = getelementptr inbounds { [2 x ptr] }, ptr %l5_pending, i32 0, i32 0
  %t68 = getelementptr inbounds [2 x ptr], ptr %t67, i64 0, i64 0
  store ptr %t66, ptr %t68
  %t69 = load ptr, ptr %l14__t9
  store ptr %t69, ptr %l15__t10
  %t70 = load ptr, ptr %l15__t10
  br label %bb2
}

define ptr @ql_6_main__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_6_main__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_6_main() {
entry:
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_6_main__async_entry, ptr null)
  ret ptr %async_task
}

define i32 @main() {
entry:
  %async_main_task = call ptr @ql_6_main()
  %async_main_join = call ptr @qlrt_executor_spawn(ptr null, ptr %async_main_task)
  %async_main_res = call ptr @qlrt_task_await(ptr %async_main_join)
  %async_main_ret = load i64, ptr %async_main_res
  call void @qlrt_task_result_release(ptr %async_main_res)
  %async_main_exit = trunc i64 %async_main_ret to i32
  ret i32 %async_main_exit
}
