; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'async_program_main_guarded_const_backed_triple_root_triple_source_row_slot_tail_alias_sourced_composed_dynamic_task_handle_forwarded_nested_array_repackage_spawn'
source_filename = "async_program_main_guarded_const_backed_triple_root_triple_source_row_slot_tail_alias_sourced_composed_dynamic_task_handle_forwarded_nested_array_repackage_spawn.ql"
target triple = "{{TARGET_TRIPLE}}"

declare ptr @malloc(i64)
declare void @free(ptr)

define ptr @qlrt_async_frame_alloc(i64 %size, i64 %align) {
entry:
  %frame_is_zero = icmp eq i64 %size, 0
  %frame_alloc_size = select i1 %frame_is_zero, i64 1, i64 %size
  %frame = call ptr @malloc(i64 %frame_alloc_size)
  ret ptr %frame
}

define ptr @qlrt_async_task_create(ptr %entry_fn, ptr %frame) {
entry:
  %task_end = getelementptr { ptr, ptr, ptr }, ptr null, i32 1
  %task_size = ptrtoint ptr %task_end to i64
  %task = call ptr @malloc(i64 %task_size)
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  store ptr %entry_fn, ptr %task_entry_ptr
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  store ptr %frame, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr null, ptr %task_result_ptr
  ret ptr %task
}

define ptr @qlrt_executor_spawn(ptr %executor, ptr %task) {
entry:
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  %task_entry = load ptr, ptr %task_entry_ptr
  %task_started = icmp eq ptr %task_entry, null
  br i1 %task_started, label %done, label %start

start:
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  %task_frame = load ptr, ptr %task_frame_ptr
  %task_result = call ptr %task_entry(ptr %task_frame)
  call void @free(ptr %task_frame)
  store ptr null, ptr %task_entry_ptr
  store ptr null, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr %task_result, ptr %task_result_ptr
  br label %done

done:
  ret ptr %task
}

define ptr @qlrt_task_await(ptr %handle) {
entry:
  %started = call ptr @qlrt_executor_spawn(ptr null, ptr %handle)
  %result_ptr_slot = getelementptr inbounds { ptr, ptr, ptr }, ptr %started, i32 0, i32 2
  %result_ptr = load ptr, ptr %result_ptr_slot
  call void @free(ptr %started)
  ret ptr %result_ptr
}

define void @qlrt_task_result_release(ptr %result) {
entry:
  call void @free(ptr %result)
  ret void
}

define i64 @ql_5_worker__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %async_body_frame_field0 = getelementptr inbounds { i64 }, ptr %frame, i32 0, i32 0
  %async_body_frame_value0 = load i64, ptr %async_body_frame_field0
  store i64 %async_body_frame_value0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  store i64 %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load i64, ptr %l0__return
  ret i64 %t1
}

define ptr @ql_5_worker__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_5_worker__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_5_worker(i64 %arg0) {
entry:
  %async_frame = call ptr @qlrt_async_frame_alloc(i64 8, i64 8)
  %async_frame_field0 = getelementptr inbounds { i64 }, ptr %async_frame, i32 0, i32 0
  store i64 %arg0, ptr %async_frame_field0
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_5_worker__async_entry, ptr %async_frame)
  ret ptr %async_task
}

define ptr @ql_6_forward(ptr %arg0) {
entry:
  %l0__return = alloca ptr
  %l1_task = alloca ptr
  store ptr %arg0, ptr %l1_task
  br label %bb0
bb0:
  %t0 = load ptr, ptr %l1_task
  store ptr %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load ptr, ptr %l0__return
  ret ptr %t1
}

define i64 @ql_7_main__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_row_root = alloca i64
  %l2_row = alloca i64
  %l3__t0 = alloca [2 x i64]
  %l4_slots = alloca [2 x i64]
  %l5_slot_root = alloca [2 x i64]
  %l6_slot_alias_root = alloca [2 x i64]
  %l7_alias_slots = alloca [2 x i64]
  %l8__t1 = alloca ptr
  %l9__t2 = alloca ptr
  %l10__t3 = alloca [2 x ptr]
  %l11__t4 = alloca { [2 x ptr] }
  %l12_pending = alloca { [2 x ptr] }
  %l13_root = alloca [2 x ptr]
  %l14_root_alias = alloca [2 x ptr]
  %l15_alias = alloca [2 x ptr]
  %l16__t5 = alloca { i64 }
  %l17_slot = alloca { i64 }
  %l18_slot_alias = alloca { i64 }
  %l20__t7 = alloca i1
  %l21__t8 = alloca i64
  %l22_first = alloca i64
  %l23__t9 = alloca i64
  %l24__t10 = alloca ptr
  %l25__t11 = alloca ptr
  %l26_tail_tasks = alloca [2 x ptr]
  %l27__t12 = alloca ptr
  %l28__t13 = alloca ptr
  %l29__t14 = alloca [2 x ptr]
  %l30__t15 = alloca { [2 x ptr] }
  %l31__t16 = alloca { { [2 x ptr] }, ptr }
  %l32_env = alloca { { [2 x ptr] }, ptr }
  %l33__t17 = alloca ptr
  %l34_running = alloca ptr
  %l35__t18 = alloca i64
  %l36_second = alloca i64
  %l37__t19 = alloca i64
  %l38_extra = alloca i64
  %l39__t20 = alloca i64
  %l40_tail = alloca i64
  %l41__t21 = alloca i64
  %l42__t22 = alloca i64
  br label %bb0
bb0:
  store i64 0, ptr %l1_row_root
  %t0 = load i64, ptr %l1_row_root
  store i64 %t0, ptr %l2_row
  %t1 = load i64, ptr %l2_row
  %t2 = load i64, ptr %l2_row
  %t3 = insertvalue [2 x i64] undef, i64 %t1, 0
  %t4 = insertvalue [2 x i64] %t3, i64 %t2, 1
  store [2 x i64] %t4, ptr %l3__t0
  %t5 = load [2 x i64], ptr %l3__t0
  store [2 x i64] %t5, ptr %l4_slots
  %t6 = load [2 x i64], ptr %l4_slots
  store [2 x i64] %t6, ptr %l5_slot_root
  %t7 = load [2 x i64], ptr %l5_slot_root
  store [2 x i64] %t7, ptr %l6_slot_alias_root
  %t8 = load [2 x i64], ptr %l6_slot_alias_root
  store [2 x i64] %t8, ptr %l7_alias_slots
  %t9 = call ptr @ql_5_worker(i64 8)
  store ptr %t9, ptr %l8__t1
  %t10 = call ptr @ql_5_worker(i64 14)
  store ptr %t10, ptr %l9__t2
  %t11 = load ptr, ptr %l8__t1
  %t12 = load ptr, ptr %l9__t2
  %t13 = insertvalue [2 x ptr] undef, ptr %t11, 0
  %t14 = insertvalue [2 x ptr] %t13, ptr %t12, 1
  store [2 x ptr] %t14, ptr %l10__t3
  %t15 = load [2 x ptr], ptr %l10__t3
  %t16 = insertvalue { [2 x ptr] } undef, [2 x ptr] %t15, 0
  store { [2 x ptr] } %t16, ptr %l11__t4
  %t17 = load { [2 x ptr] }, ptr %l11__t4
  store { [2 x ptr] } %t17, ptr %l12_pending
  %t18 = getelementptr inbounds { [2 x ptr] }, ptr %l12_pending, i32 0, i32 0
  %t19 = load [2 x ptr], ptr %t18
  store [2 x ptr] %t19, ptr %l13_root
  %t20 = getelementptr inbounds { [2 x ptr] }, ptr %l12_pending, i32 0, i32 0
  %t21 = load [2 x ptr], ptr %t20
  store [2 x ptr] %t21, ptr %l14_root_alias
  %t22 = getelementptr inbounds { [2 x ptr] }, ptr %l12_pending, i32 0, i32 0
  %t23 = load [2 x ptr], ptr %t22
  store [2 x ptr] %t23, ptr %l15_alias
  %t24 = insertvalue { i64 } undef, i64 0, 0
  store { i64 } %t24, ptr %l16__t5
  %t25 = load { i64 }, ptr %l16__t5
  store { i64 } %t25, ptr %l17_slot
  %t26 = load { i64 }, ptr %l17_slot
  store { i64 } %t26, ptr %l18_slot_alias
  %t27 = getelementptr inbounds { i64 }, ptr %l18_slot_alias, i32 0, i32 0
  %t28 = load i64, ptr %t27
  %t29 = icmp eq i64 %t28, 0
  store i1 %t29, ptr %l20__t7
  %t30 = load i1, ptr %l20__t7
  br i1 %t30, label %bb3, label %bb2
bb1:
  %t31 = load i64, ptr %l0__return
  ret i64 %t31
bb2:
  %t32 = getelementptr inbounds { [2 x ptr] }, ptr %l12_pending, i32 0, i32 0
  %t33 = load [2 x ptr], ptr %t32
  store [2 x ptr] %t33, ptr %l26_tail_tasks
  %t34 = getelementptr inbounds { [2 x ptr] }, ptr %l12_pending, i32 0, i32 0
  %t35 = getelementptr inbounds [2 x ptr], ptr %t34, i64 0, i64 0
  %t36 = load ptr, ptr %t35
  %t37 = call ptr @ql_6_forward(ptr %t36)
  store ptr %t37, ptr %l27__t12
  %t38 = call ptr @ql_5_worker(i64 37)
  store ptr %t38, ptr %l28__t13
  %t39 = load ptr, ptr %l27__t12
  %t40 = load ptr, ptr %l28__t13
  %t41 = insertvalue [2 x ptr] undef, ptr %t39, 0
  %t42 = insertvalue [2 x ptr] %t41, ptr %t40, 1
  store [2 x ptr] %t42, ptr %l29__t14
  %t43 = load [2 x ptr], ptr %l29__t14
  %t44 = insertvalue { [2 x ptr] } undef, [2 x ptr] %t43, 0
  store { [2 x ptr] } %t44, ptr %l30__t15
  %t45 = load { [2 x ptr] }, ptr %l30__t15
  %t46 = getelementptr inbounds { [2 x ptr] }, ptr %l12_pending, i32 0, i32 0
  %t47 = getelementptr inbounds [2 x ptr], ptr %t46, i64 0, i64 1
  %t48 = load ptr, ptr %t47
  %t49 = insertvalue { { [2 x ptr] }, ptr } undef, { [2 x ptr] } %t45, 0
  %t50 = insertvalue { { [2 x ptr] }, ptr } %t49, ptr %t48, 1
  store { { [2 x ptr] }, ptr } %t50, ptr %l31__t16
  %t51 = load { { [2 x ptr] }, ptr }, ptr %l31__t16
  store { { [2 x ptr] }, ptr } %t51, ptr %l32_env
  %t52 = getelementptr inbounds { { [2 x ptr] }, ptr }, ptr %l31__t16, i32 0, i32 0
  %t53 = getelementptr inbounds { [2 x ptr] }, ptr %t52, i32 0, i32 0
  %t54 = getelementptr inbounds [2 x ptr], ptr %t53, i64 0, i64 0
  %t55 = load ptr, ptr %t54
  %t56 = call ptr @qlrt_executor_spawn(ptr null, ptr %t55)
  store ptr %t56, ptr %l33__t17
  %t57 = load ptr, ptr %l33__t17
  store ptr %t57, ptr %l34_running
  %t58 = load ptr, ptr %l33__t17
  %t59 = call ptr @qlrt_task_await(ptr %t58)
  %t60 = load i64, ptr %t59
  call void @qlrt_task_result_release(ptr %t59)
  store i64 %t60, ptr %l35__t18
  %t61 = load i64, ptr %l35__t18
  store i64 %t61, ptr %l36_second
  %t62 = getelementptr inbounds { { [2 x ptr] }, ptr }, ptr %l31__t16, i32 0, i32 0
  %t63 = getelementptr inbounds { [2 x ptr] }, ptr %t62, i32 0, i32 0
  %t64 = getelementptr inbounds [2 x ptr], ptr %t63, i64 0, i64 1
  %t65 = load ptr, ptr %t64
  %t66 = call ptr @qlrt_task_await(ptr %t65)
  %t67 = load i64, ptr %t66
  call void @qlrt_task_result_release(ptr %t66)
  store i64 %t67, ptr %l37__t19
  %t68 = load i64, ptr %l37__t19
  store i64 %t68, ptr %l38_extra
  %t69 = getelementptr inbounds { { [2 x ptr] }, ptr }, ptr %l31__t16, i32 0, i32 1
  %t70 = load ptr, ptr %t69
  %t71 = call ptr @qlrt_task_await(ptr %t70)
  %t72 = load i64, ptr %t71
  call void @qlrt_task_result_release(ptr %t71)
  store i64 %t72, ptr %l39__t20
  %t73 = load i64, ptr %l39__t20
  store i64 %t73, ptr %l40_tail
  %t74 = load i64, ptr %l36_second
  %t75 = load i64, ptr %l38_extra
  %t76 = add i64 %t74, %t75
  store i64 %t76, ptr %l41__t21
  %t77 = load i64, ptr %l41__t21
  %t78 = load i64, ptr %l40_tail
  %t79 = add i64 %t77, %t78
  store i64 %t79, ptr %l42__t22
  %t80 = load i64, ptr %l42__t22
  store i64 %t80, ptr %l0__return
  br label %bb1
bb3:
  %t81 = getelementptr inbounds { [2 x ptr] }, ptr %l12_pending, i32 0, i32 0
  %t82 = getelementptr inbounds [2 x ptr], ptr %t81, i64 0, i64 0
  %t83 = load ptr, ptr %t82
  %t84 = call ptr @qlrt_task_await(ptr %t83)
  %t85 = load i64, ptr %t84
  call void @qlrt_task_result_release(ptr %t84)
  store i64 %t85, ptr %l21__t8
  %t86 = load i64, ptr %l21__t8
  store i64 %t86, ptr %l22_first
  %t87 = load i64, ptr %l22_first
  %t88 = add i64 %t87, 19
  store i64 %t88, ptr %l23__t9
  %t89 = load i64, ptr %l23__t9
  %t90 = call ptr @ql_5_worker(i64 %t89)
  store ptr %t90, ptr %l24__t10
  %t91 = load ptr, ptr %l24__t10
  %t92 = getelementptr inbounds { [2 x ptr] }, ptr %l12_pending, i32 0, i32 0
  %t93 = getelementptr inbounds [2 x ptr], ptr %t92, i64 0, i64 0
  store ptr %t91, ptr %t93
  %t94 = load ptr, ptr %l24__t10
  store ptr %t94, ptr %l25__t11
  %t95 = load ptr, ptr %l25__t11
  br label %bb2
}

define ptr @ql_7_main__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_7_main__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_7_main() {
entry:
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_7_main__async_entry, ptr null)
  ret ptr %async_task
}

define i32 @main() {
entry:
  %async_main_task = call ptr @ql_7_main()
  %async_main_join = call ptr @qlrt_executor_spawn(ptr null, ptr %async_main_task)
  %async_main_res = call ptr @qlrt_task_await(ptr %async_main_join)
  %async_main_ret = load i64, ptr %async_main_res
  call void @qlrt_task_result_release(ptr %async_main_res)
  %async_main_exit = trunc i64 %async_main_ret to i32
  ret i32 %async_main_exit
}
