; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'async_program_main_guarded_const_backed_alias_sourced_composed_dynamic_task_handle_forwarded_nested_array_repackage_spawn'
source_filename = "async_program_main_guarded_const_backed_alias_sourced_composed_dynamic_task_handle_forwarded_nested_array_repackage_spawn.ql"
target triple = "{{TARGET_TRIPLE}}"

declare ptr @malloc(i64)
declare void @free(ptr)

define ptr @qlrt_async_frame_alloc(i64 %size, i64 %align) {
entry:
  %frame_is_zero = icmp eq i64 %size, 0
  %frame_alloc_size = select i1 %frame_is_zero, i64 1, i64 %size
  %frame = call ptr @malloc(i64 %frame_alloc_size)
  ret ptr %frame
}

define ptr @qlrt_async_task_create(ptr %entry_fn, ptr %frame) {
entry:
  %task_end = getelementptr { ptr, ptr, ptr }, ptr null, i32 1
  %task_size = ptrtoint ptr %task_end to i64
  %task = call ptr @malloc(i64 %task_size)
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  store ptr %entry_fn, ptr %task_entry_ptr
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  store ptr %frame, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr null, ptr %task_result_ptr
  ret ptr %task
}

define ptr @qlrt_executor_spawn(ptr %executor, ptr %task) {
entry:
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  %task_entry = load ptr, ptr %task_entry_ptr
  %task_started = icmp eq ptr %task_entry, null
  br i1 %task_started, label %done, label %start

start:
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  %task_frame = load ptr, ptr %task_frame_ptr
  %task_result = call ptr %task_entry(ptr %task_frame)
  call void @free(ptr %task_frame)
  store ptr null, ptr %task_entry_ptr
  store ptr null, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr %task_result, ptr %task_result_ptr
  br label %done

done:
  ret ptr %task
}

define ptr @qlrt_task_await(ptr %handle) {
entry:
  %started = call ptr @qlrt_executor_spawn(ptr null, ptr %handle)
  %result_ptr_slot = getelementptr inbounds { ptr, ptr, ptr }, ptr %started, i32 0, i32 2
  %result_ptr = load ptr, ptr %result_ptr_slot
  call void @free(ptr %started)
  ret ptr %result_ptr
}

define void @qlrt_task_result_release(ptr %result) {
entry:
  call void @free(ptr %result)
  ret void
}

define i64 @ql_5_worker__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %async_body_frame_field0 = getelementptr inbounds { i64 }, ptr %frame, i32 0, i32 0
  %async_body_frame_value0 = load i64, ptr %async_body_frame_field0
  store i64 %async_body_frame_value0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  store i64 %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load i64, ptr %l0__return
  ret i64 %t1
}

define ptr @ql_5_worker__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_5_worker__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_5_worker(i64 %arg0) {
entry:
  %async_frame = call ptr @qlrt_async_frame_alloc(i64 8, i64 8)
  %async_frame_field0 = getelementptr inbounds { i64 }, ptr %async_frame, i32 0, i32 0
  store i64 %arg0, ptr %async_frame_field0
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_5_worker__async_entry, ptr %async_frame)
  ret ptr %async_task
}

define ptr @ql_6_forward(ptr %arg0) {
entry:
  %l0__return = alloca ptr
  %l1_task = alloca ptr
  store ptr %arg0, ptr %l1_task
  br label %bb0
bb0:
  %t0 = load ptr, ptr %l1_task
  store ptr %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load ptr, ptr %l0__return
  ret ptr %t1
}

define i64 @ql_7_main__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_row = alloca i64
  %l2__t0 = alloca [2 x i64]
  %l3_slots = alloca [2 x i64]
  %l4_alias_slots = alloca [2 x i64]
  %l5__t1 = alloca ptr
  %l6__t2 = alloca ptr
  %l7__t3 = alloca [2 x ptr]
  %l8__t4 = alloca { [2 x ptr] }
  %l9_pending = alloca { [2 x ptr] }
  %l10_alias = alloca [2 x ptr]
  %l11__t5 = alloca { i64 }
  %l12_slot = alloca { i64 }
  %l14__t7 = alloca i1
  %l15__t8 = alloca i64
  %l16_first = alloca i64
  %l17__t9 = alloca i64
  %l18__t10 = alloca ptr
  %l19__t11 = alloca ptr
  %l20__t12 = alloca ptr
  %l21__t13 = alloca ptr
  %l22__t14 = alloca [2 x ptr]
  %l23__t15 = alloca { [2 x ptr] }
  %l24__t16 = alloca { { [2 x ptr] }, ptr }
  %l25_env = alloca { { [2 x ptr] }, ptr }
  %l26__t17 = alloca ptr
  %l27_running = alloca ptr
  %l28__t18 = alloca i64
  %l29_second = alloca i64
  %l30__t19 = alloca i64
  %l31_extra = alloca i64
  %l32__t20 = alloca i64
  %l33_tail = alloca i64
  %l34__t21 = alloca i64
  %l35__t22 = alloca i64
  br label %bb0
bb0:
  store i64 0, ptr %l1_row
  %t0 = load i64, ptr %l1_row
  %t1 = load i64, ptr %l1_row
  %t2 = insertvalue [2 x i64] undef, i64 %t0, 0
  %t3 = insertvalue [2 x i64] %t2, i64 %t1, 1
  store [2 x i64] %t3, ptr %l2__t0
  %t4 = load [2 x i64], ptr %l2__t0
  store [2 x i64] %t4, ptr %l3_slots
  %t5 = load [2 x i64], ptr %l3_slots
  store [2 x i64] %t5, ptr %l4_alias_slots
  %t6 = call ptr @ql_5_worker(i64 8)
  store ptr %t6, ptr %l5__t1
  %t7 = call ptr @ql_5_worker(i64 14)
  store ptr %t7, ptr %l6__t2
  %t8 = load ptr, ptr %l5__t1
  %t9 = load ptr, ptr %l6__t2
  %t10 = insertvalue [2 x ptr] undef, ptr %t8, 0
  %t11 = insertvalue [2 x ptr] %t10, ptr %t9, 1
  store [2 x ptr] %t11, ptr %l7__t3
  %t12 = load [2 x ptr], ptr %l7__t3
  %t13 = insertvalue { [2 x ptr] } undef, [2 x ptr] %t12, 0
  store { [2 x ptr] } %t13, ptr %l8__t4
  %t14 = load { [2 x ptr] }, ptr %l8__t4
  store { [2 x ptr] } %t14, ptr %l9_pending
  %t15 = getelementptr inbounds { [2 x ptr] }, ptr %l9_pending, i32 0, i32 0
  %t16 = load [2 x ptr], ptr %t15
  store [2 x ptr] %t16, ptr %l10_alias
  %t17 = insertvalue { i64 } undef, i64 0, 0
  store { i64 } %t17, ptr %l11__t5
  %t18 = load { i64 }, ptr %l11__t5
  store { i64 } %t18, ptr %l12_slot
  %t19 = getelementptr inbounds { i64 }, ptr %l12_slot, i32 0, i32 0
  %t20 = load i64, ptr %t19
  %t21 = icmp eq i64 %t20, 0
  store i1 %t21, ptr %l14__t7
  %t22 = load i1, ptr %l14__t7
  br i1 %t22, label %bb3, label %bb2
bb1:
  %t23 = load i64, ptr %l0__return
  ret i64 %t23
bb2:
  %t24 = getelementptr inbounds { [2 x ptr] }, ptr %l9_pending, i32 0, i32 0
  %t25 = getelementptr inbounds [2 x ptr], ptr %t24, i64 0, i64 0
  %t26 = load ptr, ptr %t25
  %t27 = call ptr @ql_6_forward(ptr %t26)
  store ptr %t27, ptr %l20__t12
  %t28 = call ptr @ql_5_worker(i64 28)
  store ptr %t28, ptr %l21__t13
  %t29 = load ptr, ptr %l20__t12
  %t30 = load ptr, ptr %l21__t13
  %t31 = insertvalue [2 x ptr] undef, ptr %t29, 0
  %t32 = insertvalue [2 x ptr] %t31, ptr %t30, 1
  store [2 x ptr] %t32, ptr %l22__t14
  %t33 = load [2 x ptr], ptr %l22__t14
  %t34 = insertvalue { [2 x ptr] } undef, [2 x ptr] %t33, 0
  store { [2 x ptr] } %t34, ptr %l23__t15
  %t35 = load { [2 x ptr] }, ptr %l23__t15
  %t36 = getelementptr inbounds { [2 x ptr] }, ptr %l9_pending, i32 0, i32 0
  %t37 = getelementptr inbounds [2 x ptr], ptr %t36, i64 0, i64 1
  %t38 = load ptr, ptr %t37
  %t39 = insertvalue { { [2 x ptr] }, ptr } undef, { [2 x ptr] } %t35, 0
  %t40 = insertvalue { { [2 x ptr] }, ptr } %t39, ptr %t38, 1
  store { { [2 x ptr] }, ptr } %t40, ptr %l24__t16
  %t41 = load { { [2 x ptr] }, ptr }, ptr %l24__t16
  store { { [2 x ptr] }, ptr } %t41, ptr %l25_env
  %t42 = getelementptr inbounds { { [2 x ptr] }, ptr }, ptr %l24__t16, i32 0, i32 0
  %t43 = getelementptr inbounds { [2 x ptr] }, ptr %t42, i32 0, i32 0
  %t44 = getelementptr inbounds [2 x ptr], ptr %t43, i64 0, i64 0
  %t45 = load ptr, ptr %t44
  %t46 = call ptr @qlrt_executor_spawn(ptr null, ptr %t45)
  store ptr %t46, ptr %l26__t17
  %t47 = load ptr, ptr %l26__t17
  store ptr %t47, ptr %l27_running
  %t48 = load ptr, ptr %l26__t17
  %t49 = call ptr @qlrt_task_await(ptr %t48)
  %t50 = load i64, ptr %t49
  call void @qlrt_task_result_release(ptr %t49)
  store i64 %t50, ptr %l28__t18
  %t51 = load i64, ptr %l28__t18
  store i64 %t51, ptr %l29_second
  %t52 = getelementptr inbounds { { [2 x ptr] }, ptr }, ptr %l24__t16, i32 0, i32 0
  %t53 = getelementptr inbounds { [2 x ptr] }, ptr %t52, i32 0, i32 0
  %t54 = getelementptr inbounds [2 x ptr], ptr %t53, i64 0, i64 1
  %t55 = load ptr, ptr %t54
  %t56 = call ptr @qlrt_task_await(ptr %t55)
  %t57 = load i64, ptr %t56
  call void @qlrt_task_result_release(ptr %t56)
  store i64 %t57, ptr %l30__t19
  %t58 = load i64, ptr %l30__t19
  store i64 %t58, ptr %l31_extra
  %t59 = getelementptr inbounds { { [2 x ptr] }, ptr }, ptr %l24__t16, i32 0, i32 1
  %t60 = load ptr, ptr %t59
  %t61 = call ptr @qlrt_task_await(ptr %t60)
  %t62 = load i64, ptr %t61
  call void @qlrt_task_result_release(ptr %t61)
  store i64 %t62, ptr %l32__t20
  %t63 = load i64, ptr %l32__t20
  store i64 %t63, ptr %l33_tail
  %t64 = load i64, ptr %l29_second
  %t65 = load i64, ptr %l31_extra
  %t66 = add i64 %t64, %t65
  store i64 %t66, ptr %l34__t21
  %t67 = load i64, ptr %l34__t21
  %t68 = load i64, ptr %l33_tail
  %t69 = add i64 %t67, %t68
  store i64 %t69, ptr %l35__t22
  %t70 = load i64, ptr %l35__t22
  store i64 %t70, ptr %l0__return
  br label %bb1
bb3:
  %t71 = getelementptr inbounds { [2 x ptr] }, ptr %l9_pending, i32 0, i32 0
  %t72 = getelementptr inbounds [2 x ptr], ptr %t71, i64 0, i64 0
  %t73 = load ptr, ptr %t72
  %t74 = call ptr @qlrt_task_await(ptr %t73)
  %t75 = load i64, ptr %t74
  call void @qlrt_task_result_release(ptr %t74)
  store i64 %t75, ptr %l15__t8
  %t76 = load i64, ptr %l15__t8
  store i64 %t76, ptr %l16_first
  %t77 = load i64, ptr %l16_first
  %t78 = add i64 %t77, 12
  store i64 %t78, ptr %l17__t9
  %t79 = load i64, ptr %l17__t9
  %t80 = call ptr @ql_5_worker(i64 %t79)
  store ptr %t80, ptr %l18__t10
  %t81 = load ptr, ptr %l18__t10
  %t82 = getelementptr inbounds { [2 x ptr] }, ptr %l9_pending, i32 0, i32 0
  %t83 = getelementptr inbounds [2 x ptr], ptr %t82, i64 0, i64 0
  store ptr %t81, ptr %t83
  %t84 = load ptr, ptr %l18__t10
  store ptr %t84, ptr %l19__t11
  %t85 = load ptr, ptr %l19__t11
  br label %bb2
}

define ptr @ql_7_main__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_7_main__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_7_main() {
entry:
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_7_main__async_entry, ptr null)
  ret ptr %async_task
}

define i32 @main() {
entry:
  %async_main_task = call ptr @ql_7_main()
  %async_main_join = call ptr @qlrt_executor_spawn(ptr null, ptr %async_main_task)
  %async_main_res = call ptr @qlrt_task_await(ptr %async_main_join)
  %async_main_ret = load i64, ptr %async_main_res
  call void @qlrt_task_result_release(ptr %async_main_res)
  %async_main_exit = trunc i64 %async_main_ret to i32
  ret i32 %async_main_exit
}
