; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'async_program_main_aliased_guard_refined_const_backed_projected_root_task_handle_nested_array_repackage_spawn'
source_filename = "async_program_main_aliased_guard_refined_const_backed_projected_root_task_handle_nested_array_repackage_spawn.ql"
target triple = "x86_64-pc-windows-msvc"

declare ptr @malloc(i64)
declare void @free(ptr)

define ptr @qlrt_async_frame_alloc(i64 %size, i64 %align) {
entry:
  %frame_is_zero = icmp eq i64 %size, 0
  %frame_alloc_size = select i1 %frame_is_zero, i64 1, i64 %size
  %frame = call ptr @malloc(i64 %frame_alloc_size)
  ret ptr %frame
}

define ptr @qlrt_async_task_create(ptr %entry_fn, ptr %frame) {
entry:
  %task_end = getelementptr { ptr, ptr, ptr }, ptr null, i32 1
  %task_size = ptrtoint ptr %task_end to i64
  %task = call ptr @malloc(i64 %task_size)
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  store ptr %entry_fn, ptr %task_entry_ptr
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  store ptr %frame, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr null, ptr %task_result_ptr
  ret ptr %task
}

define ptr @qlrt_executor_spawn(ptr %executor, ptr %task) {
entry:
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  %task_entry = load ptr, ptr %task_entry_ptr
  %task_started = icmp eq ptr %task_entry, null
  br i1 %task_started, label %done, label %start

start:
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  %task_frame = load ptr, ptr %task_frame_ptr
  %task_result = call ptr %task_entry(ptr %task_frame)
  call void @free(ptr %task_frame)
  store ptr null, ptr %task_entry_ptr
  store ptr null, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr %task_result, ptr %task_result_ptr
  br label %done

done:
  ret ptr %task
}

define ptr @qlrt_task_await(ptr %handle) {
entry:
  %started = call ptr @qlrt_executor_spawn(ptr null, ptr %handle)
  %result_ptr_slot = getelementptr inbounds { ptr, ptr, ptr }, ptr %started, i32 0, i32 2
  %result_ptr = load ptr, ptr %result_ptr_slot
  call void @free(ptr %started)
  ret ptr %result_ptr
}

define void @qlrt_task_result_release(ptr %result) {
entry:
  call void @free(ptr %result)
  ret void
}

define i64 @ql_5_worker__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %async_body_frame_field0 = getelementptr inbounds { i64 }, ptr %frame, i32 0, i32 0
  %async_body_frame_value0 = load i64, ptr %async_body_frame_field0
  store i64 %async_body_frame_value0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  store i64 %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load i64, ptr %l0__return
  ret i64 %t1
}

define ptr @ql_5_worker__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_5_worker__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_5_worker(i64 %arg0) {
entry:
  %async_frame = call ptr @qlrt_async_frame_alloc(i64 8, i64 8)
  %async_frame_field0 = getelementptr inbounds { i64 }, ptr %async_frame, i32 0, i32 0
  store i64 %arg0, ptr %async_frame_field0
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_5_worker__async_entry, ptr %async_frame)
  ret ptr %async_task
}

define i64 @ql_6_main__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca ptr
  %l2__t1 = alloca ptr
  %l3__t2 = alloca [2 x ptr]
  %l4__t3 = alloca { [2 x ptr] }
  %l5_pending = alloca { [2 x ptr] }
  %l6_alias = alloca [2 x ptr]
  %l7__t4 = alloca { i64 }
  %l8_slot = alloca { i64 }
  %l10__t6 = alloca i1
  %l11__t7 = alloca i64
  %l12_first = alloca i64
  %l13__t8 = alloca i64
  %l14__t9 = alloca ptr
  %l15__t10 = alloca ptr
  %l16__t11 = alloca ptr
  %l17__t12 = alloca [2 x ptr]
  %l18__t13 = alloca { [2 x ptr] }
  %l19__t14 = alloca { { [2 x ptr] }, ptr }
  %l20_env = alloca { { [2 x ptr] }, ptr }
  %l21__t15 = alloca ptr
  %l22_running = alloca ptr
  %l23__t16 = alloca i64
  %l24_second = alloca i64
  %l25__t17 = alloca i64
  %l26_extra = alloca i64
  %l27__t18 = alloca i64
  %l28_tail = alloca i64
  %l29__t19 = alloca i64
  %l30__t20 = alloca i64
  br label %bb0
bb0:
  %t0 = call ptr @ql_5_worker(i64 8)
  store ptr %t0, ptr %l1__t0
  %t1 = call ptr @ql_5_worker(i64 14)
  store ptr %t1, ptr %l2__t1
  %t2 = load ptr, ptr %l1__t0
  %t3 = load ptr, ptr %l2__t1
  %t4 = insertvalue [2 x ptr] undef, ptr %t2, 0
  %t5 = insertvalue [2 x ptr] %t4, ptr %t3, 1
  store [2 x ptr] %t5, ptr %l3__t2
  %t6 = load [2 x ptr], ptr %l3__t2
  %t7 = insertvalue { [2 x ptr] } undef, [2 x ptr] %t6, 0
  store { [2 x ptr] } %t7, ptr %l4__t3
  %t8 = load { [2 x ptr] }, ptr %l4__t3
  store { [2 x ptr] } %t8, ptr %l5_pending
  %t9 = getelementptr inbounds { [2 x ptr] }, ptr %l5_pending, i32 0, i32 0
  %t10 = load [2 x ptr], ptr %t9
  store [2 x ptr] %t10, ptr %l6_alias
  %t11 = insertvalue { i64 } undef, i64 0, 0
  store { i64 } %t11, ptr %l7__t4
  %t12 = load { i64 }, ptr %l7__t4
  store { i64 } %t12, ptr %l8_slot
  %t13 = getelementptr inbounds { i64 }, ptr %l8_slot, i32 0, i32 0
  %t14 = load i64, ptr %t13
  %t15 = icmp eq i64 %t14, 0
  store i1 %t15, ptr %l10__t6
  %t16 = load i1, ptr %l10__t6
  br i1 %t16, label %bb3, label %bb2
bb1:
  %t17 = load i64, ptr %l0__return
  ret i64 %t17
bb2:
  %t18 = call ptr @ql_5_worker(i64 17)
  store ptr %t18, ptr %l16__t11
  %t19 = getelementptr inbounds { [2 x ptr] }, ptr %l5_pending, i32 0, i32 0
  %t20 = getelementptr inbounds { i64 }, ptr %l8_slot, i32 0, i32 0
  %t21 = load i64, ptr %t20
  %t22 = getelementptr inbounds [2 x ptr], ptr %t19, i64 0, i64 %t21
  %t23 = load ptr, ptr %t22
  %t24 = load ptr, ptr %l16__t11
  %t25 = insertvalue [2 x ptr] undef, ptr %t23, 0
  %t26 = insertvalue [2 x ptr] %t25, ptr %t24, 1
  store [2 x ptr] %t26, ptr %l17__t12
  %t27 = load [2 x ptr], ptr %l17__t12
  %t28 = insertvalue { [2 x ptr] } undef, [2 x ptr] %t27, 0
  store { [2 x ptr] } %t28, ptr %l18__t13
  %t29 = load { [2 x ptr] }, ptr %l18__t13
  %t30 = getelementptr inbounds { [2 x ptr] }, ptr %l5_pending, i32 0, i32 0
  %t31 = getelementptr inbounds [2 x ptr], ptr %t30, i64 0, i64 1
  %t32 = load ptr, ptr %t31
  %t33 = insertvalue { { [2 x ptr] }, ptr } undef, { [2 x ptr] } %t29, 0
  %t34 = insertvalue { { [2 x ptr] }, ptr } %t33, ptr %t32, 1
  store { { [2 x ptr] }, ptr } %t34, ptr %l19__t14
  %t35 = load { { [2 x ptr] }, ptr }, ptr %l19__t14
  store { { [2 x ptr] }, ptr } %t35, ptr %l20_env
  %t36 = getelementptr inbounds { { [2 x ptr] }, ptr }, ptr %l19__t14, i32 0, i32 0
  %t37 = getelementptr inbounds { [2 x ptr] }, ptr %t36, i32 0, i32 0
  %t38 = getelementptr inbounds [2 x ptr], ptr %t37, i64 0, i64 0
  %t39 = load ptr, ptr %t38
  %t40 = call ptr @qlrt_executor_spawn(ptr null, ptr %t39)
  store ptr %t40, ptr %l21__t15
  %t41 = load ptr, ptr %l21__t15
  store ptr %t41, ptr %l22_running
  %t42 = load ptr, ptr %l21__t15
  %t43 = call ptr @qlrt_task_await(ptr %t42)
  %t44 = load i64, ptr %t43
  call void @qlrt_task_result_release(ptr %t43)
  store i64 %t44, ptr %l23__t16
  %t45 = load i64, ptr %l23__t16
  store i64 %t45, ptr %l24_second
  %t46 = getelementptr inbounds { { [2 x ptr] }, ptr }, ptr %l19__t14, i32 0, i32 0
  %t47 = getelementptr inbounds { [2 x ptr] }, ptr %t46, i32 0, i32 0
  %t48 = getelementptr inbounds [2 x ptr], ptr %t47, i64 0, i64 1
  %t49 = load ptr, ptr %t48
  %t50 = call ptr @qlrt_task_await(ptr %t49)
  %t51 = load i64, ptr %t50
  call void @qlrt_task_result_release(ptr %t50)
  store i64 %t51, ptr %l25__t17
  %t52 = load i64, ptr %l25__t17
  store i64 %t52, ptr %l26_extra
  %t53 = getelementptr inbounds { { [2 x ptr] }, ptr }, ptr %l19__t14, i32 0, i32 1
  %t54 = load ptr, ptr %t53
  %t55 = call ptr @qlrt_task_await(ptr %t54)
  %t56 = load i64, ptr %t55
  call void @qlrt_task_result_release(ptr %t55)
  store i64 %t56, ptr %l27__t18
  %t57 = load i64, ptr %l27__t18
  store i64 %t57, ptr %l28_tail
  %t58 = load i64, ptr %l24_second
  %t59 = load i64, ptr %l26_extra
  %t60 = add i64 %t58, %t59
  store i64 %t60, ptr %l29__t19
  %t61 = load i64, ptr %l29__t19
  %t62 = load i64, ptr %l28_tail
  %t63 = add i64 %t61, %t62
  store i64 %t63, ptr %l30__t20
  %t64 = load i64, ptr %l30__t20
  store i64 %t64, ptr %l0__return
  br label %bb1
bb3:
  %t65 = getelementptr inbounds { [2 x ptr] }, ptr %l5_pending, i32 0, i32 0
  %t66 = getelementptr inbounds { i64 }, ptr %l8_slot, i32 0, i32 0
  %t67 = load i64, ptr %t66
  %t68 = getelementptr inbounds [2 x ptr], ptr %t65, i64 0, i64 %t67
  %t69 = load ptr, ptr %t68
  %t70 = call ptr @qlrt_task_await(ptr %t69)
  %t71 = load i64, ptr %t70
  call void @qlrt_task_result_release(ptr %t70)
  store i64 %t71, ptr %l11__t7
  %t72 = load i64, ptr %l11__t7
  store i64 %t72, ptr %l12_first
  %t73 = load i64, ptr %l12_first
  %t74 = add i64 %t73, 7
  store i64 %t74, ptr %l13__t8
  %t75 = load i64, ptr %l13__t8
  %t76 = call ptr @ql_5_worker(i64 %t75)
  store ptr %t76, ptr %l14__t9
  %t77 = load ptr, ptr %l14__t9
  %t78 = getelementptr inbounds { [2 x ptr] }, ptr %l5_pending, i32 0, i32 0
  %t79 = getelementptr inbounds [2 x ptr], ptr %t78, i64 0, i64 0
  store ptr %t77, ptr %t79
  %t80 = load ptr, ptr %l14__t9
  store ptr %t80, ptr %l15__t10
  %t81 = load ptr, ptr %l15__t10
  br label %bb2
}

define ptr @ql_6_main__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_6_main__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_6_main() {
entry:
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_6_main__async_entry, ptr null)
  ret ptr %async_task
}

define i32 @main() {
entry:
  %async_main_task = call ptr @ql_6_main()
  %async_main_join = call ptr @qlrt_executor_spawn(ptr null, ptr %async_main_task)
  %async_main_res = call ptr @qlrt_task_await(ptr %async_main_join)
  %async_main_ret = load i64, ptr %async_main_res
  call void @qlrt_task_result_release(ptr %async_main_res)
  %async_main_exit = trunc i64 %async_main_ret to i32
  ret i32 %async_main_exit
}
