; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'async_program_main_guarded_const_backed_double_root_double_source_row_slot_alias_sourced_composed_dynamic_task_handle_forwarded_nested_array_repackage_spawn'
source_filename = "async_program_main_guarded_const_backed_double_root_double_source_row_slot_alias_sourced_composed_dynamic_task_handle_forwarded_nested_array_repackage_spawn.ql"
target triple = "x86_64-pc-windows-msvc"

declare ptr @malloc(i64)
declare void @free(ptr)

define ptr @qlrt_async_frame_alloc(i64 %size, i64 %align) {
entry:
  %frame_is_zero = icmp eq i64 %size, 0
  %frame_alloc_size = select i1 %frame_is_zero, i64 1, i64 %size
  %frame = call ptr @malloc(i64 %frame_alloc_size)
  ret ptr %frame
}

define ptr @qlrt_async_task_create(ptr %entry_fn, ptr %frame) {
entry:
  %task_end = getelementptr { ptr, ptr, ptr }, ptr null, i32 1
  %task_size = ptrtoint ptr %task_end to i64
  %task = call ptr @malloc(i64 %task_size)
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  store ptr %entry_fn, ptr %task_entry_ptr
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  store ptr %frame, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr null, ptr %task_result_ptr
  ret ptr %task
}

define ptr @qlrt_executor_spawn(ptr %executor, ptr %task) {
entry:
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  %task_entry = load ptr, ptr %task_entry_ptr
  %task_started = icmp eq ptr %task_entry, null
  br i1 %task_started, label %done, label %start

start:
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  %task_frame = load ptr, ptr %task_frame_ptr
  %task_result = call ptr %task_entry(ptr %task_frame)
  call void @free(ptr %task_frame)
  store ptr null, ptr %task_entry_ptr
  store ptr null, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr %task_result, ptr %task_result_ptr
  br label %done

done:
  ret ptr %task
}

define ptr @qlrt_task_await(ptr %handle) {
entry:
  %started = call ptr @qlrt_executor_spawn(ptr null, ptr %handle)
  %result_ptr_slot = getelementptr inbounds { ptr, ptr, ptr }, ptr %started, i32 0, i32 2
  %result_ptr = load ptr, ptr %result_ptr_slot
  call void @free(ptr %started)
  ret ptr %result_ptr
}

define void @qlrt_task_result_release(ptr %result) {
entry:
  call void @free(ptr %result)
  ret void
}

define i64 @ql_5_worker__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %async_body_frame_field0 = getelementptr inbounds { i64 }, ptr %frame, i32 0, i32 0
  %async_body_frame_value0 = load i64, ptr %async_body_frame_field0
  store i64 %async_body_frame_value0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  store i64 %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load i64, ptr %l0__return
  ret i64 %t1
}

define ptr @ql_5_worker__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_5_worker__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_5_worker(i64 %arg0) {
entry:
  %async_frame = call ptr @qlrt_async_frame_alloc(i64 8, i64 8)
  %async_frame_field0 = getelementptr inbounds { i64 }, ptr %async_frame, i32 0, i32 0
  store i64 %arg0, ptr %async_frame_field0
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_5_worker__async_entry, ptr %async_frame)
  ret ptr %async_task
}

define ptr @ql_6_forward(ptr %arg0) {
entry:
  %l0__return = alloca ptr
  %l1_task = alloca ptr
  store ptr %arg0, ptr %l1_task
  br label %bb0
bb0:
  %t0 = load ptr, ptr %l1_task
  store ptr %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load ptr, ptr %l0__return
  ret ptr %t1
}

define i64 @ql_7_main__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_row_root = alloca i64
  %l2_row = alloca i64
  %l3__t0 = alloca [2 x i64]
  %l4_slots = alloca [2 x i64]
  %l5_slot_root = alloca [2 x i64]
  %l6_alias_slots = alloca [2 x i64]
  %l7__t1 = alloca ptr
  %l8__t2 = alloca ptr
  %l9__t3 = alloca [2 x ptr]
  %l10__t4 = alloca { [2 x ptr] }
  %l11_pending = alloca { [2 x ptr] }
  %l12_root = alloca [2 x ptr]
  %l13_alias = alloca [2 x ptr]
  %l14__t5 = alloca { i64 }
  %l15_slot = alloca { i64 }
  %l16_slot_alias = alloca { i64 }
  %l18__t7 = alloca i1
  %l19__t8 = alloca i64
  %l20_first = alloca i64
  %l21__t9 = alloca i64
  %l22__t10 = alloca ptr
  %l23__t11 = alloca ptr
  %l24__t12 = alloca ptr
  %l25__t13 = alloca ptr
  %l26__t14 = alloca [2 x ptr]
  %l27__t15 = alloca { [2 x ptr] }
  %l28__t16 = alloca { { [2 x ptr] }, ptr }
  %l29_env = alloca { { [2 x ptr] }, ptr }
  %l30__t17 = alloca ptr
  %l31_running = alloca ptr
  %l32__t18 = alloca i64
  %l33_second = alloca i64
  %l34__t19 = alloca i64
  %l35_extra = alloca i64
  %l36__t20 = alloca i64
  %l37_tail = alloca i64
  %l38__t21 = alloca i64
  %l39__t22 = alloca i64
  br label %bb0
bb0:
  store i64 0, ptr %l1_row_root
  %t0 = load i64, ptr %l1_row_root
  store i64 %t0, ptr %l2_row
  %t1 = load i64, ptr %l2_row
  %t2 = load i64, ptr %l2_row
  %t3 = insertvalue [2 x i64] undef, i64 %t1, 0
  %t4 = insertvalue [2 x i64] %t3, i64 %t2, 1
  store [2 x i64] %t4, ptr %l3__t0
  %t5 = load [2 x i64], ptr %l3__t0
  store [2 x i64] %t5, ptr %l4_slots
  %t6 = load [2 x i64], ptr %l4_slots
  store [2 x i64] %t6, ptr %l5_slot_root
  %t7 = load [2 x i64], ptr %l5_slot_root
  store [2 x i64] %t7, ptr %l6_alias_slots
  %t8 = call ptr @ql_5_worker(i64 8)
  store ptr %t8, ptr %l7__t1
  %t9 = call ptr @ql_5_worker(i64 14)
  store ptr %t9, ptr %l8__t2
  %t10 = load ptr, ptr %l7__t1
  %t11 = load ptr, ptr %l8__t2
  %t12 = insertvalue [2 x ptr] undef, ptr %t10, 0
  %t13 = insertvalue [2 x ptr] %t12, ptr %t11, 1
  store [2 x ptr] %t13, ptr %l9__t3
  %t14 = load [2 x ptr], ptr %l9__t3
  %t15 = insertvalue { [2 x ptr] } undef, [2 x ptr] %t14, 0
  store { [2 x ptr] } %t15, ptr %l10__t4
  %t16 = load { [2 x ptr] }, ptr %l10__t4
  store { [2 x ptr] } %t16, ptr %l11_pending
  %t17 = getelementptr inbounds { [2 x ptr] }, ptr %l11_pending, i32 0, i32 0
  %t18 = load [2 x ptr], ptr %t17
  store [2 x ptr] %t18, ptr %l12_root
  %t19 = getelementptr inbounds { [2 x ptr] }, ptr %l11_pending, i32 0, i32 0
  %t20 = load [2 x ptr], ptr %t19
  store [2 x ptr] %t20, ptr %l13_alias
  %t21 = insertvalue { i64 } undef, i64 0, 0
  store { i64 } %t21, ptr %l14__t5
  %t22 = load { i64 }, ptr %l14__t5
  store { i64 } %t22, ptr %l15_slot
  %t23 = load { i64 }, ptr %l15_slot
  store { i64 } %t23, ptr %l16_slot_alias
  %t24 = getelementptr inbounds { i64 }, ptr %l16_slot_alias, i32 0, i32 0
  %t25 = load i64, ptr %t24
  %t26 = icmp eq i64 %t25, 0
  store i1 %t26, ptr %l18__t7
  %t27 = load i1, ptr %l18__t7
  br i1 %t27, label %bb3, label %bb2
bb1:
  %t28 = load i64, ptr %l0__return
  ret i64 %t28
bb2:
  %t29 = getelementptr inbounds { [2 x ptr] }, ptr %l11_pending, i32 0, i32 0
  %t30 = load i64, ptr %l2_row
  %t31 = getelementptr inbounds [2 x i64], ptr %l6_alias_slots, i64 0, i64 %t30
  %t32 = load i64, ptr %t31
  %t33 = getelementptr inbounds [2 x ptr], ptr %t29, i64 0, i64 %t32
  %t34 = load ptr, ptr %t33
  %t35 = call ptr @ql_6_forward(ptr %t34)
  store ptr %t35, ptr %l24__t12
  %t36 = call ptr @ql_5_worker(i64 34)
  store ptr %t36, ptr %l25__t13
  %t37 = load ptr, ptr %l24__t12
  %t38 = load ptr, ptr %l25__t13
  %t39 = insertvalue [2 x ptr] undef, ptr %t37, 0
  %t40 = insertvalue [2 x ptr] %t39, ptr %t38, 1
  store [2 x ptr] %t40, ptr %l26__t14
  %t41 = load [2 x ptr], ptr %l26__t14
  %t42 = insertvalue { [2 x ptr] } undef, [2 x ptr] %t41, 0
  store { [2 x ptr] } %t42, ptr %l27__t15
  %t43 = load { [2 x ptr] }, ptr %l27__t15
  %t44 = getelementptr inbounds { [2 x ptr] }, ptr %l11_pending, i32 0, i32 0
  %t45 = getelementptr inbounds [2 x ptr], ptr %t44, i64 0, i64 1
  %t46 = load ptr, ptr %t45
  %t47 = insertvalue { { [2 x ptr] }, ptr } undef, { [2 x ptr] } %t43, 0
  %t48 = insertvalue { { [2 x ptr] }, ptr } %t47, ptr %t46, 1
  store { { [2 x ptr] }, ptr } %t48, ptr %l28__t16
  %t49 = load { { [2 x ptr] }, ptr }, ptr %l28__t16
  store { { [2 x ptr] }, ptr } %t49, ptr %l29_env
  %t50 = getelementptr inbounds { { [2 x ptr] }, ptr }, ptr %l28__t16, i32 0, i32 0
  %t51 = getelementptr inbounds { [2 x ptr] }, ptr %t50, i32 0, i32 0
  %t52 = getelementptr inbounds [2 x ptr], ptr %t51, i64 0, i64 0
  %t53 = load ptr, ptr %t52
  %t54 = call ptr @qlrt_executor_spawn(ptr null, ptr %t53)
  store ptr %t54, ptr %l30__t17
  %t55 = load ptr, ptr %l30__t17
  store ptr %t55, ptr %l31_running
  %t56 = load ptr, ptr %l30__t17
  %t57 = call ptr @qlrt_task_await(ptr %t56)
  %t58 = load i64, ptr %t57
  call void @qlrt_task_result_release(ptr %t57)
  store i64 %t58, ptr %l32__t18
  %t59 = load i64, ptr %l32__t18
  store i64 %t59, ptr %l33_second
  %t60 = getelementptr inbounds { { [2 x ptr] }, ptr }, ptr %l28__t16, i32 0, i32 0
  %t61 = getelementptr inbounds { [2 x ptr] }, ptr %t60, i32 0, i32 0
  %t62 = getelementptr inbounds [2 x ptr], ptr %t61, i64 0, i64 1
  %t63 = load ptr, ptr %t62
  %t64 = call ptr @qlrt_task_await(ptr %t63)
  %t65 = load i64, ptr %t64
  call void @qlrt_task_result_release(ptr %t64)
  store i64 %t65, ptr %l34__t19
  %t66 = load i64, ptr %l34__t19
  store i64 %t66, ptr %l35_extra
  %t67 = getelementptr inbounds { { [2 x ptr] }, ptr }, ptr %l28__t16, i32 0, i32 1
  %t68 = load ptr, ptr %t67
  %t69 = call ptr @qlrt_task_await(ptr %t68)
  %t70 = load i64, ptr %t69
  call void @qlrt_task_result_release(ptr %t69)
  store i64 %t70, ptr %l36__t20
  %t71 = load i64, ptr %l36__t20
  store i64 %t71, ptr %l37_tail
  %t72 = load i64, ptr %l33_second
  %t73 = load i64, ptr %l35_extra
  %t74 = add i64 %t72, %t73
  store i64 %t74, ptr %l38__t21
  %t75 = load i64, ptr %l38__t21
  %t76 = load i64, ptr %l37_tail
  %t77 = add i64 %t75, %t76
  store i64 %t77, ptr %l39__t22
  %t78 = load i64, ptr %l39__t22
  store i64 %t78, ptr %l0__return
  br label %bb1
bb3:
  %t79 = getelementptr inbounds { [2 x ptr] }, ptr %l11_pending, i32 0, i32 0
  %t80 = load i64, ptr %l2_row
  %t81 = getelementptr inbounds [2 x i64], ptr %l6_alias_slots, i64 0, i64 %t80
  %t82 = load i64, ptr %t81
  %t83 = getelementptr inbounds [2 x ptr], ptr %t79, i64 0, i64 %t82
  %t84 = load ptr, ptr %t83
  %t85 = call ptr @qlrt_task_await(ptr %t84)
  %t86 = load i64, ptr %t85
  call void @qlrt_task_result_release(ptr %t85)
  store i64 %t86, ptr %l19__t8
  %t87 = load i64, ptr %l19__t8
  store i64 %t87, ptr %l20_first
  %t88 = load i64, ptr %l20_first
  %t89 = add i64 %t88, 16
  store i64 %t89, ptr %l21__t9
  %t90 = load i64, ptr %l21__t9
  %t91 = call ptr @ql_5_worker(i64 %t90)
  store ptr %t91, ptr %l22__t10
  %t92 = load ptr, ptr %l22__t10
  %t93 = getelementptr inbounds { [2 x ptr] }, ptr %l11_pending, i32 0, i32 0
  %t94 = load i64, ptr %l2_row
  %t95 = getelementptr inbounds [2 x i64], ptr %l4_slots, i64 0, i64 %t94
  %t96 = load i64, ptr %t95
  %t97 = getelementptr inbounds [2 x ptr], ptr %t93, i64 0, i64 %t96
  store ptr %t92, ptr %t97
  %t98 = load ptr, ptr %l22__t10
  store ptr %t98, ptr %l23__t11
  %t99 = load ptr, ptr %l23__t11
  br label %bb2
}

define ptr @ql_7_main__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_7_main__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_7_main() {
entry:
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_7_main__async_entry, ptr null)
  ret ptr %async_task
}

define i32 @main() {
entry:
  %async_main_task = call ptr @ql_7_main()
  %async_main_join = call ptr @qlrt_executor_spawn(ptr null, ptr %async_main_task)
  %async_main_res = call ptr @qlrt_task_await(ptr %async_main_join)
  %async_main_ret = load i64, ptr %async_main_res
  call void @qlrt_task_result_release(ptr %async_main_res)
  %async_main_exit = trunc i64 %async_main_ret to i32
  ret i32 %async_main_exit
}
