; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'async_program_main_guarded_const_backed_double_root_alias_sourced_composed_dynamic_task_handle_forwarded_nested_array_repackage_spawn'
source_filename = "async_program_main_guarded_const_backed_double_root_alias_sourced_composed_dynamic_task_handle_forwarded_nested_array_repackage_spawn.ql"
target triple = "x86_64-pc-windows-msvc"

declare ptr @malloc(i64)
declare void @free(ptr)

define ptr @qlrt_async_frame_alloc(i64 %size, i64 %align) {
entry:
  %frame_is_zero = icmp eq i64 %size, 0
  %frame_alloc_size = select i1 %frame_is_zero, i64 1, i64 %size
  %frame = call ptr @malloc(i64 %frame_alloc_size)
  ret ptr %frame
}

define ptr @qlrt_async_task_create(ptr %entry_fn, ptr %frame) {
entry:
  %task_end = getelementptr { ptr, ptr, ptr }, ptr null, i32 1
  %task_size = ptrtoint ptr %task_end to i64
  %task = call ptr @malloc(i64 %task_size)
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  store ptr %entry_fn, ptr %task_entry_ptr
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  store ptr %frame, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr null, ptr %task_result_ptr
  ret ptr %task
}

define ptr @qlrt_executor_spawn(ptr %executor, ptr %task) {
entry:
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  %task_entry = load ptr, ptr %task_entry_ptr
  %task_started = icmp eq ptr %task_entry, null
  br i1 %task_started, label %done, label %start

start:
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  %task_frame = load ptr, ptr %task_frame_ptr
  %task_result = call ptr %task_entry(ptr %task_frame)
  call void @free(ptr %task_frame)
  store ptr null, ptr %task_entry_ptr
  store ptr null, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr %task_result, ptr %task_result_ptr
  br label %done

done:
  ret ptr %task
}

define ptr @qlrt_task_await(ptr %handle) {
entry:
  %started = call ptr @qlrt_executor_spawn(ptr null, ptr %handle)
  %result_ptr_slot = getelementptr inbounds { ptr, ptr, ptr }, ptr %started, i32 0, i32 2
  %result_ptr = load ptr, ptr %result_ptr_slot
  call void @free(ptr %started)
  ret ptr %result_ptr
}

define void @qlrt_task_result_release(ptr %result) {
entry:
  call void @free(ptr %result)
  ret void
}

define i64 @ql_5_worker__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %async_body_frame_field0 = getelementptr inbounds { i64 }, ptr %frame, i32 0, i32 0
  %async_body_frame_value0 = load i64, ptr %async_body_frame_field0
  store i64 %async_body_frame_value0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  store i64 %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load i64, ptr %l0__return
  ret i64 %t1
}

define ptr @ql_5_worker__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_5_worker__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_5_worker(i64 %arg0) {
entry:
  %async_frame = call ptr @qlrt_async_frame_alloc(i64 8, i64 8)
  %async_frame_field0 = getelementptr inbounds { i64 }, ptr %async_frame, i32 0, i32 0
  store i64 %arg0, ptr %async_frame_field0
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_5_worker__async_entry, ptr %async_frame)
  ret ptr %async_task
}

define ptr @ql_6_forward(ptr %arg0) {
entry:
  %l0__return = alloca ptr
  %l1_task = alloca ptr
  store ptr %arg0, ptr %l1_task
  br label %bb0
bb0:
  %t0 = load ptr, ptr %l1_task
  store ptr %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load ptr, ptr %l0__return
  ret ptr %t1
}

define i64 @ql_7_main__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_row = alloca i64
  %l2__t0 = alloca [2 x i64]
  %l3_slots = alloca [2 x i64]
  %l4_alias_slots = alloca [2 x i64]
  %l5__t1 = alloca ptr
  %l6__t2 = alloca ptr
  %l7__t3 = alloca [2 x ptr]
  %l8__t4 = alloca { [2 x ptr] }
  %l9_pending = alloca { [2 x ptr] }
  %l10_root = alloca [2 x ptr]
  %l11_alias = alloca [2 x ptr]
  %l12__t5 = alloca { i64 }
  %l13_slot = alloca { i64 }
  %l15__t7 = alloca i1
  %l16__t8 = alloca i64
  %l17_first = alloca i64
  %l18__t9 = alloca i64
  %l19__t10 = alloca ptr
  %l20__t11 = alloca ptr
  %l21__t12 = alloca ptr
  %l22__t13 = alloca ptr
  %l23__t14 = alloca [2 x ptr]
  %l24__t15 = alloca { [2 x ptr] }
  %l25__t16 = alloca { { [2 x ptr] }, ptr }
  %l26_env = alloca { { [2 x ptr] }, ptr }
  %l27__t17 = alloca ptr
  %l28_running = alloca ptr
  %l29__t18 = alloca i64
  %l30_second = alloca i64
  %l31__t19 = alloca i64
  %l32_extra = alloca i64
  %l33__t20 = alloca i64
  %l34_tail = alloca i64
  %l35__t21 = alloca i64
  %l36__t22 = alloca i64
  br label %bb0
bb0:
  store i64 0, ptr %l1_row
  %t0 = load i64, ptr %l1_row
  %t1 = load i64, ptr %l1_row
  %t2 = insertvalue [2 x i64] undef, i64 %t0, 0
  %t3 = insertvalue [2 x i64] %t2, i64 %t1, 1
  store [2 x i64] %t3, ptr %l2__t0
  %t4 = load [2 x i64], ptr %l2__t0
  store [2 x i64] %t4, ptr %l3_slots
  %t5 = load [2 x i64], ptr %l3_slots
  store [2 x i64] %t5, ptr %l4_alias_slots
  %t6 = call ptr @ql_5_worker(i64 8)
  store ptr %t6, ptr %l5__t1
  %t7 = call ptr @ql_5_worker(i64 14)
  store ptr %t7, ptr %l6__t2
  %t8 = load ptr, ptr %l5__t1
  %t9 = load ptr, ptr %l6__t2
  %t10 = insertvalue [2 x ptr] undef, ptr %t8, 0
  %t11 = insertvalue [2 x ptr] %t10, ptr %t9, 1
  store [2 x ptr] %t11, ptr %l7__t3
  %t12 = load [2 x ptr], ptr %l7__t3
  %t13 = insertvalue { [2 x ptr] } undef, [2 x ptr] %t12, 0
  store { [2 x ptr] } %t13, ptr %l8__t4
  %t14 = load { [2 x ptr] }, ptr %l8__t4
  store { [2 x ptr] } %t14, ptr %l9_pending
  %t15 = getelementptr inbounds { [2 x ptr] }, ptr %l9_pending, i32 0, i32 0
  %t16 = load [2 x ptr], ptr %t15
  store [2 x ptr] %t16, ptr %l10_root
  %t17 = getelementptr inbounds { [2 x ptr] }, ptr %l9_pending, i32 0, i32 0
  %t18 = load [2 x ptr], ptr %t17
  store [2 x ptr] %t18, ptr %l11_alias
  %t19 = insertvalue { i64 } undef, i64 0, 0
  store { i64 } %t19, ptr %l12__t5
  %t20 = load { i64 }, ptr %l12__t5
  store { i64 } %t20, ptr %l13_slot
  %t21 = getelementptr inbounds { i64 }, ptr %l13_slot, i32 0, i32 0
  %t22 = load i64, ptr %t21
  %t23 = icmp eq i64 %t22, 0
  store i1 %t23, ptr %l15__t7
  %t24 = load i1, ptr %l15__t7
  br i1 %t24, label %bb3, label %bb2
bb1:
  %t25 = load i64, ptr %l0__return
  ret i64 %t25
bb2:
  %t26 = getelementptr inbounds { [2 x ptr] }, ptr %l9_pending, i32 0, i32 0
  %t27 = load i64, ptr %l1_row
  %t28 = getelementptr inbounds [2 x i64], ptr %l4_alias_slots, i64 0, i64 %t27
  %t29 = load i64, ptr %t28
  %t30 = getelementptr inbounds [2 x ptr], ptr %t26, i64 0, i64 %t29
  %t31 = load ptr, ptr %t30
  %t32 = call ptr @ql_6_forward(ptr %t31)
  store ptr %t32, ptr %l21__t12
  %t33 = call ptr @ql_5_worker(i64 29)
  store ptr %t33, ptr %l22__t13
  %t34 = load ptr, ptr %l21__t12
  %t35 = load ptr, ptr %l22__t13
  %t36 = insertvalue [2 x ptr] undef, ptr %t34, 0
  %t37 = insertvalue [2 x ptr] %t36, ptr %t35, 1
  store [2 x ptr] %t37, ptr %l23__t14
  %t38 = load [2 x ptr], ptr %l23__t14
  %t39 = insertvalue { [2 x ptr] } undef, [2 x ptr] %t38, 0
  store { [2 x ptr] } %t39, ptr %l24__t15
  %t40 = load { [2 x ptr] }, ptr %l24__t15
  %t41 = getelementptr inbounds { [2 x ptr] }, ptr %l9_pending, i32 0, i32 0
  %t42 = getelementptr inbounds [2 x ptr], ptr %t41, i64 0, i64 1
  %t43 = load ptr, ptr %t42
  %t44 = insertvalue { { [2 x ptr] }, ptr } undef, { [2 x ptr] } %t40, 0
  %t45 = insertvalue { { [2 x ptr] }, ptr } %t44, ptr %t43, 1
  store { { [2 x ptr] }, ptr } %t45, ptr %l25__t16
  %t46 = load { { [2 x ptr] }, ptr }, ptr %l25__t16
  store { { [2 x ptr] }, ptr } %t46, ptr %l26_env
  %t47 = getelementptr inbounds { { [2 x ptr] }, ptr }, ptr %l25__t16, i32 0, i32 0
  %t48 = getelementptr inbounds { [2 x ptr] }, ptr %t47, i32 0, i32 0
  %t49 = getelementptr inbounds [2 x ptr], ptr %t48, i64 0, i64 0
  %t50 = load ptr, ptr %t49
  %t51 = call ptr @qlrt_executor_spawn(ptr null, ptr %t50)
  store ptr %t51, ptr %l27__t17
  %t52 = load ptr, ptr %l27__t17
  store ptr %t52, ptr %l28_running
  %t53 = load ptr, ptr %l27__t17
  %t54 = call ptr @qlrt_task_await(ptr %t53)
  %t55 = load i64, ptr %t54
  call void @qlrt_task_result_release(ptr %t54)
  store i64 %t55, ptr %l29__t18
  %t56 = load i64, ptr %l29__t18
  store i64 %t56, ptr %l30_second
  %t57 = getelementptr inbounds { { [2 x ptr] }, ptr }, ptr %l25__t16, i32 0, i32 0
  %t58 = getelementptr inbounds { [2 x ptr] }, ptr %t57, i32 0, i32 0
  %t59 = getelementptr inbounds [2 x ptr], ptr %t58, i64 0, i64 1
  %t60 = load ptr, ptr %t59
  %t61 = call ptr @qlrt_task_await(ptr %t60)
  %t62 = load i64, ptr %t61
  call void @qlrt_task_result_release(ptr %t61)
  store i64 %t62, ptr %l31__t19
  %t63 = load i64, ptr %l31__t19
  store i64 %t63, ptr %l32_extra
  %t64 = getelementptr inbounds { { [2 x ptr] }, ptr }, ptr %l25__t16, i32 0, i32 1
  %t65 = load ptr, ptr %t64
  %t66 = call ptr @qlrt_task_await(ptr %t65)
  %t67 = load i64, ptr %t66
  call void @qlrt_task_result_release(ptr %t66)
  store i64 %t67, ptr %l33__t20
  %t68 = load i64, ptr %l33__t20
  store i64 %t68, ptr %l34_tail
  %t69 = load i64, ptr %l30_second
  %t70 = load i64, ptr %l32_extra
  %t71 = add i64 %t69, %t70
  store i64 %t71, ptr %l35__t21
  %t72 = load i64, ptr %l35__t21
  %t73 = load i64, ptr %l34_tail
  %t74 = add i64 %t72, %t73
  store i64 %t74, ptr %l36__t22
  %t75 = load i64, ptr %l36__t22
  store i64 %t75, ptr %l0__return
  br label %bb1
bb3:
  %t76 = getelementptr inbounds { [2 x ptr] }, ptr %l9_pending, i32 0, i32 0
  %t77 = load i64, ptr %l1_row
  %t78 = getelementptr inbounds [2 x i64], ptr %l4_alias_slots, i64 0, i64 %t77
  %t79 = load i64, ptr %t78
  %t80 = getelementptr inbounds [2 x ptr], ptr %t76, i64 0, i64 %t79
  %t81 = load ptr, ptr %t80
  %t82 = call ptr @qlrt_task_await(ptr %t81)
  %t83 = load i64, ptr %t82
  call void @qlrt_task_result_release(ptr %t82)
  store i64 %t83, ptr %l16__t8
  %t84 = load i64, ptr %l16__t8
  store i64 %t84, ptr %l17_first
  %t85 = load i64, ptr %l17_first
  %t86 = add i64 %t85, 13
  store i64 %t86, ptr %l18__t9
  %t87 = load i64, ptr %l18__t9
  %t88 = call ptr @ql_5_worker(i64 %t87)
  store ptr %t88, ptr %l19__t10
  %t89 = load ptr, ptr %l19__t10
  %t90 = getelementptr inbounds { [2 x ptr] }, ptr %l9_pending, i32 0, i32 0
  %t91 = load i64, ptr %l1_row
  %t92 = getelementptr inbounds [2 x i64], ptr %l3_slots, i64 0, i64 %t91
  %t93 = load i64, ptr %t92
  %t94 = getelementptr inbounds [2 x ptr], ptr %t90, i64 0, i64 %t93
  store ptr %t89, ptr %t94
  %t95 = load ptr, ptr %l19__t10
  store ptr %t95, ptr %l20__t11
  %t96 = load ptr, ptr %l20__t11
  br label %bb2
}

define ptr @ql_7_main__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_7_main__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_7_main() {
entry:
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_7_main__async_entry, ptr null)
  ret ptr %async_task
}

define i32 @main() {
entry:
  %async_main_task = call ptr @ql_7_main()
  %async_main_join = call ptr @qlrt_executor_spawn(ptr null, ptr %async_main_task)
  %async_main_res = call ptr @qlrt_task_await(ptr %async_main_join)
  %async_main_ret = load i64, ptr %async_main_res
  call void @qlrt_task_result_release(ptr %async_main_res)
  %async_main_exit = trunc i64 %async_main_ret to i32
  ret i32 %async_main_exit
}
