; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'async_program_main_composed_dynamic_task_handle_reinit'
source_filename = "async_program_main_composed_dynamic_task_handle_reinit.ql"
target triple = "x86_64-pc-windows-msvc"

declare ptr @malloc(i64)
declare void @free(ptr)

define ptr @qlrt_async_frame_alloc(i64 %size, i64 %align) {
entry:
  %frame_is_zero = icmp eq i64 %size, 0
  %frame_alloc_size = select i1 %frame_is_zero, i64 1, i64 %size
  %frame = call ptr @malloc(i64 %frame_alloc_size)
  ret ptr %frame
}

define ptr @qlrt_async_task_create(ptr %entry_fn, ptr %frame) {
entry:
  %task_end = getelementptr { ptr, ptr, ptr }, ptr null, i32 1
  %task_size = ptrtoint ptr %task_end to i64
  %task = call ptr @malloc(i64 %task_size)
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  store ptr %entry_fn, ptr %task_entry_ptr
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  store ptr %frame, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr null, ptr %task_result_ptr
  ret ptr %task
}

define ptr @qlrt_executor_spawn(ptr %executor, ptr %task) {
entry:
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  %task_entry = load ptr, ptr %task_entry_ptr
  %task_started = icmp eq ptr %task_entry, null
  br i1 %task_started, label %done, label %start

start:
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  %task_frame = load ptr, ptr %task_frame_ptr
  %task_result = call ptr %task_entry(ptr %task_frame)
  call void @free(ptr %task_frame)
  store ptr null, ptr %task_entry_ptr
  store ptr null, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr %task_result, ptr %task_result_ptr
  br label %done

done:
  ret ptr %task
}

define ptr @qlrt_task_await(ptr %handle) {
entry:
  %started = call ptr @qlrt_executor_spawn(ptr null, ptr %handle)
  %result_ptr_slot = getelementptr inbounds { ptr, ptr, ptr }, ptr %started, i32 0, i32 2
  %result_ptr = load ptr, ptr %result_ptr_slot
  call void @free(ptr %started)
  ret ptr %result_ptr
}

define void @qlrt_task_result_release(ptr %result) {
entry:
  call void @free(ptr %result)
  ret void
}

define i64 @ql_0_worker__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %async_body_frame_field0 = getelementptr inbounds { i64 }, ptr %frame, i32 0, i32 0
  %async_body_frame_value0 = load i64, ptr %async_body_frame_field0
  store i64 %async_body_frame_value0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  store i64 %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load i64, ptr %l0__return
  ret i64 %t1
}

define ptr @ql_0_worker__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_0_worker__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_0_worker(i64 %arg0) {
entry:
  %async_frame = call ptr @qlrt_async_frame_alloc(i64 8, i64 8)
  %async_frame_field0 = getelementptr inbounds { i64 }, ptr %async_frame, i32 0, i32 0
  store i64 %arg0, ptr %async_frame_field0
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_0_worker__async_entry, ptr %async_frame)
  ret ptr %async_task
}

define i64 @ql_1_choose() {
entry:
  %l0__return = alloca i64
  br label %bb0
bb0:
  store i64 0, ptr %l0__return
  br label %bb1
bb1:
  %t0 = load i64, ptr %l0__return
  ret i64 %t0
}

define i64 @ql_2_score(i64 %arg0) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  store i64 %arg0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  store i64 %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load i64, ptr %l0__return
  ret i64 %t1
}

define i64 @ql_3_main__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca i64
  %l2_row = alloca i64
  %l3__t1 = alloca ptr
  %l4__t2 = alloca ptr
  %l5__t3 = alloca [2 x ptr]
  %l6_tasks = alloca [2 x ptr]
  %l7__t4 = alloca [2 x i64]
  %l8_slots = alloca [2 x i64]
  %l9__t5 = alloca i64
  %l10_first = alloca i64
  %l11__t6 = alloca i64
  %l12__t7 = alloca ptr
  %l13__t8 = alloca i64
  %l14_final_value = alloca i64
  %l15__t9 = alloca i64
  br label %bb0
bb0:
  %t0 = call i64 @ql_1_choose()
  store i64 %t0, ptr %l1__t0
  %t1 = load i64, ptr %l1__t0
  store i64 %t1, ptr %l2_row
  %t2 = call ptr @ql_0_worker(i64 1)
  store ptr %t2, ptr %l3__t1
  %t3 = call ptr @ql_0_worker(i64 2)
  store ptr %t3, ptr %l4__t2
  %t4 = load ptr, ptr %l3__t1
  %t5 = load ptr, ptr %l4__t2
  %t6 = insertvalue [2 x ptr] undef, ptr %t4, 0
  %t7 = insertvalue [2 x ptr] %t6, ptr %t5, 1
  store [2 x ptr] %t7, ptr %l5__t3
  %t8 = load [2 x ptr], ptr %l5__t3
  store [2 x ptr] %t8, ptr %l6_tasks
  %t9 = load i64, ptr %l2_row
  %t10 = load i64, ptr %l2_row
  %t11 = insertvalue [2 x i64] undef, i64 %t9, 0
  %t12 = insertvalue [2 x i64] %t11, i64 %t10, 1
  store [2 x i64] %t12, ptr %l7__t4
  %t13 = load [2 x i64], ptr %l7__t4
  store [2 x i64] %t13, ptr %l8_slots
  %t14 = load i64, ptr %l2_row
  %t15 = getelementptr inbounds [2 x i64], ptr %l8_slots, i64 0, i64 %t14
  %t16 = load i64, ptr %t15
  %t17 = getelementptr inbounds [2 x ptr], ptr %l6_tasks, i64 0, i64 %t16
  %t18 = load ptr, ptr %t17
  %t19 = call ptr @qlrt_task_await(ptr %t18)
  %t20 = load i64, ptr %t19
  call void @qlrt_task_result_release(ptr %t19)
  store i64 %t20, ptr %l9__t5
  %t21 = load i64, ptr %l9__t5
  store i64 %t21, ptr %l10_first
  %t22 = load i64, ptr %l10_first
  %t23 = add i64 %t22, 1
  store i64 %t23, ptr %l11__t6
  %t24 = load i64, ptr %l11__t6
  %t25 = call ptr @ql_0_worker(i64 %t24)
  store ptr %t25, ptr %l12__t7
  %t26 = load ptr, ptr %l12__t7
  %t27 = load i64, ptr %l2_row
  %t28 = getelementptr inbounds [2 x i64], ptr %l8_slots, i64 0, i64 %t27
  %t29 = load i64, ptr %t28
  %t30 = getelementptr inbounds [2 x ptr], ptr %l6_tasks, i64 0, i64 %t29
  store ptr %t26, ptr %t30
  %t31 = load i64, ptr %l2_row
  %t32 = getelementptr inbounds [2 x i64], ptr %l8_slots, i64 0, i64 %t31
  %t33 = load i64, ptr %t32
  %t34 = getelementptr inbounds [2 x ptr], ptr %l6_tasks, i64 0, i64 %t33
  %t35 = load ptr, ptr %t34
  %t36 = call ptr @qlrt_task_await(ptr %t35)
  %t37 = load i64, ptr %t36
  call void @qlrt_task_result_release(ptr %t36)
  store i64 %t37, ptr %l13__t8
  %t38 = load i64, ptr %l13__t8
  store i64 %t38, ptr %l14_final_value
  %t39 = load i64, ptr %l14_final_value
  %t40 = call i64 @ql_2_score(i64 %t39)
  store i64 %t40, ptr %l15__t9
  %t41 = load i64, ptr %l15__t9
  store i64 %t41, ptr %l0__return
  br label %bb1
bb1:
  %t42 = load i64, ptr %l0__return
  ret i64 %t42
}

define ptr @ql_3_main__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_3_main__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_3_main() {
entry:
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_3_main__async_entry, ptr null)
  ret ptr %async_task
}

define i32 @main() {
entry:
  %async_main_task = call ptr @ql_3_main()
  %async_main_join = call ptr @qlrt_executor_spawn(ptr null, ptr %async_main_task)
  %async_main_res = call ptr @qlrt_task_await(ptr %async_main_join)
  %async_main_ret = load i64, ptr %async_main_res
  call void @qlrt_task_result_release(ptr %async_main_res)
  %async_main_exit = trunc i64 %async_main_ret to i32
  ret i32 %async_main_exit
}
