; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'async_program_main_spawn_bound_task_handle'
source_filename = "async_program_main_spawn_bound_task_handle.ql"
target triple = "{{TARGET_TRIPLE}}"

declare ptr @malloc(i64)
declare void @free(ptr)

define ptr @qlrt_async_frame_alloc(i64 %size, i64 %align) {
entry:
  %frame_is_zero = icmp eq i64 %size, 0
  %frame_alloc_size = select i1 %frame_is_zero, i64 1, i64 %size
  %frame = call ptr @malloc(i64 %frame_alloc_size)
  ret ptr %frame
}

define ptr @qlrt_async_task_create(ptr %entry_fn, ptr %frame) {
entry:
  %task_end = getelementptr { ptr, ptr, ptr }, ptr null, i32 1
  %task_size = ptrtoint ptr %task_end to i64
  %task = call ptr @malloc(i64 %task_size)
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  store ptr %entry_fn, ptr %task_entry_ptr
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  store ptr %frame, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr null, ptr %task_result_ptr
  ret ptr %task
}

define ptr @qlrt_executor_spawn(ptr %executor, ptr %task) {
entry:
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  %task_entry = load ptr, ptr %task_entry_ptr
  %task_started = icmp eq ptr %task_entry, null
  br i1 %task_started, label %done, label %start

start:
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  %task_frame = load ptr, ptr %task_frame_ptr
  %task_result = call ptr %task_entry(ptr %task_frame)
  call void @free(ptr %task_frame)
  store ptr null, ptr %task_entry_ptr
  store ptr null, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr %task_result, ptr %task_result_ptr
  br label %done

done:
  ret ptr %task
}

define ptr @qlrt_task_await(ptr %handle) {
entry:
  %started = call ptr @qlrt_executor_spawn(ptr null, ptr %handle)
  %result_ptr_slot = getelementptr inbounds { ptr, ptr, ptr }, ptr %started, i32 0, i32 2
  %result_ptr = load ptr, ptr %result_ptr_slot
  call void @free(ptr %started)
  ret ptr %result_ptr
}

define void @qlrt_task_result_release(ptr %result) {
entry:
  call void @free(ptr %result)
  ret void
}

define i64 @ql_0_worker__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %async_body_frame_field0 = getelementptr inbounds { i64 }, ptr %frame, i32 0, i32 0
  %async_body_frame_value0 = load i64, ptr %async_body_frame_field0
  store i64 %async_body_frame_value0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  store i64 %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load i64, ptr %l0__return
  ret i64 %t1
}

define ptr @ql_0_worker__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_0_worker__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_0_worker(i64 %arg0) {
entry:
  %async_frame = call ptr @qlrt_async_frame_alloc(i64 8, i64 8)
  %async_frame_field0 = getelementptr inbounds { i64 }, ptr %async_frame, i32 0, i32 0
  store i64 %arg0, ptr %async_frame_field0
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_0_worker__async_entry, ptr %async_frame)
  ret ptr %async_task
}

define i64 @ql_1_main__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca ptr
  %l2_first_task = alloca ptr
  %l3__t1 = alloca ptr
  %l4_second_task = alloca ptr
  %l5__t2 = alloca ptr
  %l6_first_running = alloca ptr
  %l7__t3 = alloca ptr
  %l8_second_running = alloca ptr
  %l9__t4 = alloca i64
  %l10_first = alloca i64
  %l11__t5 = alloca i64
  %l12_second = alloca i64
  %l13__t6 = alloca i64
  br label %bb0
bb0:
  %t0 = call ptr @ql_0_worker(i64 1)
  store ptr %t0, ptr %l1__t0
  %t1 = load ptr, ptr %l1__t0
  store ptr %t1, ptr %l2_first_task
  %t2 = call ptr @ql_0_worker(i64 2)
  store ptr %t2, ptr %l3__t1
  %t3 = load ptr, ptr %l3__t1
  store ptr %t3, ptr %l4_second_task
  %t4 = load ptr, ptr %l2_first_task
  %t5 = call ptr @qlrt_executor_spawn(ptr null, ptr %t4)
  store ptr %t5, ptr %l5__t2
  %t6 = load ptr, ptr %l5__t2
  store ptr %t6, ptr %l6_first_running
  %t7 = load ptr, ptr %l4_second_task
  %t8 = call ptr @qlrt_executor_spawn(ptr null, ptr %t7)
  store ptr %t8, ptr %l7__t3
  %t9 = load ptr, ptr %l7__t3
  store ptr %t9, ptr %l8_second_running
  %t10 = load ptr, ptr %l6_first_running
  %t11 = call ptr @qlrt_task_await(ptr %t10)
  %t12 = load i64, ptr %t11
  call void @qlrt_task_result_release(ptr %t11)
  store i64 %t12, ptr %l9__t4
  %t13 = load i64, ptr %l9__t4
  store i64 %t13, ptr %l10_first
  %t14 = load ptr, ptr %l8_second_running
  %t15 = call ptr @qlrt_task_await(ptr %t14)
  %t16 = load i64, ptr %t15
  call void @qlrt_task_result_release(ptr %t15)
  store i64 %t16, ptr %l11__t5
  %t17 = load i64, ptr %l11__t5
  store i64 %t17, ptr %l12_second
  %t18 = load i64, ptr %l10_first
  %t19 = load i64, ptr %l12_second
  %t20 = add i64 %t18, %t19
  store i64 %t20, ptr %l13__t6
  %t21 = load i64, ptr %l13__t6
  store i64 %t21, ptr %l0__return
  br label %bb1
bb1:
  %t22 = load i64, ptr %l0__return
  ret i64 %t22
}

define ptr @ql_1_main__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_1_main__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_1_main() {
entry:
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_1_main__async_entry, ptr null)
  ret ptr %async_task
}

define i32 @main() {
entry:
  %async_main_task = call ptr @ql_1_main()
  %async_main_join = call ptr @qlrt_executor_spawn(ptr null, ptr %async_main_task)
  %async_main_res = call ptr @qlrt_task_await(ptr %async_main_join)
  %async_main_ret = load i64, ptr %async_main_res
  call void @qlrt_task_result_release(ptr %async_main_res)
  %async_main_exit = trunc i64 %async_main_ret to i32
  ret i32 %async_main_exit
}
