; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'async_callable_const_static_build'
source_filename = "async_callable_const_static_build.ql"
target triple = "x86_64-pc-windows-msvc"

declare ptr @malloc(i64)
declare void @free(ptr)

define ptr @qlrt_async_frame_alloc(i64 %size, i64 %align) {
entry:
  %frame_is_zero = icmp eq i64 %size, 0
  %frame_alloc_size = select i1 %frame_is_zero, i64 1, i64 %size
  %frame = call ptr @malloc(i64 %frame_alloc_size)
  ret ptr %frame
}

define ptr @qlrt_async_task_create(ptr %entry_fn, ptr %frame) {
entry:
  %task_end = getelementptr { ptr, ptr, ptr }, ptr null, i32 1
  %task_size = ptrtoint ptr %task_end to i64
  %task = call ptr @malloc(i64 %task_size)
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  store ptr %entry_fn, ptr %task_entry_ptr
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  store ptr %frame, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr null, ptr %task_result_ptr
  ret ptr %task
}

define ptr @qlrt_executor_spawn(ptr %executor, ptr %task) {
entry:
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  %task_entry = load ptr, ptr %task_entry_ptr
  %task_started = icmp eq ptr %task_entry, null
  br i1 %task_started, label %done, label %start

start:
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  %task_frame = load ptr, ptr %task_frame_ptr
  %task_result = call ptr %task_entry(ptr %task_frame)
  call void @free(ptr %task_frame)
  store ptr null, ptr %task_entry_ptr
  store ptr null, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr %task_result, ptr %task_result_ptr
  br label %done

done:
  ret ptr %task
}

define ptr @qlrt_task_await(ptr %handle) {
entry:
  %started = call ptr @qlrt_executor_spawn(ptr null, ptr %handle)
  %result_ptr_slot = getelementptr inbounds { ptr, ptr, ptr }, ptr %started, i32 0, i32 2
  %result_ptr = load ptr, ptr %result_ptr_slot
  call void @free(ptr %started)
  ret ptr %result_ptr
}

define void @qlrt_task_result_release(ptr %result) {
entry:
  call void @free(ptr %result)
  ret void
}

define i64 @ql_0_worker__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %l2__t0 = alloca i64
  %async_body_frame_field0 = getelementptr inbounds { i64 }, ptr %frame, i32 0, i32 0
  %async_body_frame_value0 = load i64, ptr %async_body_frame_field0
  store i64 %async_body_frame_value0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  %t1 = add i64 %t0, 1
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l2__t0
  store i64 %t2, ptr %l0__return
  br label %bb1
bb1:
  %t3 = load i64, ptr %l0__return
  ret i64 %t3
}

define ptr @ql_0_worker__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_0_worker__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_0_worker(i64 %arg0) {
entry:
  %async_frame = call ptr @qlrt_async_frame_alloc(i64 8, i64 8)
  %async_frame_field0 = getelementptr inbounds { i64 }, ptr %async_frame, i32 0, i32 0
  store i64 %arg0, ptr %async_frame_field0
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_0_worker__async_entry, ptr %async_frame)
  ret ptr %async_task
}

define i64 @ql_3_main__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_f = alloca ptr
  %l2_g = alloca ptr
  %l3__t0 = alloca ptr
  %l4__t1 = alloca i64
  %l5_first = alloca i64
  %l6__t2 = alloca ptr
  %l7__t3 = alloca i64
  %l8_second = alloca i64
  %l9__t4 = alloca ptr
  %l10__t5 = alloca i64
  %l11_third = alloca i64
  %l12__t6 = alloca ptr
  %l13__t7 = alloca i64
  %l14_fourth = alloca i64
  %l15__t8 = alloca i64
  %l16__t9 = alloca i64
  %l17__t10 = alloca i64
  br label %bb0
bb0:
  store ptr @ql_0_worker, ptr %l1_f
  store ptr @ql_0_worker, ptr %l2_g
  %t0 = call ptr @ql_0_worker(i64 10)
  store ptr %t0, ptr %l3__t0
  %t1 = load ptr, ptr %l3__t0
  %t2 = call ptr @qlrt_task_await(ptr %t1)
  %t3 = load i64, ptr %t2
  call void @qlrt_task_result_release(ptr %t2)
  store i64 %t3, ptr %l4__t1
  %t4 = load i64, ptr %l4__t1
  store i64 %t4, ptr %l5_first
  %t5 = call ptr @ql_0_worker(i64 20)
  store ptr %t5, ptr %l6__t2
  %t6 = load ptr, ptr %l6__t2
  %t7 = call ptr @qlrt_task_await(ptr %t6)
  %t8 = load i64, ptr %t7
  call void @qlrt_task_result_release(ptr %t7)
  store i64 %t8, ptr %l7__t3
  %t9 = load i64, ptr %l7__t3
  store i64 %t9, ptr %l8_second
  %t10 = load ptr, ptr %l1_f
  %t11 = call ptr %t10(i64 30)
  store ptr %t11, ptr %l9__t4
  %t12 = load ptr, ptr %l9__t4
  %t13 = call ptr @qlrt_task_await(ptr %t12)
  %t14 = load i64, ptr %t13
  call void @qlrt_task_result_release(ptr %t13)
  store i64 %t14, ptr %l10__t5
  %t15 = load i64, ptr %l10__t5
  store i64 %t15, ptr %l11_third
  %t16 = load ptr, ptr %l2_g
  %t17 = call ptr %t16(i64 40)
  store ptr %t17, ptr %l12__t6
  %t18 = load ptr, ptr %l12__t6
  %t19 = call ptr @qlrt_task_await(ptr %t18)
  %t20 = load i64, ptr %t19
  call void @qlrt_task_result_release(ptr %t19)
  store i64 %t20, ptr %l13__t7
  %t21 = load i64, ptr %l13__t7
  store i64 %t21, ptr %l14_fourth
  %t22 = load i64, ptr %l5_first
  %t23 = load i64, ptr %l8_second
  %t24 = add i64 %t22, %t23
  store i64 %t24, ptr %l15__t8
  %t25 = load i64, ptr %l15__t8
  %t26 = load i64, ptr %l11_third
  %t27 = add i64 %t25, %t26
  store i64 %t27, ptr %l16__t9
  %t28 = load i64, ptr %l16__t9
  %t29 = load i64, ptr %l14_fourth
  %t30 = add i64 %t28, %t29
  store i64 %t30, ptr %l17__t10
  %t31 = load i64, ptr %l17__t10
  store i64 %t31, ptr %l0__return
  br label %bb1
bb1:
  %t32 = load i64, ptr %l0__return
  ret i64 %t32
}

define ptr @ql_3_main__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_3_main__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_3_main() {
entry:
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_3_main__async_entry, ptr null)
  ret ptr %async_task
}

define i32 @main() {
entry:
  %async_main_task = call ptr @ql_3_main()
  %async_main_join = call ptr @qlrt_executor_spawn(ptr null, ptr %async_main_task)
  %async_main_res = call ptr @qlrt_task_await(ptr %async_main_join)
  %async_main_ret = load i64, ptr %async_main_res
  call void @qlrt_task_result_release(ptr %async_main_res)
  %async_main_exit = trunc i64 %async_main_ret to i32
  ret i32 %async_main_exit
}
