; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'async_program_main_aliased_projected_root_dynamic_task_handle_reinit'
source_filename = "async_program_main_aliased_projected_root_dynamic_task_handle_reinit.ql"
target triple = "x86_64-pc-windows-msvc"

declare ptr @malloc(i64)
declare void @free(ptr)

define ptr @qlrt_async_frame_alloc(i64 %size, i64 %align) {
entry:
  %frame_is_zero = icmp eq i64 %size, 0
  %frame_alloc_size = select i1 %frame_is_zero, i64 1, i64 %size
  %frame = call ptr @malloc(i64 %frame_alloc_size)
  ret ptr %frame
}

define ptr @qlrt_async_task_create(ptr %entry_fn, ptr %frame) {
entry:
  %task_end = getelementptr { ptr, ptr, ptr }, ptr null, i32 1
  %task_size = ptrtoint ptr %task_end to i64
  %task = call ptr @malloc(i64 %task_size)
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  store ptr %entry_fn, ptr %task_entry_ptr
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  store ptr %frame, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr null, ptr %task_result_ptr
  ret ptr %task
}

define ptr @qlrt_executor_spawn(ptr %executor, ptr %task) {
entry:
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  %task_entry = load ptr, ptr %task_entry_ptr
  %task_started = icmp eq ptr %task_entry, null
  br i1 %task_started, label %done, label %start

start:
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  %task_frame = load ptr, ptr %task_frame_ptr
  %task_result = call ptr %task_entry(ptr %task_frame)
  call void @free(ptr %task_frame)
  store ptr null, ptr %task_entry_ptr
  store ptr null, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr %task_result, ptr %task_result_ptr
  br label %done

done:
  ret ptr %task
}

define ptr @qlrt_task_await(ptr %handle) {
entry:
  %started = call ptr @qlrt_executor_spawn(ptr null, ptr %handle)
  %result_ptr_slot = getelementptr inbounds { ptr, ptr, ptr }, ptr %started, i32 0, i32 2
  %result_ptr = load ptr, ptr %result_ptr_slot
  call void @free(ptr %started)
  ret ptr %result_ptr
}

define void @qlrt_task_result_release(ptr %result) {
entry:
  call void @free(ptr %result)
  ret void
}

define i64 @ql_2_worker__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %async_body_frame_field0 = getelementptr inbounds { i64 }, ptr %frame, i32 0, i32 0
  %async_body_frame_value0 = load i64, ptr %async_body_frame_field0
  store i64 %async_body_frame_value0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  store i64 %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load i64, ptr %l0__return
  ret i64 %t1
}

define ptr @ql_2_worker__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_2_worker__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_2_worker(i64 %arg0) {
entry:
  %async_frame = call ptr @qlrt_async_frame_alloc(i64 8, i64 8)
  %async_frame_field0 = getelementptr inbounds { i64 }, ptr %async_frame, i32 0, i32 0
  store i64 %arg0, ptr %async_frame_field0
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_2_worker__async_entry, ptr %async_frame)
  ret ptr %async_task
}

define i64 @ql_3_main__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca ptr
  %l2__t1 = alloca ptr
  %l3__t2 = alloca [2 x ptr]
  %l4__t3 = alloca { [2 x ptr] }
  %l5_pending = alloca { [2 x ptr] }
  %l6__t4 = alloca { i64 }
  %l7_slot = alloca { i64 }
  %l8_alias = alloca [2 x ptr]
  %l9__t5 = alloca i64
  %l10_first = alloca i64
  %l11__t6 = alloca i64
  %l12__t7 = alloca ptr
  %l13__t8 = alloca i64
  %l14_second = alloca i64
  %l15__t9 = alloca i64
  %l16_tail = alloca i64
  %l17__t10 = alloca i64
  br label %bb0
bb0:
  %t0 = call ptr @ql_2_worker(i64 5)
  store ptr %t0, ptr %l1__t0
  %t1 = call ptr @ql_2_worker(i64 8)
  store ptr %t1, ptr %l2__t1
  %t2 = load ptr, ptr %l1__t0
  %t3 = load ptr, ptr %l2__t1
  %t4 = insertvalue [2 x ptr] undef, ptr %t2, 0
  %t5 = insertvalue [2 x ptr] %t4, ptr %t3, 1
  store [2 x ptr] %t5, ptr %l3__t2
  %t6 = load [2 x ptr], ptr %l3__t2
  %t7 = insertvalue { [2 x ptr] } undef, [2 x ptr] %t6, 0
  store { [2 x ptr] } %t7, ptr %l4__t3
  %t8 = load { [2 x ptr] }, ptr %l4__t3
  store { [2 x ptr] } %t8, ptr %l5_pending
  %t9 = insertvalue { i64 } undef, i64 0, 0
  store { i64 } %t9, ptr %l6__t4
  %t10 = load { i64 }, ptr %l6__t4
  store { i64 } %t10, ptr %l7_slot
  %t11 = getelementptr inbounds { [2 x ptr] }, ptr %l5_pending, i32 0, i32 0
  %t12 = load [2 x ptr], ptr %t11
  store [2 x ptr] %t12, ptr %l8_alias
  %t13 = getelementptr inbounds { [2 x ptr] }, ptr %l5_pending, i32 0, i32 0
  %t14 = getelementptr inbounds { i64 }, ptr %l7_slot, i32 0, i32 0
  %t15 = load i64, ptr %t14
  %t16 = getelementptr inbounds [2 x ptr], ptr %t13, i64 0, i64 %t15
  %t17 = load ptr, ptr %t16
  %t18 = call ptr @qlrt_task_await(ptr %t17)
  %t19 = load i64, ptr %t18
  call void @qlrt_task_result_release(ptr %t18)
  store i64 %t19, ptr %l9__t5
  %t20 = load i64, ptr %l9__t5
  store i64 %t20, ptr %l10_first
  %t21 = load i64, ptr %l10_first
  %t22 = add i64 %t21, 4
  store i64 %t22, ptr %l11__t6
  %t23 = load i64, ptr %l11__t6
  %t24 = call ptr @ql_2_worker(i64 %t23)
  store ptr %t24, ptr %l12__t7
  %t25 = load ptr, ptr %l12__t7
  %t26 = getelementptr inbounds { [2 x ptr] }, ptr %l5_pending, i32 0, i32 0
  %t27 = getelementptr inbounds { i64 }, ptr %l7_slot, i32 0, i32 0
  %t28 = load i64, ptr %t27
  %t29 = getelementptr inbounds [2 x ptr], ptr %t26, i64 0, i64 %t28
  store ptr %t25, ptr %t29
  %t30 = getelementptr inbounds { [2 x ptr] }, ptr %l5_pending, i32 0, i32 0
  %t31 = getelementptr inbounds { i64 }, ptr %l7_slot, i32 0, i32 0
  %t32 = load i64, ptr %t31
  %t33 = getelementptr inbounds [2 x ptr], ptr %t30, i64 0, i64 %t32
  %t34 = load ptr, ptr %t33
  %t35 = call ptr @qlrt_task_await(ptr %t34)
  %t36 = load i64, ptr %t35
  call void @qlrt_task_result_release(ptr %t35)
  store i64 %t36, ptr %l13__t8
  %t37 = load i64, ptr %l13__t8
  store i64 %t37, ptr %l14_second
  %t38 = getelementptr inbounds { [2 x ptr] }, ptr %l5_pending, i32 0, i32 0
  %t39 = getelementptr inbounds [2 x ptr], ptr %t38, i64 0, i64 1
  %t40 = load ptr, ptr %t39
  %t41 = call ptr @qlrt_task_await(ptr %t40)
  %t42 = load i64, ptr %t41
  call void @qlrt_task_result_release(ptr %t41)
  store i64 %t42, ptr %l15__t9
  %t43 = load i64, ptr %l15__t9
  store i64 %t43, ptr %l16_tail
  %t44 = load i64, ptr %l14_second
  %t45 = load i64, ptr %l16_tail
  %t46 = add i64 %t44, %t45
  store i64 %t46, ptr %l17__t10
  %t47 = load i64, ptr %l17__t10
  store i64 %t47, ptr %l0__return
  br label %bb1
bb1:
  %t48 = load i64, ptr %l0__return
  ret i64 %t48
}

define ptr @ql_3_main__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_3_main__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_3_main() {
entry:
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_3_main__async_entry, ptr null)
  ret ptr %async_task
}

define i32 @main() {
entry:
  %async_main_task = call ptr @ql_3_main()
  %async_main_join = call ptr @qlrt_executor_spawn(ptr null, ptr %async_main_task)
  %async_main_res = call ptr @qlrt_task_await(ptr %async_main_join)
  %async_main_ret = load i64, ptr %async_main_res
  call void @qlrt_task_result_release(ptr %async_main_res)
  %async_main_exit = trunc i64 %async_main_ret to i32
  ret i32 %async_main_exit
}
