; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'async_program_main_guarded_const_backed_double_root_double_source_alias_sourced_composed_dynamic_task_handle_forwarded_nested_array_repackage_spawn'
source_filename = "async_program_main_guarded_const_backed_double_root_double_source_alias_sourced_composed_dynamic_task_handle_forwarded_nested_array_repackage_spawn.ql"
target triple = "x86_64-pc-windows-msvc"

declare ptr @malloc(i64)
declare void @free(ptr)

define ptr @qlrt_async_frame_alloc(i64 %size, i64 %align) {
entry:
  %frame_is_zero = icmp eq i64 %size, 0
  %frame_alloc_size = select i1 %frame_is_zero, i64 1, i64 %size
  %frame = call ptr @malloc(i64 %frame_alloc_size)
  ret ptr %frame
}

define ptr @qlrt_async_task_create(ptr %entry_fn, ptr %frame) {
entry:
  %task_end = getelementptr { ptr, ptr, ptr }, ptr null, i32 1
  %task_size = ptrtoint ptr %task_end to i64
  %task = call ptr @malloc(i64 %task_size)
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  store ptr %entry_fn, ptr %task_entry_ptr
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  store ptr %frame, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr null, ptr %task_result_ptr
  ret ptr %task
}

define ptr @qlrt_executor_spawn(ptr %executor, ptr %task) {
entry:
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  %task_entry = load ptr, ptr %task_entry_ptr
  %task_started = icmp eq ptr %task_entry, null
  br i1 %task_started, label %done, label %start

start:
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  %task_frame = load ptr, ptr %task_frame_ptr
  %task_result = call ptr %task_entry(ptr %task_frame)
  call void @free(ptr %task_frame)
  store ptr null, ptr %task_entry_ptr
  store ptr null, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr %task_result, ptr %task_result_ptr
  br label %done

done:
  ret ptr %task
}

define ptr @qlrt_task_await(ptr %handle) {
entry:
  %started = call ptr @qlrt_executor_spawn(ptr null, ptr %handle)
  %result_ptr_slot = getelementptr inbounds { ptr, ptr, ptr }, ptr %started, i32 0, i32 2
  %result_ptr = load ptr, ptr %result_ptr_slot
  call void @free(ptr %started)
  ret ptr %result_ptr
}

define void @qlrt_task_result_release(ptr %result) {
entry:
  call void @free(ptr %result)
  ret void
}

define i64 @ql_5_worker__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %async_body_frame_field0 = getelementptr inbounds { i64 }, ptr %frame, i32 0, i32 0
  %async_body_frame_value0 = load i64, ptr %async_body_frame_field0
  store i64 %async_body_frame_value0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  store i64 %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load i64, ptr %l0__return
  ret i64 %t1
}

define ptr @ql_5_worker__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_5_worker__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_5_worker(i64 %arg0) {
entry:
  %async_frame = call ptr @qlrt_async_frame_alloc(i64 8, i64 8)
  %async_frame_field0 = getelementptr inbounds { i64 }, ptr %async_frame, i32 0, i32 0
  store i64 %arg0, ptr %async_frame_field0
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_5_worker__async_entry, ptr %async_frame)
  ret ptr %async_task
}

define ptr @ql_6_forward(ptr %arg0) {
entry:
  %l0__return = alloca ptr
  %l1_task = alloca ptr
  store ptr %arg0, ptr %l1_task
  br label %bb0
bb0:
  %t0 = load ptr, ptr %l1_task
  store ptr %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load ptr, ptr %l0__return
  ret ptr %t1
}

define i64 @ql_7_main__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_row = alloca i64
  %l2__t0 = alloca [2 x i64]
  %l3_slots = alloca [2 x i64]
  %l4_slot_root = alloca [2 x i64]
  %l5_alias_slots = alloca [2 x i64]
  %l6__t1 = alloca ptr
  %l7__t2 = alloca ptr
  %l8__t3 = alloca [2 x ptr]
  %l9__t4 = alloca { [2 x ptr] }
  %l10_pending = alloca { [2 x ptr] }
  %l11_root = alloca [2 x ptr]
  %l12_alias = alloca [2 x ptr]
  %l13__t5 = alloca { i64 }
  %l14_slot = alloca { i64 }
  %l16__t7 = alloca i1
  %l17__t8 = alloca i64
  %l18_first = alloca i64
  %l19__t9 = alloca i64
  %l20__t10 = alloca ptr
  %l21__t11 = alloca ptr
  %l22__t12 = alloca ptr
  %l23__t13 = alloca ptr
  %l24__t14 = alloca [2 x ptr]
  %l25__t15 = alloca { [2 x ptr] }
  %l26__t16 = alloca { { [2 x ptr] }, ptr }
  %l27_env = alloca { { [2 x ptr] }, ptr }
  %l28__t17 = alloca ptr
  %l29_running = alloca ptr
  %l30__t18 = alloca i64
  %l31_second = alloca i64
  %l32__t19 = alloca i64
  %l33_extra = alloca i64
  %l34__t20 = alloca i64
  %l35_tail = alloca i64
  %l36__t21 = alloca i64
  %l37__t22 = alloca i64
  br label %bb0
bb0:
  store i64 0, ptr %l1_row
  %t0 = load i64, ptr %l1_row
  %t1 = load i64, ptr %l1_row
  %t2 = insertvalue [2 x i64] undef, i64 %t0, 0
  %t3 = insertvalue [2 x i64] %t2, i64 %t1, 1
  store [2 x i64] %t3, ptr %l2__t0
  %t4 = load [2 x i64], ptr %l2__t0
  store [2 x i64] %t4, ptr %l3_slots
  %t5 = load [2 x i64], ptr %l3_slots
  store [2 x i64] %t5, ptr %l4_slot_root
  %t6 = load [2 x i64], ptr %l4_slot_root
  store [2 x i64] %t6, ptr %l5_alias_slots
  %t7 = call ptr @ql_5_worker(i64 8)
  store ptr %t7, ptr %l6__t1
  %t8 = call ptr @ql_5_worker(i64 14)
  store ptr %t8, ptr %l7__t2
  %t9 = load ptr, ptr %l6__t1
  %t10 = load ptr, ptr %l7__t2
  %t11 = insertvalue [2 x ptr] undef, ptr %t9, 0
  %t12 = insertvalue [2 x ptr] %t11, ptr %t10, 1
  store [2 x ptr] %t12, ptr %l8__t3
  %t13 = load [2 x ptr], ptr %l8__t3
  %t14 = insertvalue { [2 x ptr] } undef, [2 x ptr] %t13, 0
  store { [2 x ptr] } %t14, ptr %l9__t4
  %t15 = load { [2 x ptr] }, ptr %l9__t4
  store { [2 x ptr] } %t15, ptr %l10_pending
  %t16 = getelementptr inbounds { [2 x ptr] }, ptr %l10_pending, i32 0, i32 0
  %t17 = load [2 x ptr], ptr %t16
  store [2 x ptr] %t17, ptr %l11_root
  %t18 = getelementptr inbounds { [2 x ptr] }, ptr %l10_pending, i32 0, i32 0
  %t19 = load [2 x ptr], ptr %t18
  store [2 x ptr] %t19, ptr %l12_alias
  %t20 = insertvalue { i64 } undef, i64 0, 0
  store { i64 } %t20, ptr %l13__t5
  %t21 = load { i64 }, ptr %l13__t5
  store { i64 } %t21, ptr %l14_slot
  %t22 = getelementptr inbounds { i64 }, ptr %l14_slot, i32 0, i32 0
  %t23 = load i64, ptr %t22
  %t24 = icmp eq i64 %t23, 0
  store i1 %t24, ptr %l16__t7
  %t25 = load i1, ptr %l16__t7
  br i1 %t25, label %bb3, label %bb2
bb1:
  %t26 = load i64, ptr %l0__return
  ret i64 %t26
bb2:
  %t27 = getelementptr inbounds { [2 x ptr] }, ptr %l10_pending, i32 0, i32 0
  %t28 = load i64, ptr %l1_row
  %t29 = getelementptr inbounds [2 x i64], ptr %l5_alias_slots, i64 0, i64 %t28
  %t30 = load i64, ptr %t29
  %t31 = getelementptr inbounds [2 x ptr], ptr %t27, i64 0, i64 %t30
  %t32 = load ptr, ptr %t31
  %t33 = call ptr @ql_6_forward(ptr %t32)
  store ptr %t33, ptr %l22__t12
  %t34 = call ptr @ql_5_worker(i64 30)
  store ptr %t34, ptr %l23__t13
  %t35 = load ptr, ptr %l22__t12
  %t36 = load ptr, ptr %l23__t13
  %t37 = insertvalue [2 x ptr] undef, ptr %t35, 0
  %t38 = insertvalue [2 x ptr] %t37, ptr %t36, 1
  store [2 x ptr] %t38, ptr %l24__t14
  %t39 = load [2 x ptr], ptr %l24__t14
  %t40 = insertvalue { [2 x ptr] } undef, [2 x ptr] %t39, 0
  store { [2 x ptr] } %t40, ptr %l25__t15
  %t41 = load { [2 x ptr] }, ptr %l25__t15
  %t42 = getelementptr inbounds { [2 x ptr] }, ptr %l10_pending, i32 0, i32 0
  %t43 = getelementptr inbounds [2 x ptr], ptr %t42, i64 0, i64 1
  %t44 = load ptr, ptr %t43
  %t45 = insertvalue { { [2 x ptr] }, ptr } undef, { [2 x ptr] } %t41, 0
  %t46 = insertvalue { { [2 x ptr] }, ptr } %t45, ptr %t44, 1
  store { { [2 x ptr] }, ptr } %t46, ptr %l26__t16
  %t47 = load { { [2 x ptr] }, ptr }, ptr %l26__t16
  store { { [2 x ptr] }, ptr } %t47, ptr %l27_env
  %t48 = getelementptr inbounds { { [2 x ptr] }, ptr }, ptr %l26__t16, i32 0, i32 0
  %t49 = getelementptr inbounds { [2 x ptr] }, ptr %t48, i32 0, i32 0
  %t50 = getelementptr inbounds [2 x ptr], ptr %t49, i64 0, i64 0
  %t51 = load ptr, ptr %t50
  %t52 = call ptr @qlrt_executor_spawn(ptr null, ptr %t51)
  store ptr %t52, ptr %l28__t17
  %t53 = load ptr, ptr %l28__t17
  store ptr %t53, ptr %l29_running
  %t54 = load ptr, ptr %l28__t17
  %t55 = call ptr @qlrt_task_await(ptr %t54)
  %t56 = load i64, ptr %t55
  call void @qlrt_task_result_release(ptr %t55)
  store i64 %t56, ptr %l30__t18
  %t57 = load i64, ptr %l30__t18
  store i64 %t57, ptr %l31_second
  %t58 = getelementptr inbounds { { [2 x ptr] }, ptr }, ptr %l26__t16, i32 0, i32 0
  %t59 = getelementptr inbounds { [2 x ptr] }, ptr %t58, i32 0, i32 0
  %t60 = getelementptr inbounds [2 x ptr], ptr %t59, i64 0, i64 1
  %t61 = load ptr, ptr %t60
  %t62 = call ptr @qlrt_task_await(ptr %t61)
  %t63 = load i64, ptr %t62
  call void @qlrt_task_result_release(ptr %t62)
  store i64 %t63, ptr %l32__t19
  %t64 = load i64, ptr %l32__t19
  store i64 %t64, ptr %l33_extra
  %t65 = getelementptr inbounds { { [2 x ptr] }, ptr }, ptr %l26__t16, i32 0, i32 1
  %t66 = load ptr, ptr %t65
  %t67 = call ptr @qlrt_task_await(ptr %t66)
  %t68 = load i64, ptr %t67
  call void @qlrt_task_result_release(ptr %t67)
  store i64 %t68, ptr %l34__t20
  %t69 = load i64, ptr %l34__t20
  store i64 %t69, ptr %l35_tail
  %t70 = load i64, ptr %l31_second
  %t71 = load i64, ptr %l33_extra
  %t72 = add i64 %t70, %t71
  store i64 %t72, ptr %l36__t21
  %t73 = load i64, ptr %l36__t21
  %t74 = load i64, ptr %l35_tail
  %t75 = add i64 %t73, %t74
  store i64 %t75, ptr %l37__t22
  %t76 = load i64, ptr %l37__t22
  store i64 %t76, ptr %l0__return
  br label %bb1
bb3:
  %t77 = getelementptr inbounds { [2 x ptr] }, ptr %l10_pending, i32 0, i32 0
  %t78 = load i64, ptr %l1_row
  %t79 = getelementptr inbounds [2 x i64], ptr %l5_alias_slots, i64 0, i64 %t78
  %t80 = load i64, ptr %t79
  %t81 = getelementptr inbounds [2 x ptr], ptr %t77, i64 0, i64 %t80
  %t82 = load ptr, ptr %t81
  %t83 = call ptr @qlrt_task_await(ptr %t82)
  %t84 = load i64, ptr %t83
  call void @qlrt_task_result_release(ptr %t83)
  store i64 %t84, ptr %l17__t8
  %t85 = load i64, ptr %l17__t8
  store i64 %t85, ptr %l18_first
  %t86 = load i64, ptr %l18_first
  %t87 = add i64 %t86, 14
  store i64 %t87, ptr %l19__t9
  %t88 = load i64, ptr %l19__t9
  %t89 = call ptr @ql_5_worker(i64 %t88)
  store ptr %t89, ptr %l20__t10
  %t90 = load ptr, ptr %l20__t10
  %t91 = getelementptr inbounds { [2 x ptr] }, ptr %l10_pending, i32 0, i32 0
  %t92 = load i64, ptr %l1_row
  %t93 = getelementptr inbounds [2 x i64], ptr %l3_slots, i64 0, i64 %t92
  %t94 = load i64, ptr %t93
  %t95 = getelementptr inbounds [2 x ptr], ptr %t91, i64 0, i64 %t94
  store ptr %t90, ptr %t95
  %t96 = load ptr, ptr %l20__t10
  store ptr %t96, ptr %l21__t11
  %t97 = load ptr, ptr %l21__t11
  br label %bb2
}

define ptr @ql_7_main__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_7_main__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_7_main() {
entry:
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_7_main__async_entry, ptr null)
  ret ptr %async_task
}

define i32 @main() {
entry:
  %async_main_task = call ptr @ql_7_main()
  %async_main_join = call ptr @qlrt_executor_spawn(ptr null, ptr %async_main_task)
  %async_main_res = call ptr @qlrt_task_await(ptr %async_main_join)
  %async_main_ret = load i64, ptr %async_main_res
  call void @qlrt_task_result_release(ptr %async_main_res)
  %async_main_exit = trunc i64 %async_main_ret to i32
  ret i32 %async_main_exit
}
