; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'async_function_value_build'
source_filename = "async_function_value_build.ql"
target triple = "x86_64-pc-windows-msvc"

declare ptr @malloc(i64)
declare void @free(ptr)

define ptr @qlrt_async_frame_alloc(i64 %size, i64 %align) {
entry:
  %frame_is_zero = icmp eq i64 %size, 0
  %frame_alloc_size = select i1 %frame_is_zero, i64 1, i64 %size
  %frame = call ptr @malloc(i64 %frame_alloc_size)
  ret ptr %frame
}

define ptr @qlrt_async_task_create(ptr %entry_fn, ptr %frame) {
entry:
  %task_end = getelementptr { ptr, ptr, ptr }, ptr null, i32 1
  %task_size = ptrtoint ptr %task_end to i64
  %task = call ptr @malloc(i64 %task_size)
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  store ptr %entry_fn, ptr %task_entry_ptr
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  store ptr %frame, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr null, ptr %task_result_ptr
  ret ptr %task
}

define ptr @qlrt_executor_spawn(ptr %executor, ptr %task) {
entry:
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  %task_entry = load ptr, ptr %task_entry_ptr
  %task_started = icmp eq ptr %task_entry, null
  br i1 %task_started, label %done, label %start

start:
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  %task_frame = load ptr, ptr %task_frame_ptr
  %task_result = call ptr %task_entry(ptr %task_frame)
  call void @free(ptr %task_frame)
  store ptr null, ptr %task_entry_ptr
  store ptr null, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr %task_result, ptr %task_result_ptr
  br label %done

done:
  ret ptr %task
}

define ptr @qlrt_task_await(ptr %handle) {
entry:
  %started = call ptr @qlrt_executor_spawn(ptr null, ptr %handle)
  %result_ptr_slot = getelementptr inbounds { ptr, ptr, ptr }, ptr %started, i32 0, i32 2
  %result_ptr = load ptr, ptr %result_ptr_slot
  call void @free(ptr %started)
  ret ptr %result_ptr
}

define void @qlrt_task_result_release(ptr %result) {
entry:
  call void @free(ptr %result)
  ret void
}

define i64 @ql_0_worker__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %l2__t0 = alloca i64
  %async_body_frame_field0 = getelementptr inbounds { i64 }, ptr %frame, i32 0, i32 0
  %async_body_frame_value0 = load i64, ptr %async_body_frame_field0
  store i64 %async_body_frame_value0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  %t1 = add i64 %t0, 1
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l2__t0
  store i64 %t2, ptr %l0__return
  br label %bb1
bb1:
  %t3 = load i64, ptr %l0__return
  ret i64 %t3
}

define ptr @ql_0_worker__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_0_worker__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_0_worker(i64 %arg0) {
entry:
  %async_frame = call ptr @qlrt_async_frame_alloc(i64 8, i64 8)
  %async_frame_field0 = getelementptr inbounds { i64 }, ptr %async_frame, i32 0, i32 0
  store i64 %arg0, ptr %async_frame_field0
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_0_worker__async_entry, ptr %async_frame)
  ret ptr %async_task
}

define i64 @ql_1_main__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_direct = alloca ptr
  %l2_aliased = alloca ptr
  %l3__t0 = alloca ptr
  %l4__t1 = alloca i64
  %l5_first = alloca i64
  %l6__t2 = alloca ptr
  %l7__t3 = alloca i64
  %l8_second = alloca i64
  %l9__t4 = alloca i64
  br label %bb0
bb0:
  store ptr @ql_0_worker, ptr %l1_direct
  store ptr @ql_0_worker, ptr %l2_aliased
  %t0 = load ptr, ptr %l1_direct
  %t1 = call ptr %t0(i64 10)
  store ptr %t1, ptr %l3__t0
  %t2 = load ptr, ptr %l3__t0
  %t3 = call ptr @qlrt_task_await(ptr %t2)
  %t4 = load i64, ptr %t3
  call void @qlrt_task_result_release(ptr %t3)
  store i64 %t4, ptr %l4__t1
  %t5 = load i64, ptr %l4__t1
  store i64 %t5, ptr %l5_first
  %t6 = load ptr, ptr %l2_aliased
  %t7 = call ptr %t6(i64 20)
  store ptr %t7, ptr %l6__t2
  %t8 = load ptr, ptr %l6__t2
  %t9 = call ptr @qlrt_task_await(ptr %t8)
  %t10 = load i64, ptr %t9
  call void @qlrt_task_result_release(ptr %t9)
  store i64 %t10, ptr %l7__t3
  %t11 = load i64, ptr %l7__t3
  store i64 %t11, ptr %l8_second
  %t12 = load i64, ptr %l5_first
  %t13 = load i64, ptr %l8_second
  %t14 = add i64 %t12, %t13
  store i64 %t14, ptr %l9__t4
  %t15 = load i64, ptr %l9__t4
  store i64 %t15, ptr %l0__return
  br label %bb1
bb1:
  %t16 = load i64, ptr %l0__return
  ret i64 %t16
}

define ptr @ql_1_main__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_1_main__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_1_main() {
entry:
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_1_main__async_entry, ptr null)
  ret ptr %async_task
}

define i32 @main() {
entry:
  %async_main_task = call ptr @ql_1_main()
  %async_main_join = call ptr @qlrt_executor_spawn(ptr null, ptr %async_main_task)
  %async_main_res = call ptr @qlrt_task_await(ptr %async_main_join)
  %async_main_ret = load i64, ptr %async_main_res
  call void @qlrt_task_result_release(ptr %async_main_res)
  %async_main_exit = trunc i64 %async_main_ret to i32
  ret i32 %async_main_exit
}
