; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'async_program_main_aliased_projected_root_task_handle_nested_repackage_spawn'
source_filename = "async_program_main_aliased_projected_root_task_handle_nested_repackage_spawn.ql"
target triple = "{{TARGET_TRIPLE}}"

declare ptr @malloc(i64)
declare void @free(ptr)

define ptr @qlrt_async_frame_alloc(i64 %size, i64 %align) {
entry:
  %frame_is_zero = icmp eq i64 %size, 0
  %frame_alloc_size = select i1 %frame_is_zero, i64 1, i64 %size
  %frame = call ptr @malloc(i64 %frame_alloc_size)
  ret ptr %frame
}

define ptr @qlrt_async_task_create(ptr %entry_fn, ptr %frame) {
entry:
  %task_end = getelementptr { ptr, ptr, ptr }, ptr null, i32 1
  %task_size = ptrtoint ptr %task_end to i64
  %task = call ptr @malloc(i64 %task_size)
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  store ptr %entry_fn, ptr %task_entry_ptr
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  store ptr %frame, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr null, ptr %task_result_ptr
  ret ptr %task
}

define ptr @qlrt_executor_spawn(ptr %executor, ptr %task) {
entry:
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  %task_entry = load ptr, ptr %task_entry_ptr
  %task_started = icmp eq ptr %task_entry, null
  br i1 %task_started, label %done, label %start

start:
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  %task_frame = load ptr, ptr %task_frame_ptr
  %task_result = call ptr %task_entry(ptr %task_frame)
  call void @free(ptr %task_frame)
  store ptr null, ptr %task_entry_ptr
  store ptr null, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr %task_result, ptr %task_result_ptr
  br label %done

done:
  ret ptr %task
}

define ptr @qlrt_task_await(ptr %handle) {
entry:
  %started = call ptr @qlrt_executor_spawn(ptr null, ptr %handle)
  %result_ptr_slot = getelementptr inbounds { ptr, ptr, ptr }, ptr %started, i32 0, i32 2
  %result_ptr = load ptr, ptr %result_ptr_slot
  call void @free(ptr %started)
  ret ptr %result_ptr
}

define void @qlrt_task_result_release(ptr %result) {
entry:
  call void @free(ptr %result)
  ret void
}

define i64 @ql_4_worker__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %async_body_frame_field0 = getelementptr inbounds { i64 }, ptr %frame, i32 0, i32 0
  %async_body_frame_value0 = load i64, ptr %async_body_frame_field0
  store i64 %async_body_frame_value0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  store i64 %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load i64, ptr %l0__return
  ret i64 %t1
}

define ptr @ql_4_worker__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_4_worker__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_4_worker(i64 %arg0) {
entry:
  %async_frame = call ptr @qlrt_async_frame_alloc(i64 8, i64 8)
  %async_frame_field0 = getelementptr inbounds { i64 }, ptr %async_frame, i32 0, i32 0
  store i64 %arg0, ptr %async_frame_field0
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_4_worker__async_entry, ptr %async_frame)
  ret ptr %async_task
}

define i64 @ql_5_main__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca ptr
  %l2__t1 = alloca ptr
  %l3__t2 = alloca [2 x ptr]
  %l4__t3 = alloca { [2 x ptr] }
  %l5_pending = alloca { [2 x ptr] }
  %l6__t4 = alloca { i64 }
  %l7_slot = alloca { i64 }
  %l8_alias = alloca [2 x ptr]
  %l9__t5 = alloca i64
  %l10_first = alloca i64
  %l11__t6 = alloca i64
  %l12__t7 = alloca ptr
  %l13__t8 = alloca ptr
  %l14__t9 = alloca { ptr, ptr }
  %l15__t10 = alloca { { ptr, ptr }, ptr }
  %l16_env = alloca { { ptr, ptr }, ptr }
  %l17__t11 = alloca ptr
  %l18_running = alloca ptr
  %l19__t12 = alloca i64
  %l20_second = alloca i64
  %l21__t13 = alloca i64
  %l22_extra = alloca i64
  %l23__t14 = alloca i64
  %l24_tail = alloca i64
  %l25__t15 = alloca i64
  %l26__t16 = alloca i64
  br label %bb0
bb0:
  %t0 = call ptr @ql_4_worker(i64 9)
  store ptr %t0, ptr %l1__t0
  %t1 = call ptr @ql_4_worker(i64 14)
  store ptr %t1, ptr %l2__t1
  %t2 = load ptr, ptr %l1__t0
  %t3 = load ptr, ptr %l2__t1
  %t4 = insertvalue [2 x ptr] undef, ptr %t2, 0
  %t5 = insertvalue [2 x ptr] %t4, ptr %t3, 1
  store [2 x ptr] %t5, ptr %l3__t2
  %t6 = load [2 x ptr], ptr %l3__t2
  %t7 = insertvalue { [2 x ptr] } undef, [2 x ptr] %t6, 0
  store { [2 x ptr] } %t7, ptr %l4__t3
  %t8 = load { [2 x ptr] }, ptr %l4__t3
  store { [2 x ptr] } %t8, ptr %l5_pending
  %t9 = insertvalue { i64 } undef, i64 0, 0
  store { i64 } %t9, ptr %l6__t4
  %t10 = load { i64 }, ptr %l6__t4
  store { i64 } %t10, ptr %l7_slot
  %t11 = getelementptr inbounds { [2 x ptr] }, ptr %l5_pending, i32 0, i32 0
  %t12 = load [2 x ptr], ptr %t11
  store [2 x ptr] %t12, ptr %l8_alias
  %t13 = getelementptr inbounds { [2 x ptr] }, ptr %l5_pending, i32 0, i32 0
  %t14 = getelementptr inbounds [2 x ptr], ptr %t13, i64 0, i64 0
  %t15 = load ptr, ptr %t14
  %t16 = call ptr @qlrt_task_await(ptr %t15)
  %t17 = load i64, ptr %t16
  call void @qlrt_task_result_release(ptr %t16)
  store i64 %t17, ptr %l9__t5
  %t18 = load i64, ptr %l9__t5
  store i64 %t18, ptr %l10_first
  %t19 = load i64, ptr %l10_first
  %t20 = add i64 %t19, 4
  store i64 %t20, ptr %l11__t6
  %t21 = load i64, ptr %l11__t6
  %t22 = call ptr @ql_4_worker(i64 %t21)
  store ptr %t22, ptr %l12__t7
  %t23 = load ptr, ptr %l12__t7
  %t24 = getelementptr inbounds { [2 x ptr] }, ptr %l5_pending, i32 0, i32 0
  %t25 = getelementptr inbounds [2 x ptr], ptr %t24, i64 0, i64 0
  store ptr %t23, ptr %t25
  %t26 = call ptr @ql_4_worker(i64 7)
  store ptr %t26, ptr %l13__t8
  %t27 = getelementptr inbounds { [2 x ptr] }, ptr %l5_pending, i32 0, i32 0
  %t28 = getelementptr inbounds [2 x ptr], ptr %t27, i64 0, i64 0
  %t29 = load ptr, ptr %t28
  %t30 = load ptr, ptr %l13__t8
  %t31 = insertvalue { ptr, ptr } undef, ptr %t29, 0
  %t32 = insertvalue { ptr, ptr } %t31, ptr %t30, 1
  store { ptr, ptr } %t32, ptr %l14__t9
  %t33 = load { ptr, ptr }, ptr %l14__t9
  %t34 = getelementptr inbounds { [2 x ptr] }, ptr %l5_pending, i32 0, i32 0
  %t35 = getelementptr inbounds [2 x ptr], ptr %t34, i64 0, i64 1
  %t36 = load ptr, ptr %t35
  %t37 = insertvalue { { ptr, ptr }, ptr } undef, { ptr, ptr } %t33, 0
  %t38 = insertvalue { { ptr, ptr }, ptr } %t37, ptr %t36, 1
  store { { ptr, ptr }, ptr } %t38, ptr %l15__t10
  %t39 = load { { ptr, ptr }, ptr }, ptr %l15__t10
  store { { ptr, ptr }, ptr } %t39, ptr %l16_env
  %t40 = getelementptr inbounds { { ptr, ptr }, ptr }, ptr %l15__t10, i32 0, i32 0
  %t41 = getelementptr inbounds { ptr, ptr }, ptr %t40, i32 0, i32 0
  %t42 = load ptr, ptr %t41
  %t43 = call ptr @qlrt_executor_spawn(ptr null, ptr %t42)
  store ptr %t43, ptr %l17__t11
  %t44 = load ptr, ptr %l17__t11
  store ptr %t44, ptr %l18_running
  %t45 = load ptr, ptr %l17__t11
  %t46 = call ptr @qlrt_task_await(ptr %t45)
  %t47 = load i64, ptr %t46
  call void @qlrt_task_result_release(ptr %t46)
  store i64 %t47, ptr %l19__t12
  %t48 = load i64, ptr %l19__t12
  store i64 %t48, ptr %l20_second
  %t49 = getelementptr inbounds { { ptr, ptr }, ptr }, ptr %l15__t10, i32 0, i32 0
  %t50 = getelementptr inbounds { ptr, ptr }, ptr %t49, i32 0, i32 1
  %t51 = load ptr, ptr %t50
  %t52 = call ptr @qlrt_task_await(ptr %t51)
  %t53 = load i64, ptr %t52
  call void @qlrt_task_result_release(ptr %t52)
  store i64 %t53, ptr %l21__t13
  %t54 = load i64, ptr %l21__t13
  store i64 %t54, ptr %l22_extra
  %t55 = getelementptr inbounds { { ptr, ptr }, ptr }, ptr %l15__t10, i32 0, i32 1
  %t56 = load ptr, ptr %t55
  %t57 = call ptr @qlrt_task_await(ptr %t56)
  %t58 = load i64, ptr %t57
  call void @qlrt_task_result_release(ptr %t57)
  store i64 %t58, ptr %l23__t14
  %t59 = load i64, ptr %l23__t14
  store i64 %t59, ptr %l24_tail
  %t60 = load i64, ptr %l20_second
  %t61 = load i64, ptr %l22_extra
  %t62 = add i64 %t60, %t61
  store i64 %t62, ptr %l25__t15
  %t63 = load i64, ptr %l25__t15
  %t64 = load i64, ptr %l24_tail
  %t65 = add i64 %t63, %t64
  store i64 %t65, ptr %l26__t16
  %t66 = load i64, ptr %l26__t16
  store i64 %t66, ptr %l0__return
  br label %bb1
bb1:
  %t67 = load i64, ptr %l0__return
  ret i64 %t67
}

define ptr @ql_5_main__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_5_main__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_5_main() {
entry:
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_5_main__async_entry, ptr null)
  ret ptr %async_task
}

define i32 @main() {
entry:
  %async_main_task = call ptr @ql_5_main()
  %async_main_join = call ptr @qlrt_executor_spawn(ptr null, ptr %async_main_task)
  %async_main_res = call ptr @qlrt_task_await(ptr %async_main_join)
  %async_main_ret = load i64, ptr %async_main_res
  call void @qlrt_task_result_release(ptr %async_main_res)
  %async_main_exit = trunc i64 %async_main_ret to i32
  ret i32 %async_main_exit
}
