; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'async_program_main_const_backed_alias_sourced_composed_dynamic_task_handle_forwarded_nested_array_repackage_spawn'
source_filename = "async_program_main_const_backed_alias_sourced_composed_dynamic_task_handle_forwarded_nested_array_repackage_spawn.ql"
target triple = "{{TARGET_TRIPLE}}"

declare ptr @malloc(i64)
declare void @free(ptr)

define ptr @qlrt_async_frame_alloc(i64 %size, i64 %align) {
entry:
  %frame_is_zero = icmp eq i64 %size, 0
  %frame_alloc_size = select i1 %frame_is_zero, i64 1, i64 %size
  %frame = call ptr @malloc(i64 %frame_alloc_size)
  ret ptr %frame
}

define ptr @qlrt_async_task_create(ptr %entry_fn, ptr %frame) {
entry:
  %task_end = getelementptr { ptr, ptr, ptr }, ptr null, i32 1
  %task_size = ptrtoint ptr %task_end to i64
  %task = call ptr @malloc(i64 %task_size)
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  store ptr %entry_fn, ptr %task_entry_ptr
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  store ptr %frame, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr null, ptr %task_result_ptr
  ret ptr %task
}

define ptr @qlrt_executor_spawn(ptr %executor, ptr %task) {
entry:
  %task_entry_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 0
  %task_entry = load ptr, ptr %task_entry_ptr
  %task_started = icmp eq ptr %task_entry, null
  br i1 %task_started, label %done, label %start

start:
  %task_frame_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 1
  %task_frame = load ptr, ptr %task_frame_ptr
  %task_result = call ptr %task_entry(ptr %task_frame)
  call void @free(ptr %task_frame)
  store ptr null, ptr %task_entry_ptr
  store ptr null, ptr %task_frame_ptr
  %task_result_ptr = getelementptr inbounds { ptr, ptr, ptr }, ptr %task, i32 0, i32 2
  store ptr %task_result, ptr %task_result_ptr
  br label %done

done:
  ret ptr %task
}

define ptr @qlrt_task_await(ptr %handle) {
entry:
  %started = call ptr @qlrt_executor_spawn(ptr null, ptr %handle)
  %result_ptr_slot = getelementptr inbounds { ptr, ptr, ptr }, ptr %started, i32 0, i32 2
  %result_ptr = load ptr, ptr %result_ptr_slot
  call void @free(ptr %started)
  ret ptr %result_ptr
}

define void @qlrt_task_result_release(ptr %result) {
entry:
  call void @free(ptr %result)
  ret void
}

define i64 @ql_4_worker__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %async_body_frame_field0 = getelementptr inbounds { i64 }, ptr %frame, i32 0, i32 0
  %async_body_frame_value0 = load i64, ptr %async_body_frame_field0
  store i64 %async_body_frame_value0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  store i64 %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load i64, ptr %l0__return
  ret i64 %t1
}

define ptr @ql_4_worker__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_4_worker__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_4_worker(i64 %arg0) {
entry:
  %async_frame = call ptr @qlrt_async_frame_alloc(i64 8, i64 8)
  %async_frame_field0 = getelementptr inbounds { i64 }, ptr %async_frame, i32 0, i32 0
  store i64 %arg0, ptr %async_frame_field0
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_4_worker__async_entry, ptr %async_frame)
  ret ptr %async_task
}

define ptr @ql_5_forward(ptr %arg0) {
entry:
  %l0__return = alloca ptr
  %l1_task = alloca ptr
  store ptr %arg0, ptr %l1_task
  br label %bb0
bb0:
  %t0 = load ptr, ptr %l1_task
  store ptr %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load ptr, ptr %l0__return
  ret ptr %t1
}

define i64 @ql_6_main__async_body(ptr %frame) {
entry:
  %l0__return = alloca i64
  %l1_row = alloca i64
  %l2__t0 = alloca [2 x i64]
  %l3_slots = alloca [2 x i64]
  %l4_alias_slots = alloca [2 x i64]
  %l5__t1 = alloca ptr
  %l6__t2 = alloca ptr
  %l7__t3 = alloca [2 x ptr]
  %l8__t4 = alloca { [2 x ptr] }
  %l9_pending = alloca { [2 x ptr] }
  %l10_alias = alloca [2 x ptr]
  %l11__t5 = alloca i64
  %l12_first = alloca i64
  %l13__t6 = alloca i64
  %l14__t7 = alloca ptr
  %l15__t8 = alloca ptr
  %l16__t9 = alloca ptr
  %l17__t10 = alloca [2 x ptr]
  %l18__t11 = alloca { [2 x ptr] }
  %l19__t12 = alloca { { [2 x ptr] }, ptr }
  %l20_env = alloca { { [2 x ptr] }, ptr }
  %l21__t13 = alloca ptr
  %l22_running = alloca ptr
  %l23__t14 = alloca i64
  %l24_second = alloca i64
  %l25__t15 = alloca i64
  %l26_extra = alloca i64
  %l27__t16 = alloca i64
  %l28_tail = alloca i64
  %l29__t17 = alloca i64
  %l30__t18 = alloca i64
  br label %bb0
bb0:
  store i64 0, ptr %l1_row
  %t0 = load i64, ptr %l1_row
  %t1 = load i64, ptr %l1_row
  %t2 = insertvalue [2 x i64] undef, i64 %t0, 0
  %t3 = insertvalue [2 x i64] %t2, i64 %t1, 1
  store [2 x i64] %t3, ptr %l2__t0
  %t4 = load [2 x i64], ptr %l2__t0
  store [2 x i64] %t4, ptr %l3_slots
  %t5 = load [2 x i64], ptr %l3_slots
  store [2 x i64] %t5, ptr %l4_alias_slots
  %t6 = call ptr @ql_4_worker(i64 9)
  store ptr %t6, ptr %l5__t1
  %t7 = call ptr @ql_4_worker(i64 14)
  store ptr %t7, ptr %l6__t2
  %t8 = load ptr, ptr %l5__t1
  %t9 = load ptr, ptr %l6__t2
  %t10 = insertvalue [2 x ptr] undef, ptr %t8, 0
  %t11 = insertvalue [2 x ptr] %t10, ptr %t9, 1
  store [2 x ptr] %t11, ptr %l7__t3
  %t12 = load [2 x ptr], ptr %l7__t3
  %t13 = insertvalue { [2 x ptr] } undef, [2 x ptr] %t12, 0
  store { [2 x ptr] } %t13, ptr %l8__t4
  %t14 = load { [2 x ptr] }, ptr %l8__t4
  store { [2 x ptr] } %t14, ptr %l9_pending
  %t15 = getelementptr inbounds { [2 x ptr] }, ptr %l9_pending, i32 0, i32 0
  %t16 = load [2 x ptr], ptr %t15
  store [2 x ptr] %t16, ptr %l10_alias
  %t17 = getelementptr inbounds { [2 x ptr] }, ptr %l9_pending, i32 0, i32 0
  %t18 = getelementptr inbounds [2 x ptr], ptr %t17, i64 0, i64 0
  %t19 = load ptr, ptr %t18
  %t20 = call ptr @qlrt_task_await(ptr %t19)
  %t21 = load i64, ptr %t20
  call void @qlrt_task_result_release(ptr %t20)
  store i64 %t21, ptr %l11__t5
  %t22 = load i64, ptr %l11__t5
  store i64 %t22, ptr %l12_first
  %t23 = load i64, ptr %l12_first
  %t24 = add i64 %t23, 11
  store i64 %t24, ptr %l13__t6
  %t25 = load i64, ptr %l13__t6
  %t26 = call ptr @ql_4_worker(i64 %t25)
  store ptr %t26, ptr %l14__t7
  %t27 = load ptr, ptr %l14__t7
  %t28 = getelementptr inbounds { [2 x ptr] }, ptr %l9_pending, i32 0, i32 0
  %t29 = getelementptr inbounds [2 x ptr], ptr %t28, i64 0, i64 0
  store ptr %t27, ptr %t29
  %t30 = getelementptr inbounds { [2 x ptr] }, ptr %l9_pending, i32 0, i32 0
  %t31 = getelementptr inbounds [2 x ptr], ptr %t30, i64 0, i64 0
  %t32 = load ptr, ptr %t31
  %t33 = call ptr @ql_5_forward(ptr %t32)
  store ptr %t33, ptr %l15__t8
  %t34 = call ptr @ql_4_worker(i64 27)
  store ptr %t34, ptr %l16__t9
  %t35 = load ptr, ptr %l15__t8
  %t36 = load ptr, ptr %l16__t9
  %t37 = insertvalue [2 x ptr] undef, ptr %t35, 0
  %t38 = insertvalue [2 x ptr] %t37, ptr %t36, 1
  store [2 x ptr] %t38, ptr %l17__t10
  %t39 = load [2 x ptr], ptr %l17__t10
  %t40 = insertvalue { [2 x ptr] } undef, [2 x ptr] %t39, 0
  store { [2 x ptr] } %t40, ptr %l18__t11
  %t41 = load { [2 x ptr] }, ptr %l18__t11
  %t42 = getelementptr inbounds { [2 x ptr] }, ptr %l9_pending, i32 0, i32 0
  %t43 = getelementptr inbounds [2 x ptr], ptr %t42, i64 0, i64 1
  %t44 = load ptr, ptr %t43
  %t45 = insertvalue { { [2 x ptr] }, ptr } undef, { [2 x ptr] } %t41, 0
  %t46 = insertvalue { { [2 x ptr] }, ptr } %t45, ptr %t44, 1
  store { { [2 x ptr] }, ptr } %t46, ptr %l19__t12
  %t47 = load { { [2 x ptr] }, ptr }, ptr %l19__t12
  store { { [2 x ptr] }, ptr } %t47, ptr %l20_env
  %t48 = getelementptr inbounds { { [2 x ptr] }, ptr }, ptr %l19__t12, i32 0, i32 0
  %t49 = getelementptr inbounds { [2 x ptr] }, ptr %t48, i32 0, i32 0
  %t50 = getelementptr inbounds [2 x ptr], ptr %t49, i64 0, i64 0
  %t51 = load ptr, ptr %t50
  %t52 = call ptr @qlrt_executor_spawn(ptr null, ptr %t51)
  store ptr %t52, ptr %l21__t13
  %t53 = load ptr, ptr %l21__t13
  store ptr %t53, ptr %l22_running
  %t54 = load ptr, ptr %l21__t13
  %t55 = call ptr @qlrt_task_await(ptr %t54)
  %t56 = load i64, ptr %t55
  call void @qlrt_task_result_release(ptr %t55)
  store i64 %t56, ptr %l23__t14
  %t57 = load i64, ptr %l23__t14
  store i64 %t57, ptr %l24_second
  %t58 = getelementptr inbounds { { [2 x ptr] }, ptr }, ptr %l19__t12, i32 0, i32 0
  %t59 = getelementptr inbounds { [2 x ptr] }, ptr %t58, i32 0, i32 0
  %t60 = getelementptr inbounds [2 x ptr], ptr %t59, i64 0, i64 1
  %t61 = load ptr, ptr %t60
  %t62 = call ptr @qlrt_task_await(ptr %t61)
  %t63 = load i64, ptr %t62
  call void @qlrt_task_result_release(ptr %t62)
  store i64 %t63, ptr %l25__t15
  %t64 = load i64, ptr %l25__t15
  store i64 %t64, ptr %l26_extra
  %t65 = getelementptr inbounds { { [2 x ptr] }, ptr }, ptr %l19__t12, i32 0, i32 1
  %t66 = load ptr, ptr %t65
  %t67 = call ptr @qlrt_task_await(ptr %t66)
  %t68 = load i64, ptr %t67
  call void @qlrt_task_result_release(ptr %t67)
  store i64 %t68, ptr %l27__t16
  %t69 = load i64, ptr %l27__t16
  store i64 %t69, ptr %l28_tail
  %t70 = load i64, ptr %l24_second
  %t71 = load i64, ptr %l26_extra
  %t72 = add i64 %t70, %t71
  store i64 %t72, ptr %l29__t17
  %t73 = load i64, ptr %l29__t17
  %t74 = load i64, ptr %l28_tail
  %t75 = add i64 %t73, %t74
  store i64 %t75, ptr %l30__t18
  %t76 = load i64, ptr %l30__t18
  store i64 %t76, ptr %l0__return
  br label %bb1
bb1:
  %t77 = load i64, ptr %l0__return
  ret i64 %t77
}

define ptr @ql_6_main__async_entry(ptr %frame) {
entry:
  %async_result = call i64 @ql_6_main__async_body(ptr %frame)
  %async_result_ptr = call ptr @malloc(i64 8)
  store i64 %async_result, ptr %async_result_ptr, align 8
  ret ptr %async_result_ptr
}

define ptr @ql_6_main() {
entry:
  %async_task = call ptr @qlrt_async_task_create(ptr @ql_6_main__async_entry, ptr null)
  ret ptr %async_task
}

define i32 @main() {
entry:
  %async_main_task = call ptr @ql_6_main()
  %async_main_join = call ptr @qlrt_executor_spawn(ptr null, ptr %async_main_task)
  %async_main_res = call ptr @qlrt_task_await(ptr %async_main_join)
  %async_main_ret = load i64, ptr %async_main_res
  call void @qlrt_task_result_release(ptr %async_main_res)
  %async_main_exit = trunc i64 %async_main_ret to i32
  ret i32 %async_main_exit
}
