; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'bool_dynamic_guard_match'
source_filename = "bool_dynamic_guard_match.ql"
target triple = "x86_64-pc-windows-msvc"

define i64 @ql_0_main() {
entry:
  %l0__return = alloca i64
  %l1_flag = alloca i1
  %l2_enabled = alloca i1
  %l3__t0 = alloca i64
  %l4__t1 = alloca i1
  br label %bb0
bb0:
  store i1 true, ptr %l1_flag
  store i1 false, ptr %l2_enabled
  %t0 = load i1, ptr %l1_flag
  store i1 %t0, ptr %l4__t1
  %t1 = load i1, ptr %l4__t1
  br i1 %t1, label %bb0_match_guard0, label %bb0_match_dispatch1
bb0_match_guard0:
  %t2 = load i1, ptr %l2_enabled
  br i1 %t2, label %bb3, label %bb0_match_dispatch1
bb0_match_dispatch1:
  br i1 %t1, label %bb4, label %bb0_match_dispatch2
bb0_match_dispatch2:
  br i1 %t1, label %bb2, label %bb5
bb1:
  %t3 = load i64, ptr %l0__return
  ret i64 %t3
bb2:
  %t4 = load i64, ptr %l3__t0
  store i64 %t4, ptr %l0__return
  br label %bb1
bb3:
  store i64 1, ptr %l3__t0
  br label %bb2
bb4:
  store i64 2, ptr %l3__t0
  br label %bb2
bb5:
  store i64 0, ptr %l3__t0
  br label %bb2
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_0_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
