; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'bool_short_circuit_expr'
source_filename = "bool_short_circuit_expr.ql"
target triple = "x86_64-pc-windows-msvc"

define i1 @ql_0_left_true() {
entry:
  %l0__return = alloca i1
  br label %bb0
bb0:
  store i1 true, ptr %l0__return
  br label %bb1
bb1:
  %t0 = load i1, ptr %l0__return
  ret i1 %t0
}

define i1 @ql_1_left_false() {
entry:
  %l0__return = alloca i1
  br label %bb0
bb0:
  store i1 false, ptr %l0__return
  br label %bb1
bb1:
  %t0 = load i1, ptr %l0__return
  ret i1 %t0
}

define i1 @ql_2_right_true() {
entry:
  %l0__return = alloca i1
  br label %bb0
bb0:
  store i1 true, ptr %l0__return
  br label %bb1
bb1:
  %t0 = load i1, ptr %l0__return
  ret i1 %t0
}

define i1 @ql_3_right_false() {
entry:
  %l0__return = alloca i1
  br label %bb0
bb0:
  store i1 false, ptr %l0__return
  br label %bb1
bb1:
  %t0 = load i1, ptr %l0__return
  ret i1 %t0
}

define i64 @ql_4_main() {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca i1
  %l2__t1 = alloca i1
  %l3__t2 = alloca i1
  %l4_both = alloca i1
  %l5__t3 = alloca i1
  %l6__t4 = alloca i1
  %l7__t5 = alloca i1
  %l8_either = alloca i1
  %l11__t8 = alloca i1
  %l12__t9 = alloca i1
  br label %bb0
bb0:
  %t0 = call i1 @ql_1_left_false()
  store i1 %t0, ptr %l2__t1
  %t1 = load i1, ptr %l2__t1
  br i1 %t1, label %bb3, label %bb4
bb1:
  %t2 = load i64, ptr %l0__return
  ret i64 %t2
bb2:
  %t3 = load i1, ptr %l1__t0
  store i1 %t3, ptr %l4_both
  %t4 = call i1 @ql_0_left_true()
  store i1 %t4, ptr %l6__t4
  %t5 = load i1, ptr %l6__t4
  br i1 %t5, label %bb7, label %bb6
bb3:
  %t6 = call i1 @ql_2_right_true()
  store i1 %t6, ptr %l3__t2
  %t7 = load i1, ptr %l3__t2
  store i1 %t7, ptr %l1__t0
  br label %bb2
bb4:
  store i1 false, ptr %l1__t0
  br label %bb2
bb5:
  %t8 = load i1, ptr %l5__t3
  store i1 %t8, ptr %l8_either
  %t9 = load i1, ptr %l4_both
  br i1 %t9, label %bb9, label %bb8
bb6:
  %t10 = call i1 @ql_3_right_false()
  store i1 %t10, ptr %l7__t5
  %t11 = load i1, ptr %l7__t5
  store i1 %t11, ptr %l5__t3
  br label %bb5
bb7:
  store i1 true, ptr %l5__t3
  br label %bb5
bb8:
  %t12 = load i1, ptr %l8_either
  br i1 %t12, label %bb12, label %bb13
bb9:
  store i64 1, ptr %l0__return
  br label %bb1
bb10:
  store i64 4, ptr %l0__return
  br label %bb1
bb11:
  %t13 = load i1, ptr %l11__t8
  br i1 %t13, label %bb14, label %bb10
bb12:
  %t14 = load i1, ptr %l4_both
  %t15 = xor i1 %t14, true
  store i1 %t15, ptr %l12__t9
  %t16 = load i1, ptr %l12__t9
  store i1 %t16, ptr %l11__t8
  br label %bb11
bb13:
  store i1 false, ptr %l11__t8
  br label %bb11
bb14:
  store i64 3, ptr %l0__return
  br label %bb1
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_4_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
