; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'bool_match'
source_filename = "bool_match.ql"
target triple = "x86_64-pc-windows-msvc"

define i64 @ql_0_main() {
entry:
  %l0__return = alloca i64
  %l1_flag = alloca i1
  %l2__t0 = alloca i64
  %l3__t1 = alloca i1
  br label %bb0
bb0:
  store i1 true, ptr %l1_flag
  %t0 = load i1, ptr %l1_flag
  store i1 %t0, ptr %l3__t1
  %t1 = load i1, ptr %l3__t1
  br i1 %t1, label %bb3, label %bb4
bb1:
  %t2 = load i64, ptr %l0__return
  ret i64 %t2
bb2:
  %t3 = load i64, ptr %l2__t0
  store i64 %t3, ptr %l0__return
  br label %bb1
bb3:
  store i64 1, ptr %l2__t0
  br label %bb2
bb4:
  store i64 0, ptr %l2__t0
  br label %bb2
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_0_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
