; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'capturing_closure_reassigned_alias_call'
source_filename = "capturing_closure_reassigned_alias_call.ql"
target triple = "{{TARGET_TRIPLE}}"

define i64 @ql_0_main() {
entry:
  %l0__return = alloca i64
  %l1_first = alloca i64
  %l2_second = alloca i64
  %l3__t0 = alloca ptr
  %l4_capture_first = alloca ptr
  %l5__t1 = alloca ptr
  %l6_capture_second = alloca ptr
  %l7_alias = alloca ptr
  %l8__t2 = alloca i64
  br label %bb0
bb0:
  store i64 1, ptr %l1_first
  store i64 2, ptr %l2_second
  store ptr null, ptr %l3__t0
  %t0 = load ptr, ptr %l3__t0
  store ptr %t0, ptr %l4_capture_first
  store ptr null, ptr %l5__t1
  %t1 = load ptr, ptr %l5__t1
  store ptr %t1, ptr %l6_capture_second
  %t2 = load ptr, ptr %l4_capture_first
  store ptr %t2, ptr %l7_alias
  %t3 = load ptr, ptr %l6_capture_second
  store ptr %t3, ptr %l7_alias
  %t4 = load i64, ptr %l2_second
  %t5 = call i64 @ql_0_main__closure1(i64 %t4)
  store i64 %t5, ptr %l8__t2
  %t6 = load i64, ptr %l8__t2
  store i64 %t6, ptr %l0__return
  br label %bb1
bb1:
  %t7 = load i64, ptr %l0__return
  ret i64 %t7
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_0_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}

define i64 @ql_0_main__closure0(i64 %arg0) {
entry:
  %l0__return = alloca i64
  %l1_first = alloca i64
  store i64 %arg0, ptr %l1_first
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_first
  store i64 %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load i64, ptr %l0__return
  ret i64 %t1
}

define i64 @ql_0_main__closure1(i64 %arg0) {
entry:
  %l0__return = alloca i64
  %l1_second = alloca i64
  store i64 %arg0, ptr %l1_second
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_second
  store i64 %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load i64, ptr %l0__return
  ret i64 %t1
}
