; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'closure_backed_callable_const_static_build'
source_filename = "closure_backed_callable_const_static_build.ql"
target triple = "x86_64-pc-windows-msvc"

define i64 @ql_2_main() {
entry:
  %l0__return = alloca i64
  %l1_f = alloca ptr
  %l2_g = alloca ptr
  %l3__t0 = alloca i64
  %l4__t1 = alloca i64
  %l5__t2 = alloca i64
  %l6__t3 = alloca i64
  %l7__t4 = alloca i64
  %l8__t5 = alloca i64
  %l9__t6 = alloca i64
  br label %bb0
bb0:
  store ptr @ql_0_APPLY_CONST__closure0, ptr %l1_f
  store ptr @ql_1_APPLY_STATIC__closure0, ptr %l2_g
  %t0 = call i64 @ql_0_APPLY_CONST__closure0(i64 10)
  store i64 %t0, ptr %l3__t0
  %t1 = call i64 @ql_1_APPLY_STATIC__closure0(i64 20)
  store i64 %t1, ptr %l4__t1
  %t2 = load i64, ptr %l3__t0
  %t3 = load i64, ptr %l4__t1
  %t4 = add i64 %t2, %t3
  store i64 %t4, ptr %l5__t2
  %t5 = load ptr, ptr %l1_f
  %t6 = call i64 %t5(i64 30)
  store i64 %t6, ptr %l6__t3
  %t7 = load i64, ptr %l5__t2
  %t8 = load i64, ptr %l6__t3
  %t9 = add i64 %t7, %t8
  store i64 %t9, ptr %l7__t4
  %t10 = load ptr, ptr %l2_g
  %t11 = call i64 %t10(i64 40)
  store i64 %t11, ptr %l8__t5
  %t12 = load i64, ptr %l7__t4
  %t13 = load i64, ptr %l8__t5
  %t14 = add i64 %t12, %t13
  store i64 %t14, ptr %l9__t6
  %t15 = load i64, ptr %l9__t6
  store i64 %t15, ptr %l0__return
  br label %bb1
bb1:
  %t16 = load i64, ptr %l0__return
  ret i64 %t16
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_2_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}

define i64 @ql_0_APPLY_CONST__closure0(i64 %arg0) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %l2__t0 = alloca i64
  store i64 %arg0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  %t1 = add i64 %t0, 1
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l2__t0
  store i64 %t2, ptr %l0__return
  br label %bb1
bb1:
  %t3 = load i64, ptr %l0__return
  ret i64 %t3
}

define i64 @ql_1_APPLY_STATIC__closure0(i64 %arg0) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %l2__t0 = alloca i64
  store i64 %arg0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  %t1 = add i64 %t0, 2
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l2__t0
  store i64 %t2, ptr %l0__return
  br label %bb1
bb1:
  %t3 = load i64, ptr %l0__return
  ret i64 %t3
}
