; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'empty_array_expected'
source_filename = "empty_array_expected.ql"
target triple = "{{TARGET_TRIPLE}}"

define [0 x i64] @ql_0_values() {
entry:
  %l0__return = alloca [0 x i64]
  %l1__t0 = alloca [0 x i64]
  br label %bb0
bb0:
  store [0 x i64] zeroinitializer, ptr %l1__t0
  %t0 = load [0 x i64], ptr %l1__t0
  store [0 x i64] %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load [0 x i64], ptr %l0__return
  ret [0 x i64] %t1
}

define { [0 x i64], i64 } @ql_1_pair() {
entry:
  %l0__return = alloca { [0 x i64], i64 }
  %l1__t0 = alloca [0 x i64]
  %l2__t1 = alloca { [0 x i64], i64 }
  br label %bb0
bb0:
  store [0 x i64] zeroinitializer, ptr %l1__t0
  %t0 = load [0 x i64], ptr %l1__t0
  %t1 = insertvalue { [0 x i64], i64 } undef, [0 x i64] %t0, 0
  %t2 = insertvalue { [0 x i64], i64 } %t1, i64 1, 1
  store { [0 x i64], i64 } %t2, ptr %l2__t1
  %t3 = load { [0 x i64], i64 }, ptr %l2__t1
  store { [0 x i64], i64 } %t3, ptr %l0__return
  br label %bb1
bb1:
  %t4 = load { [0 x i64], i64 }, ptr %l0__return
  ret { [0 x i64], i64 } %t4
}

define { [0 x i64] } @ql_3_build() {
entry:
  %l0__return = alloca { [0 x i64] }
  %l1__t0 = alloca [0 x i64]
  %l2__t1 = alloca { [0 x i64] }
  br label %bb0
bb0:
  store [0 x i64] zeroinitializer, ptr %l1__t0
  %t0 = load [0 x i64], ptr %l1__t0
  %t1 = insertvalue { [0 x i64] } undef, [0 x i64] %t0, 0
  store { [0 x i64] } %t1, ptr %l2__t1
  %t2 = load { [0 x i64] }, ptr %l2__t1
  store { [0 x i64] } %t2, ptr %l0__return
  br label %bb1
bb1:
  %t3 = load { [0 x i64] }, ptr %l0__return
  ret { [0 x i64] } %t3
}

define [1 x [0 x i64]] @ql_4_nested() {
entry:
  %l0__return = alloca [1 x [0 x i64]]
  %l1__t0 = alloca [0 x i64]
  %l2__t1 = alloca [1 x [0 x i64]]
  br label %bb0
bb0:
  store [0 x i64] zeroinitializer, ptr %l1__t0
  %t0 = load [0 x i64], ptr %l1__t0
  %t1 = insertvalue [1 x [0 x i64]] undef, [0 x i64] %t0, 0
  store [1 x [0 x i64]] %t1, ptr %l2__t1
  %t2 = load [1 x [0 x i64]], ptr %l2__t1
  store [1 x [0 x i64]] %t2, ptr %l0__return
  br label %bb1
bb1:
  %t3 = load [1 x [0 x i64]], ptr %l0__return
  ret [1 x [0 x i64]] %t3
}

define i64 @ql_5_take([0 x i64] %arg0) {
entry:
  %l0__return = alloca i64
  %l1_values = alloca [0 x i64]
  store [0 x i64] %arg0, ptr %l1_values
  br label %bb0
bb0:
  store i64 0, ptr %l0__return
  br label %bb1
bb1:
  %t0 = load i64, ptr %l0__return
  ret i64 %t0
}

define i64 @ql_6_main() {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca { [0 x i64], i64 }
  %l2_pair_value = alloca { [0 x i64], i64 }
  %l3__t1 = alloca { [0 x i64] }
  %l4_wrap = alloca { [0 x i64] }
  %l5__t2 = alloca [1 x [0 x i64]]
  %l6_nested_values = alloca [1 x [0 x i64]]
  %l7__t3 = alloca [0 x i64]
  %l8__t4 = alloca i64
  %l9__t5 = alloca i64
  %l10__t6 = alloca i64
  %l11__t7 = alloca i64
  %l12__t8 = alloca i64
  %l13__t9 = alloca i64
  %l14__t10 = alloca [0 x i64]
  %l15__t11 = alloca i64
  %l16__t12 = alloca i64
  br label %bb0
bb0:
  %t0 = call { [0 x i64], i64 } @ql_1_pair()
  store { [0 x i64], i64 } %t0, ptr %l1__t0
  %t1 = load { [0 x i64], i64 }, ptr %l1__t0
  store { [0 x i64], i64 } %t1, ptr %l2_pair_value
  %t2 = call { [0 x i64] } @ql_3_build()
  store { [0 x i64] } %t2, ptr %l3__t1
  %t3 = load { [0 x i64] }, ptr %l3__t1
  store { [0 x i64] } %t3, ptr %l4_wrap
  %t4 = call [1 x [0 x i64]] @ql_4_nested()
  store [1 x [0 x i64]] %t4, ptr %l5__t2
  %t5 = load [1 x [0 x i64]], ptr %l5__t2
  store [1 x [0 x i64]] %t5, ptr %l6_nested_values
  %t6 = call [0 x i64] @ql_0_values()
  store [0 x i64] %t6, ptr %l7__t3
  %t7 = load [0 x i64], ptr %l7__t3
  %t8 = call i64 @ql_5_take([0 x i64] %t7)
  store i64 %t8, ptr %l8__t4
  %t9 = load i64, ptr %l8__t4
  %t10 = getelementptr inbounds { [0 x i64], i64 }, ptr %l2_pair_value, i32 0, i32 1
  %t11 = load i64, ptr %t10
  %t12 = add i64 %t9, %t11
  store i64 %t12, ptr %l9__t5
  %t13 = getelementptr inbounds { [0 x i64] }, ptr %l4_wrap, i32 0, i32 0
  %t14 = load [0 x i64], ptr %t13
  %t15 = call i64 @ql_5_take([0 x i64] %t14)
  store i64 %t15, ptr %l10__t6
  %t16 = load i64, ptr %l9__t5
  %t17 = load i64, ptr %l10__t6
  %t18 = add i64 %t16, %t17
  store i64 %t18, ptr %l11__t7
  %t19 = getelementptr inbounds [1 x [0 x i64]], ptr %l6_nested_values, i64 0, i64 0
  %t20 = load [0 x i64], ptr %t19
  %t21 = call i64 @ql_5_take([0 x i64] %t20)
  store i64 %t21, ptr %l12__t8
  %t22 = load i64, ptr %l11__t7
  %t23 = load i64, ptr %l12__t8
  %t24 = add i64 %t22, %t23
  store i64 %t24, ptr %l13__t9
  store [0 x i64] zeroinitializer, ptr %l14__t10
  %t25 = load [0 x i64], ptr %l14__t10
  %t26 = call i64 @ql_5_take([0 x i64] %t25)
  store i64 %t26, ptr %l15__t11
  %t27 = load i64, ptr %l13__t9
  %t28 = load i64, ptr %l15__t11
  %t29 = add i64 %t27, %t28
  store i64 %t29, ptr %l16__t12
  %t30 = load i64, ptr %l16__t12
  store i64 %t30, ptr %l0__return
  br label %bb1
bb1:
  %t31 = load i64, ptr %l0__return
  ret i64 %t31
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_6_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
