; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'extern_c_build'
source_filename = "extern_c_build.ql"
target triple = "{{TARGET_TRIPLE}}"

declare i64 @q_add(i64, i64)

define i64 @ql_1_main() {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca i64
  br label %bb0
bb0:
  %t0 = call i64 @q_add(i64 1, i64 2)
  store i64 %t0, ptr %l1__t0
  %t1 = load i64, ptr %l1__t0
  store i64 %t1, ptr %l0__return
  br label %bb1
bb1:
  %t2 = load i64, ptr %l0__return
  ret i64 %t2
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_1_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
