; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'extern_c_export'
source_filename = "extern_c_export.ql"
target triple = "{{TARGET_TRIPLE}}"

define i64 @q_add(i64 %arg0, i64 %arg1) {
entry:
  %l0__return = alloca i64
  %l1_left = alloca i64
  %l2_right = alloca i64
  %l3__t0 = alloca i64
  store i64 %arg0, ptr %l1_left
  store i64 %arg1, ptr %l2_right
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_left
  %t1 = load i64, ptr %l2_right
  %t2 = add i64 %t0, %t1
  store i64 %t2, ptr %l3__t0
  %t3 = load i64, ptr %l3__t0
  store i64 %t3, ptr %l0__return
  br label %bb1
bb1:
  %t4 = load i64, ptr %l0__return
  ret i64 %t4
}

define i64 @ql_1_main() {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca i64
  br label %bb0
bb0:
  %t0 = call i64 @q_add(i64 1, i64 2)
  store i64 %t0, ptr %l1__t0
  %t1 = load i64, ptr %l1__t0
  store i64 %t1, ptr %l0__return
  br label %bb1
bb1:
  %t2 = load i64, ptr %l0__return
  ret i64 %t2
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_1_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
