; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'import_alias_call_root_fixed_shapes'
source_filename = "import_alias_call_root_fixed_shapes.ql"
target triple = "x86_64-pc-windows-msvc"

define [2 x i64] @ql_1_array_values(i64 %arg0) {
entry:
  %l0__return = alloca [2 x i64]
  %l1_base = alloca i64
  %l2__t0 = alloca [2 x i64]
  store i64 %arg0, ptr %l1_base
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_base
  %t1 = load i64, ptr %l1_base
  %t2 = insertvalue [2 x i64] undef, i64 %t0, 0
  %t3 = insertvalue [2 x i64] %t2, i64 %t1, 1
  store [2 x i64] %t3, ptr %l2__t0
  %t4 = load [2 x i64], ptr %l2__t0
  store [2 x i64] %t4, ptr %l0__return
  br label %bb1
bb1:
  %t5 = load [2 x i64], ptr %l0__return
  ret [2 x i64] %t5
}

define { i64, i64 } @ql_2_tuple_values(i64 %arg0) {
entry:
  %l0__return = alloca { i64, i64 }
  %l1_base = alloca i64
  %l2__t0 = alloca i64
  %l3__t1 = alloca { i64, i64 }
  store i64 %arg0, ptr %l1_base
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_base
  %t1 = add i64 %t0, 1
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l1_base
  %t3 = load i64, ptr %l2__t0
  %t4 = insertvalue { i64, i64 } undef, i64 %t2, 0
  %t5 = insertvalue { i64, i64 } %t4, i64 %t3, 1
  store { i64, i64 } %t5, ptr %l3__t1
  %t6 = load { i64, i64 }, ptr %l3__t1
  store { i64, i64 } %t6, ptr %l0__return
  br label %bb1
bb1:
  %t7 = load { i64, i64 }, ptr %l0__return
  ret { i64, i64 } %t7
}

define { [2 x i64] } @ql_3_make_payload(i64 %arg0) {
entry:
  %l0__return = alloca { [2 x i64] }
  %l1_base = alloca i64
  %l2__t0 = alloca i64
  %l3__t1 = alloca [2 x i64]
  %l4__t2 = alloca { [2 x i64] }
  store i64 %arg0, ptr %l1_base
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_base
  %t1 = add i64 %t0, 1
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l1_base
  %t3 = load i64, ptr %l2__t0
  %t4 = insertvalue [2 x i64] undef, i64 %t2, 0
  %t5 = insertvalue [2 x i64] %t4, i64 %t3, 1
  store [2 x i64] %t5, ptr %l3__t1
  %t6 = load [2 x i64], ptr %l3__t1
  %t7 = insertvalue { [2 x i64] } undef, [2 x i64] %t6, 0
  store { [2 x i64] } %t7, ptr %l4__t2
  %t8 = load { [2 x i64] }, ptr %l4__t2
  store { [2 x i64] } %t8, ptr %l0__return
  br label %bb1
bb1:
  %t9 = load { [2 x i64] }, ptr %l0__return
  ret { [2 x i64] } %t9
}

define i64 @ql_4_main() {
entry:
  %l0__return = alloca i64
  %l1_total = alloca i64
  %l2__t0 = alloca [2 x i64]
  %l3__t1 = alloca i64
  %l4_value = alloca i64
  %l5__t2 = alloca i64
  %l6__t3 = alloca { i64, i64 }
  %l7__t4 = alloca i64
  %l8_value = alloca i64
  %l9__t5 = alloca i64
  %l10__t6 = alloca { [2 x i64] }
  %l11__t7 = alloca { [2 x i64] }
  %l12__t8 = alloca i64
  %l13_value = alloca i64
  %l14__t9 = alloca i64
  %for_await_index_bb2 = alloca i64
  %for_await_index_bb5 = alloca i64
  %for_await_index_bb8 = alloca i64
  store i64 -1, ptr %for_await_index_bb2
  store i64 -1, ptr %for_await_index_bb5
  store i64 -1, ptr %for_await_index_bb8
  br label %bb0
bb0:
  store i64 0, ptr %l1_total
  %t0 = call [2 x i64] @ql_1_array_values(i64 10)
  store [2 x i64] %t0, ptr %l2__t0
  %t1 = load i64, ptr %for_await_index_bb2
  %t2 = add i64 %t1, 1
  store i64 %t2, ptr %for_await_index_bb2
  br label %bb2
bb1:
  %t3 = load i64, ptr %l0__return
  ret i64 %t3
bb2:
  %t4 = load i64, ptr %for_await_index_bb2
  %t5 = icmp ult i64 %t4, 2
  br i1 %t5, label %bb2_for_await_setup, label %bb4
bb3:
  %t6 = load i64, ptr %l3__t1
  store i64 %t6, ptr %l4_value
  %t7 = load i64, ptr %l1_total
  %t8 = load i64, ptr %l4_value
  %t9 = add i64 %t7, %t8
  store i64 %t9, ptr %l5__t2
  %t10 = load i64, ptr %l5__t2
  store i64 %t10, ptr %l1_total
  %t11 = load i64, ptr %for_await_index_bb2
  %t12 = add i64 %t11, 1
  store i64 %t12, ptr %for_await_index_bb2
  br label %bb2
bb4:
  %t13 = call { i64, i64 } @ql_2_tuple_values(i64 7)
  store { i64, i64 } %t13, ptr %l6__t3
  %t14 = load i64, ptr %for_await_index_bb5
  %t15 = add i64 %t14, 1
  store i64 %t15, ptr %for_await_index_bb5
  br label %bb5
bb5:
  %t16 = load i64, ptr %for_await_index_bb5
  %t17 = icmp ult i64 %t16, 2
  br i1 %t17, label %bb5_for_await_setup, label %bb7
bb6:
  %t18 = load i64, ptr %l7__t4
  store i64 %t18, ptr %l8_value
  %t19 = load i64, ptr %l1_total
  %t20 = load i64, ptr %l8_value
  %t21 = add i64 %t19, %t20
  store i64 %t21, ptr %l9__t5
  %t22 = load i64, ptr %l9__t5
  store i64 %t22, ptr %l1_total
  %t23 = load i64, ptr %for_await_index_bb5
  %t24 = add i64 %t23, 1
  store i64 %t24, ptr %for_await_index_bb5
  br label %bb5
bb7:
  %t25 = call { [2 x i64] } @ql_3_make_payload(i64 3)
  store { [2 x i64] } %t25, ptr %l10__t6
  %t26 = load { [2 x i64] }, ptr %l10__t6
  store { [2 x i64] } %t26, ptr %l11__t7
  %t27 = load i64, ptr %for_await_index_bb8
  %t28 = add i64 %t27, 1
  store i64 %t28, ptr %for_await_index_bb8
  br label %bb8
bb8:
  %t29 = load i64, ptr %for_await_index_bb8
  %t30 = icmp ult i64 %t29, 2
  br i1 %t30, label %bb8_for_await_setup, label %bb10
bb9:
  %t31 = load i64, ptr %l12__t8
  store i64 %t31, ptr %l13_value
  %t32 = load i64, ptr %l1_total
  %t33 = load i64, ptr %l13_value
  %t34 = add i64 %t32, %t33
  store i64 %t34, ptr %l14__t9
  %t35 = load i64, ptr %l14__t9
  store i64 %t35, ptr %l1_total
  %t36 = load i64, ptr %for_await_index_bb8
  %t37 = add i64 %t36, 1
  store i64 %t37, ptr %for_await_index_bb8
  br label %bb8
bb10:
  %t38 = load i64, ptr %l1_total
  store i64 %t38, ptr %l0__return
  br label %bb1
bb2_for_await_setup:
  %t39 = load i64, ptr %for_await_index_bb2
  %t40 = getelementptr inbounds [2 x i64], ptr %l2__t0, i64 0, i64 %t39
  %t41 = load i64, ptr %t40
  store i64 %t41, ptr %l3__t1
  br label %bb3
bb5_for_await_setup:
  %t42 = load i64, ptr %for_await_index_bb5
  %t43 = icmp eq i64 %t42, 0
  br i1 %t43, label %bb5_for_await_tuple_item_0, label %bb5_for_await_tuple_check_1
bb5_for_await_tuple_check_1:
  br label %bb5_for_await_tuple_item_1
bb5_for_await_tuple_item_0:
  %t44 = getelementptr inbounds { i64, i64 }, ptr %l6__t3, i32 0, i32 0
  %t45 = load i64, ptr %t44
  store i64 %t45, ptr %l7__t4
  br label %bb6
bb5_for_await_tuple_item_1:
  %t46 = getelementptr inbounds { i64, i64 }, ptr %l6__t3, i32 0, i32 1
  %t47 = load i64, ptr %t46
  store i64 %t47, ptr %l7__t4
  br label %bb6
bb8_for_await_setup:
  %t48 = load i64, ptr %for_await_index_bb8
  %t49 = getelementptr inbounds { [2 x i64] }, ptr %l11__t7, i32 0, i32 0
  %t50 = getelementptr inbounds [2 x i64], ptr %t49, i64 0, i64 %t48
  %t51 = load i64, ptr %t50
  store i64 %t51, ptr %l12__t8
  br label %bb9
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_4_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
