; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'integer_dynamic_guard_match'
source_filename = "integer_dynamic_guard_match.ql"
target triple = "x86_64-pc-windows-msvc"

define i64 @ql_0_choose(i64 %arg0, i1 %arg1) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %l2_enabled = alloca i1
  %l3__t0 = alloca i64
  %l4__t1 = alloca i64
  store i64 %arg0, ptr %l1_value
  store i1 %arg1, ptr %l2_enabled
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  store i64 %t0, ptr %l4__t1
  %t1 = load i64, ptr %l4__t1
  %t2 = icmp eq i64 %t1, 1
  br i1 %t2, label %bb0_match_guard0, label %bb0_match_dispatch1
bb0_match_guard0:
  %t3 = load i1, ptr %l2_enabled
  br i1 %t3, label %bb3, label %bb0_match_dispatch1
bb0_match_dispatch1:
  %t4 = icmp eq i64 %t1, 2
  br i1 %t4, label %bb4, label %bb5
bb1:
  %t5 = load i64, ptr %l0__return
  ret i64 %t5
bb2:
  %t6 = load i64, ptr %l3__t0
  store i64 %t6, ptr %l0__return
  br label %bb1
bb3:
  store i64 10, ptr %l3__t0
  br label %bb2
bb4:
  store i64 20, ptr %l3__t0
  br label %bb2
bb5:
  store i64 0, ptr %l3__t0
  br label %bb2
}

define i64 @ql_1_main() {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca i64
  br label %bb0
bb0:
  %t0 = call i64 @ql_0_choose(i64 1, i1 false)
  store i64 %t0, ptr %l1__t0
  %t1 = load i64, ptr %l1__t0
  store i64 %t1, ptr %l0__return
  br label %bb1
bb1:
  %t2 = load i64, ptr %l0__return
  ret i64 %t2
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_1_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
