; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'match_guard_alias_backed_nested_call_root_combos'
source_filename = "match_guard_alias_backed_nested_call_root_combos.ql"
target triple = "x86_64-pc-windows-msvc"

define { i1 } @ql_1_state(i1 %arg0) {
entry:
  %l0__return = alloca { i1 }
  %l1_flag = alloca i1
  %l2__t0 = alloca { i1 }
  store i1 %arg0, ptr %l1_flag
  br label %bb0
bb0:
  %t0 = load i1, ptr %l1_flag
  %t1 = insertvalue { i1 } undef, i1 %t0, 0
  store { i1 } %t1, ptr %l2__t0
  %t2 = load { i1 }, ptr %l2__t0
  store { i1 } %t2, ptr %l0__return
  br label %bb1
bb1:
  %t3 = load { i1 }, ptr %l0__return
  ret { i1 } %t3
}

define [3 x i64] @ql_2_bundle(i64 %arg0) {
entry:
  %l0__return = alloca [3 x i64]
  %l1_seed = alloca i64
  %l2__t0 = alloca i64
  %l3__t1 = alloca i64
  %l4__t2 = alloca [3 x i64]
  store i64 %arg0, ptr %l1_seed
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_seed
  %t1 = add i64 %t0, 1
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l1_seed
  %t3 = add i64 %t2, 2
  store i64 %t3, ptr %l3__t1
  %t4 = load i64, ptr %l1_seed
  %t5 = load i64, ptr %l2__t0
  %t6 = load i64, ptr %l3__t1
  %t7 = insertvalue [3 x i64] undef, i64 %t4, 0
  %t8 = insertvalue [3 x i64] %t7, i64 %t5, 1
  %t9 = insertvalue [3 x i64] %t8, i64 %t6, 2
  store [3 x i64] %t9, ptr %l4__t2
  %t10 = load [3 x i64], ptr %l4__t2
  store [3 x i64] %t10, ptr %l0__return
  br label %bb1
bb1:
  %t11 = load [3 x i64], ptr %l0__return
  ret [3 x i64] %t11
}

define i64 @ql_3_offset(i64 %arg0) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %l2__t0 = alloca i64
  store i64 %arg0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  %t1 = sub i64 %t0, 2
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l2__t0
  store i64 %t2, ptr %l0__return
  br label %bb1
bb1:
  %t3 = load i64, ptr %l0__return
  ret i64 %t3
}

define i1 @ql_4_ready(i1 %arg0) {
entry:
  %l0__return = alloca i1
  %l1_flag = alloca i1
  store i1 %arg0, ptr %l1_flag
  br label %bb0
bb0:
  %t0 = load i1, ptr %l1_flag
  store i1 %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load i1, ptr %l0__return
  ret i1 %t1
}

define i1 @ql_5_enabled({ i1 } %arg0, i1 %arg1) {
entry:
  %l0__return = alloca i1
  %l1_state = alloca { i1 }
  %l2_extra = alloca i1
  %l3__t0 = alloca i1
  store { i1 } %arg0, ptr %l1_state
  store i1 %arg1, ptr %l2_extra
  br label %bb0
bb0:
  %t0 = getelementptr inbounds { i1 }, ptr %l1_state, i32 0, i32 0
  %t1 = load i1, ptr %t0
  br i1 %t1, label %bb3, label %bb4
bb1:
  %t2 = load i1, ptr %l0__return
  ret i1 %t2
bb2:
  %t3 = load i1, ptr %l3__t0
  store i1 %t3, ptr %l0__return
  br label %bb1
bb3:
  %t4 = load i1, ptr %l2_extra
  store i1 %t4, ptr %l3__t0
  br label %bb2
bb4:
  store i1 false, ptr %l3__t0
  br label %bb2
}

define i1 @ql_6_matches(i64 %arg0, i64 %arg1) {
entry:
  %l0__return = alloca i1
  %l1_value = alloca i64
  %l2_expected = alloca i64
  %l3__t0 = alloca i1
  store i64 %arg0, ptr %l1_value
  store i64 %arg1, ptr %l2_expected
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  %t1 = load i64, ptr %l2_expected
  %t2 = icmp eq i64 %t0, %t1
  store i1 %t2, ptr %l3__t0
  %t3 = load i1, ptr %l3__t0
  store i1 %t3, ptr %l0__return
  br label %bb1
bb1:
  %t4 = load i1, ptr %l0__return
  ret i1 %t4
}

define i64 @ql_7_seed(i64 %arg0) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  store i64 %arg0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  store i64 %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load i64, ptr %l0__return
  ret i64 %t1
}

define i64 @ql_8_main() {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca i64
  %l2__t1 = alloca i1
  %l3_first = alloca i64
  %l4__t2 = alloca i64
  %l5__t3 = alloca i64
  %l6_current = alloca i64
  %l7_second = alloca i64
  %l8__t4 = alloca i64
  %l9__t5 = alloca i64
  %l10_current = alloca i64
  %l11_third = alloca i64
  %l12__t6 = alloca i64
  %l13__t7 = alloca i64
  br label %bb0
bb0:
  store i1 true, ptr %l2__t1
  %t0 = load i1, ptr %l2__t1
  br i1 %t0, label %bb0_match_guard0, label %bb0_match_dispatch1
bb0_match_guard0:
  %t1 = call [3 x i64] @ql_2_bundle(i64 3)
  %t2 = alloca [3 x i64]
  store [3 x i64] %t1, ptr %t2
  %t3 = call i64 @ql_3_offset(i64 3)
  %t4 = getelementptr inbounds [3 x i64], ptr %t2, i64 0, i64 %t3
  %t5 = load i64, ptr %t4
  %t6 = call i64 @ql_7_seed(i64 4)
  %t7 = icmp eq i64 %t5, %t6
  %t8 = call i1 @ql_4_ready(i1 %t7)
  %t9 = call { i1 } @ql_1_state(i1 %t8)
  %t10 = alloca { i1 }
  store { i1 } %t9, ptr %t10
  %t11 = load { i1 }, ptr %t10
  %t12 = call [3 x i64] @ql_2_bundle(i64 3)
  %t13 = alloca [3 x i64]
  store [3 x i64] %t12, ptr %t13
  %t14 = call i64 @ql_3_offset(i64 3)
  %t15 = getelementptr inbounds [3 x i64], ptr %t13, i64 0, i64 %t14
  %t16 = load i64, ptr %t15
  %t17 = call i64 @ql_7_seed(i64 4)
  %t18 = icmp eq i64 %t16, %t17
  %t19 = call i1 @ql_4_ready(i1 %t18)
  %t20 = call i1 @ql_5_enabled({ i1 } %t11, i1 %t19)
  br i1 %t20, label %bb3, label %bb0_match_dispatch1
bb0_match_dispatch1:
  br i1 %t0, label %bb2, label %bb4
bb1:
  %t21 = load i64, ptr %l0__return
  ret i64 %t21
bb2:
  %t22 = load i64, ptr %l1__t0
  store i64 %t22, ptr %l3_first
  store i64 3, ptr %l5__t3
  %t23 = load i64, ptr %l5__t3
  br label %bb2_match_guard0
bb2_match_guard0:
  store i64 %t23, ptr %l6_current
  %t24 = call [3 x i64] @ql_2_bundle(i64 %t23)
  %t25 = alloca [3 x i64]
  store [3 x i64] %t24, ptr %t25
  %t26 = call i64 @ql_3_offset(i64 %t23)
  %t27 = getelementptr inbounds [3 x i64], ptr %t25, i64 0, i64 %t26
  %t28 = load i64, ptr %t27
  %t29 = call i64 @ql_7_seed(i64 8)
  %t30 = call i64 @ql_7_seed(i64 9)
  %t31 = insertvalue [3 x i64] undef, i64 %t28, 0
  %t32 = insertvalue [3 x i64] %t31, i64 %t29, 1
  %t33 = insertvalue [3 x i64] %t32, i64 %t30, 2
  %t34 = alloca [3 x i64]
  store [3 x i64] %t33, ptr %t34
  %t35 = getelementptr inbounds [3 x i64], ptr %t34, i64 0, i64 0
  %t36 = load i64, ptr %t35
  %t37 = call i64 @ql_7_seed(i64 4)
  %t38 = icmp eq i64 %t36, %t37
  br i1 %t38, label %bb6, label %bb7
bb3:
  store i64 10, ptr %l1__t0
  br label %bb2
bb4:
  store i64 0, ptr %l1__t0
  br label %bb2
bb5:
  %t39 = load i64, ptr %l4__t2
  store i64 %t39, ptr %l7_second
  store i64 3, ptr %l9__t5
  %t40 = load i64, ptr %l9__t5
  br label %bb5_match_guard0
bb5_match_guard0:
  store i64 %t40, ptr %l10_current
  %t41 = call [3 x i64] @ql_2_bundle(i64 %t40)
  %t42 = alloca [3 x i64]
  store [3 x i64] %t41, ptr %t42
  %t43 = call i64 @ql_3_offset(i64 %t40)
  %t44 = getelementptr inbounds [3 x i64], ptr %t42, i64 0, i64 %t43
  %t45 = load i64, ptr %t44
  %t46 = call i64 @ql_7_seed(i64 8)
  %t47 = insertvalue [3 x i64] undef, i64 %t45, 0
  %t48 = insertvalue [3 x i64] %t47, i64 %t46, 1
  %t49 = insertvalue [3 x i64] %t48, i64 9, 2
  %t50 = alloca [3 x i64]
  store [3 x i64] %t49, ptr %t50
  %t51 = getelementptr inbounds [3 x i64], ptr %t50, i64 0, i64 0
  %t52 = load i64, ptr %t51
  %t53 = call i64 @ql_7_seed(i64 4)
  %t54 = call i1 @ql_6_matches(i64 %t52, i64 %t53)
  br i1 %t54, label %bb9, label %bb10
bb6:
  %t55 = load i64, ptr %l5__t3
  store i64 %t55, ptr %l6_current
  store i64 12, ptr %l4__t2
  br label %bb5
bb7:
  store i64 0, ptr %l4__t2
  br label %bb5
bb8:
  %t56 = load i64, ptr %l8__t4
  store i64 %t56, ptr %l11_third
  %t57 = load i64, ptr %l3_first
  %t58 = load i64, ptr %l7_second
  %t59 = add i64 %t57, %t58
  store i64 %t59, ptr %l12__t6
  %t60 = load i64, ptr %l12__t6
  %t61 = load i64, ptr %l11_third
  %t62 = add i64 %t60, %t61
  store i64 %t62, ptr %l13__t7
  %t63 = load i64, ptr %l13__t7
  store i64 %t63, ptr %l0__return
  br label %bb1
bb9:
  %t64 = load i64, ptr %l9__t5
  store i64 %t64, ptr %l10_current
  store i64 20, ptr %l8__t4
  br label %bb8
bb10:
  store i64 0, ptr %l8__t4
  br label %bb8
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_8_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
