; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'match_guard_projection_backed_nested_call_root_combos'
source_filename = "match_guard_projection_backed_nested_call_root_combos.ql"
target triple = "x86_64-pc-windows-msvc"

define { i1 } @ql_3_state(i1 %arg0) {
entry:
  %l0__return = alloca { i1 }
  %l1_flag = alloca i1
  %l2__t0 = alloca { i1 }
  store i1 %arg0, ptr %l1_flag
  br label %bb0
bb0:
  %t0 = load i1, ptr %l1_flag
  %t1 = insertvalue { i1 } undef, i1 %t0, 0
  store { i1 } %t1, ptr %l2__t0
  %t2 = load { i1 }, ptr %l2__t0
  store { i1 } %t2, ptr %l0__return
  br label %bb1
bb1:
  %t3 = load { i1 }, ptr %l0__return
  ret { i1 } %t3
}

define [3 x i64] @ql_4_bundle(i64 %arg0) {
entry:
  %l0__return = alloca [3 x i64]
  %l1_seed = alloca i64
  %l2__t0 = alloca i64
  %l3__t1 = alloca i64
  %l4__t2 = alloca [3 x i64]
  store i64 %arg0, ptr %l1_seed
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_seed
  %t1 = add i64 %t0, 1
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l1_seed
  %t3 = add i64 %t2, 2
  store i64 %t3, ptr %l3__t1
  %t4 = load i64, ptr %l1_seed
  %t5 = load i64, ptr %l2__t0
  %t6 = load i64, ptr %l3__t1
  %t7 = insertvalue [3 x i64] undef, i64 %t4, 0
  %t8 = insertvalue [3 x i64] %t7, i64 %t5, 1
  %t9 = insertvalue [3 x i64] %t8, i64 %t6, 2
  store [3 x i64] %t9, ptr %l4__t2
  %t10 = load [3 x i64], ptr %l4__t2
  store [3 x i64] %t10, ptr %l0__return
  br label %bb1
bb1:
  %t11 = load [3 x i64], ptr %l0__return
  ret [3 x i64] %t11
}

define i64 @ql_5_offset(i64 %arg0) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %l2__t0 = alloca i64
  store i64 %arg0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  %t1 = sub i64 %t0, 2
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l2__t0
  store i64 %t2, ptr %l0__return
  br label %bb1
bb1:
  %t3 = load i64, ptr %l0__return
  ret i64 %t3
}

define i1 @ql_6_enabled({ i1 } %arg0, i1 %arg1) {
entry:
  %l0__return = alloca i1
  %l1_state = alloca { i1 }
  %l2_extra = alloca i1
  %l3__t0 = alloca i1
  store { i1 } %arg0, ptr %l1_state
  store i1 %arg1, ptr %l2_extra
  br label %bb0
bb0:
  %t0 = getelementptr inbounds { i1 }, ptr %l1_state, i32 0, i32 0
  %t1 = load i1, ptr %t0
  br i1 %t1, label %bb3, label %bb4
bb1:
  %t2 = load i1, ptr %l0__return
  ret i1 %t2
bb2:
  %t3 = load i1, ptr %l3__t0
  store i1 %t3, ptr %l0__return
  br label %bb1
bb3:
  %t4 = load i1, ptr %l2_extra
  store i1 %t4, ptr %l3__t0
  br label %bb2
bb4:
  store i1 false, ptr %l3__t0
  br label %bb2
}

define i1 @ql_7_matches(i64 %arg0, i64 %arg1) {
entry:
  %l0__return = alloca i1
  %l1_value = alloca i64
  %l2_expected = alloca i64
  %l3__t0 = alloca i1
  store i64 %arg0, ptr %l1_value
  store i64 %arg1, ptr %l2_expected
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  %t1 = load i64, ptr %l2_expected
  %t2 = icmp eq i64 %t0, %t1
  store i1 %t2, ptr %l3__t0
  %t3 = load i1, ptr %l3__t0
  store i1 %t3, ptr %l0__return
  br label %bb1
bb1:
  %t4 = load i1, ptr %l0__return
  ret i1 %t4
}

define i64 @ql_8_main() {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca { i64 }
  %l2__t1 = alloca { { i64 } }
  %l3_config = alloca { { i64 } }
  %l4__t2 = alloca i64
  %l5__t3 = alloca i1
  %l6_first = alloca i64
  %l7__t4 = alloca i64
  %l8__t5 = alloca i64
  %l9_current = alloca i64
  %l10_second = alloca i64
  %l11__t6 = alloca i64
  %l12__t7 = alloca i64
  %l13_current = alloca i64
  %l14_third = alloca i64
  %l15__t8 = alloca i64
  %l16__t9 = alloca i64
  br label %bb0
bb0:
  %t0 = insertvalue { i64 } undef, i64 3, 0
  store { i64 } %t0, ptr %l1__t0
  %t1 = load { i64 }, ptr %l1__t0
  %t2 = insertvalue { { i64 } } undef, { i64 } %t1, 0
  store { { i64 } } %t2, ptr %l2__t1
  %t3 = load { { i64 } }, ptr %l2__t1
  store { { i64 } } %t3, ptr %l3_config
  store i1 true, ptr %l5__t3
  %t4 = load i1, ptr %l5__t3
  br i1 %t4, label %bb0_match_guard0, label %bb0_match_dispatch1
bb0_match_guard0:
  %t5 = getelementptr inbounds { { i64 } }, ptr %l3_config, i32 0, i32 0
  %t6 = getelementptr inbounds { i64 }, ptr %t5, i32 0, i32 0
  %t7 = load i64, ptr %t6
  %t8 = call [3 x i64] @ql_4_bundle(i64 %t7)
  %t9 = alloca [3 x i64]
  store [3 x i64] %t8, ptr %t9
  %t10 = getelementptr inbounds { { i64 } }, ptr %l3_config, i32 0, i32 0
  %t11 = getelementptr inbounds { i64 }, ptr %t10, i32 0, i32 0
  %t12 = load i64, ptr %t11
  %t13 = call i64 @ql_5_offset(i64 %t12)
  %t14 = getelementptr inbounds [3 x i64], ptr %t9, i64 0, i64 %t13
  %t15 = load i64, ptr %t14
  %t16 = icmp eq i64 %t15, 4
  %t17 = call { i1 } @ql_3_state(i1 %t16)
  %t18 = alloca { i1 }
  store { i1 } %t17, ptr %t18
  %t19 = load { i1 }, ptr %t18
  %t20 = getelementptr inbounds { { i64 } }, ptr %l3_config, i32 0, i32 0
  %t21 = getelementptr inbounds { i64 }, ptr %t20, i32 0, i32 0
  %t22 = load i64, ptr %t21
  %t23 = call [3 x i64] @ql_4_bundle(i64 %t22)
  %t24 = alloca [3 x i64]
  store [3 x i64] %t23, ptr %t24
  %t25 = getelementptr inbounds { { i64 } }, ptr %l3_config, i32 0, i32 0
  %t26 = getelementptr inbounds { i64 }, ptr %t25, i32 0, i32 0
  %t27 = load i64, ptr %t26
  %t28 = call i64 @ql_5_offset(i64 %t27)
  %t29 = getelementptr inbounds [3 x i64], ptr %t24, i64 0, i64 %t28
  %t30 = load i64, ptr %t29
  %t31 = icmp eq i64 %t30, 4
  %t32 = call i1 @ql_6_enabled({ i1 } %t19, i1 %t31)
  br i1 %t32, label %bb3, label %bb0_match_dispatch1
bb0_match_dispatch1:
  br i1 %t4, label %bb2, label %bb4
bb1:
  %t33 = load i64, ptr %l0__return
  ret i64 %t33
bb2:
  %t34 = load i64, ptr %l4__t2
  store i64 %t34, ptr %l6_first
  store i64 3, ptr %l8__t5
  %t35 = load i64, ptr %l8__t5
  br label %bb2_match_guard0
bb2_match_guard0:
  store i64 %t35, ptr %l9_current
  %t36 = getelementptr inbounds { { i64 } }, ptr %l3_config, i32 0, i32 0
  %t37 = getelementptr inbounds { i64 }, ptr %t36, i32 0, i32 0
  %t38 = load i64, ptr %t37
  %t39 = call [3 x i64] @ql_4_bundle(i64 %t38)
  %t40 = alloca [3 x i64]
  store [3 x i64] %t39, ptr %t40
  %t41 = getelementptr inbounds { { i64 } }, ptr %l3_config, i32 0, i32 0
  %t42 = getelementptr inbounds { i64 }, ptr %t41, i32 0, i32 0
  %t43 = load i64, ptr %t42
  %t44 = call i64 @ql_5_offset(i64 %t43)
  %t45 = getelementptr inbounds [3 x i64], ptr %t40, i64 0, i64 %t44
  %t46 = load i64, ptr %t45
  %t47 = add i64 %t35, 5
  %t48 = insertvalue [3 x i64] undef, i64 %t46, 0
  %t49 = insertvalue [3 x i64] %t48, i64 %t47, 1
  %t50 = insertvalue [3 x i64] %t49, i64 9, 2
  %t51 = alloca [3 x i64]
  store [3 x i64] %t50, ptr %t51
  %t52 = getelementptr inbounds [3 x i64], ptr %t51, i64 0, i64 0
  %t53 = load i64, ptr %t52
  %t54 = icmp eq i64 %t53, 4
  br i1 %t54, label %bb6, label %bb7
bb3:
  store i64 10, ptr %l4__t2
  br label %bb2
bb4:
  store i64 0, ptr %l4__t2
  br label %bb2
bb5:
  %t55 = load i64, ptr %l7__t4
  store i64 %t55, ptr %l10_second
  store i64 3, ptr %l12__t7
  %t56 = load i64, ptr %l12__t7
  br label %bb5_match_guard0
bb5_match_guard0:
  store i64 %t56, ptr %l13_current
  %t57 = getelementptr inbounds { { i64 } }, ptr %l3_config, i32 0, i32 0
  %t58 = getelementptr inbounds { i64 }, ptr %t57, i32 0, i32 0
  %t59 = load i64, ptr %t58
  %t60 = call [3 x i64] @ql_4_bundle(i64 %t59)
  %t61 = alloca [3 x i64]
  store [3 x i64] %t60, ptr %t61
  %t62 = getelementptr inbounds { { i64 } }, ptr %l3_config, i32 0, i32 0
  %t63 = getelementptr inbounds { i64 }, ptr %t62, i32 0, i32 0
  %t64 = load i64, ptr %t63
  %t65 = call i64 @ql_5_offset(i64 %t64)
  %t66 = getelementptr inbounds [3 x i64], ptr %t61, i64 0, i64 %t65
  %t67 = load i64, ptr %t66
  %t68 = insertvalue [3 x i64] undef, i64 %t67, 0
  %t69 = insertvalue [3 x i64] %t68, i64 %t56, 1
  %t70 = insertvalue [3 x i64] %t69, i64 9, 2
  %t71 = alloca [3 x i64]
  store [3 x i64] %t70, ptr %t71
  %t72 = getelementptr inbounds [3 x i64], ptr %t71, i64 0, i64 0
  %t73 = load i64, ptr %t72
  %t74 = call i1 @ql_7_matches(i64 %t73, i64 4)
  br i1 %t74, label %bb9, label %bb10
bb6:
  %t75 = load i64, ptr %l8__t5
  store i64 %t75, ptr %l9_current
  store i64 12, ptr %l7__t4
  br label %bb5
bb7:
  store i64 0, ptr %l7__t4
  br label %bb5
bb8:
  %t76 = load i64, ptr %l11__t6
  store i64 %t76, ptr %l14_third
  %t77 = load i64, ptr %l6_first
  %t78 = load i64, ptr %l10_second
  %t79 = add i64 %t77, %t78
  store i64 %t79, ptr %l15__t8
  %t80 = load i64, ptr %l15__t8
  %t81 = load i64, ptr %l14_third
  %t82 = add i64 %t80, %t81
  store i64 %t82, ptr %l16__t9
  %t83 = load i64, ptr %l16__t9
  store i64 %t83, ptr %l0__return
  br label %bb1
bb9:
  %t84 = load i64, ptr %l12__t7
  store i64 %t84, ptr %l13_current
  store i64 20, ptr %l11__t6
  br label %bb8
bb10:
  store i64 0, ptr %l11__t6
  br label %bb8
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_8_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
