; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'match_guard_call_backed_combos'
source_filename = "match_guard_call_backed_combos.ql"
target triple = "x86_64-pc-windows-msvc"

define i1 @ql_1_ready(i1 %arg0) {
entry:
  %l0__return = alloca i1
  %l1_flag = alloca i1
  store i1 %arg0, ptr %l1_flag
  br label %bb0
bb0:
  %t0 = load i1, ptr %l1_flag
  store i1 %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load i1, ptr %l0__return
  ret i1 %t1
}

define i1 @ql_2_enabled({ i1 } %arg0, i1 %arg1) {
entry:
  %l0__return = alloca i1
  %l1_state = alloca { i1 }
  %l2_extra = alloca i1
  %l3__t0 = alloca i1
  store { i1 } %arg0, ptr %l1_state
  store i1 %arg1, ptr %l2_extra
  br label %bb0
bb0:
  %t0 = getelementptr inbounds { i1 }, ptr %l1_state, i32 0, i32 0
  %t1 = load i1, ptr %t0
  br i1 %t1, label %bb3, label %bb4
bb1:
  %t2 = load i1, ptr %l0__return
  ret i1 %t2
bb2:
  %t3 = load i1, ptr %l3__t0
  store i1 %t3, ptr %l0__return
  br label %bb1
bb3:
  %t4 = load i1, ptr %l2_extra
  store i1 %t4, ptr %l3__t0
  br label %bb2
bb4:
  store i1 false, ptr %l3__t0
  br label %bb2
}

define i64 @ql_3_seed(i64 %arg0) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  store i64 %arg0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  store i64 %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load i64, ptr %l0__return
  ret i64 %t1
}

define i1 @ql_4_matches({ i64, i64 } %arg0, i64 %arg1) {
entry:
  %l0__return = alloca i1
  %l1_pair = alloca { i64, i64 }
  %l2_expected = alloca i64
  %l3__t0 = alloca i1
  store { i64, i64 } %arg0, ptr %l1_pair
  store i64 %arg1, ptr %l2_expected
  br label %bb0
bb0:
  %t0 = getelementptr inbounds { i64, i64 }, ptr %l1_pair, i32 0, i32 1
  %t1 = load i64, ptr %t0
  %t2 = load i64, ptr %l2_expected
  %t3 = icmp eq i64 %t1, %t2
  store i1 %t3, ptr %l3__t0
  %t4 = load i1, ptr %l3__t0
  store i1 %t4, ptr %l0__return
  br label %bb1
bb1:
  %t5 = load i1, ptr %l0__return
  ret i1 %t5
}

define [3 x i64] @ql_5_values(i64 %arg0) {
entry:
  %l0__return = alloca [3 x i64]
  %l1_seed = alloca i64
  %l2__t0 = alloca i64
  %l3__t1 = alloca i64
  %l4__t2 = alloca [3 x i64]
  store i64 %arg0, ptr %l1_seed
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_seed
  %t1 = add i64 %t0, 1
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l1_seed
  %t3 = add i64 %t2, 2
  store i64 %t3, ptr %l3__t1
  %t4 = load i64, ptr %l1_seed
  %t5 = load i64, ptr %l2__t0
  %t6 = load i64, ptr %l3__t1
  %t7 = insertvalue [3 x i64] undef, i64 %t4, 0
  %t8 = insertvalue [3 x i64] %t7, i64 %t5, 1
  %t9 = insertvalue [3 x i64] %t8, i64 %t6, 2
  store [3 x i64] %t9, ptr %l4__t2
  %t10 = load [3 x i64], ptr %l4__t2
  store [3 x i64] %t10, ptr %l0__return
  br label %bb1
bb1:
  %t11 = load [3 x i64], ptr %l0__return
  ret [3 x i64] %t11
}

define i64 @ql_6_offset(i64 %arg0) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %l2__t0 = alloca i64
  store i64 %arg0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  %t1 = sub i64 %t0, 2
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l2__t0
  store i64 %t2, ptr %l0__return
  br label %bb1
bb1:
  %t3 = load i64, ptr %l0__return
  ret i64 %t3
}

define i64 @ql_7_main() {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca i64
  %l2__t1 = alloca i1
  %l3_first = alloca i64
  %l4__t2 = alloca i64
  %l5__t3 = alloca i64
  %l6_current = alloca i64
  %l7_second = alloca i64
  %l8__t4 = alloca i64
  %l9__t5 = alloca i64
  %l10_current = alloca i64
  %l11_third = alloca i64
  %l12__t6 = alloca i64
  %l13__t7 = alloca i64
  br label %bb0
bb0:
  store i1 true, ptr %l2__t1
  %t0 = load i1, ptr %l2__t1
  br i1 %t0, label %bb0_match_guard0, label %bb0_match_dispatch1
bb0_match_guard0:
  %t1 = call i1 @ql_1_ready(i1 true)
  %t2 = insertvalue { i1 } undef, i1 %t1, 0
  %t3 = call i1 @ql_1_ready(i1 true)
  %t4 = call i1 @ql_2_enabled({ i1 } %t2, i1 %t3)
  br i1 %t4, label %bb3, label %bb0_match_dispatch1
bb0_match_dispatch1:
  br i1 %t0, label %bb2, label %bb4
bb1:
  %t5 = load i64, ptr %l0__return
  ret i64 %t5
bb2:
  %t6 = load i64, ptr %l1__t0
  store i64 %t6, ptr %l3_first
  store i64 22, ptr %l5__t3
  %t7 = load i64, ptr %l5__t3
  br label %bb2_match_guard0
bb2_match_guard0:
  store i64 %t7, ptr %l6_current
  %t8 = call i64 @ql_3_seed(i64 0)
  %t9 = insertvalue { i64, i64 } undef, i64 %t8, 0
  %t10 = insertvalue { i64, i64 } %t9, i64 %t7, 1
  %t11 = call i1 @ql_4_matches({ i64, i64 } %t10, i64 22)
  br i1 %t11, label %bb6, label %bb7
bb3:
  store i64 10, ptr %l1__t0
  br label %bb2
bb4:
  store i64 0, ptr %l1__t0
  br label %bb2
bb5:
  %t12 = load i64, ptr %l4__t2
  store i64 %t12, ptr %l7_second
  store i64 3, ptr %l9__t5
  %t13 = load i64, ptr %l9__t5
  br label %bb5_match_guard0
bb5_match_guard0:
  store i64 %t13, ptr %l10_current
  %t14 = call [3 x i64] @ql_5_values(i64 %t13)
  %t15 = alloca [3 x i64]
  store [3 x i64] %t14, ptr %t15
  %t16 = call i64 @ql_6_offset(i64 %t13)
  %t17 = getelementptr inbounds [3 x i64], ptr %t15, i64 0, i64 %t16
  %t18 = load i64, ptr %t17
  %t19 = icmp eq i64 %t18, 4
  br i1 %t19, label %bb9, label %bb10
bb6:
  %t20 = load i64, ptr %l5__t3
  store i64 %t20, ptr %l6_current
  store i64 12, ptr %l4__t2
  br label %bb5
bb7:
  store i64 0, ptr %l4__t2
  br label %bb5
bb8:
  %t21 = load i64, ptr %l8__t4
  store i64 %t21, ptr %l11_third
  %t22 = load i64, ptr %l3_first
  %t23 = load i64, ptr %l7_second
  %t24 = add i64 %t22, %t23
  store i64 %t24, ptr %l12__t6
  %t25 = load i64, ptr %l12__t6
  %t26 = load i64, ptr %l11_third
  %t27 = add i64 %t25, %t26
  store i64 %t27, ptr %l13__t7
  %t28 = load i64, ptr %l13__t7
  store i64 %t28, ptr %l0__return
  br label %bb1
bb9:
  %t29 = load i64, ptr %l9__t5
  store i64 %t29, ptr %l10_current
  store i64 20, ptr %l8__t4
  br label %bb8
bb10:
  store i64 0, ptr %l8__t4
  br label %bb8
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_7_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
