; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'match_guard_item_backed_nested_call_root_combos'
source_filename = "match_guard_item_backed_nested_call_root_combos.ql"
target triple = "x86_64-pc-windows-msvc"

define { i1 } @ql_2_state(i1 %arg0) {
entry:
  %l0__return = alloca { i1 }
  %l1_flag = alloca i1
  %l2__t0 = alloca { i1 }
  store i1 %arg0, ptr %l1_flag
  br label %bb0
bb0:
  %t0 = load i1, ptr %l1_flag
  %t1 = insertvalue { i1 } undef, i1 %t0, 0
  store { i1 } %t1, ptr %l2__t0
  %t2 = load { i1 }, ptr %l2__t0
  store { i1 } %t2, ptr %l0__return
  br label %bb1
bb1:
  %t3 = load { i1 }, ptr %l0__return
  ret { i1 } %t3
}

define [3 x i64] @ql_3_bundle(i64 %arg0) {
entry:
  %l0__return = alloca [3 x i64]
  %l1_seed = alloca i64
  %l2__t0 = alloca i64
  %l3__t1 = alloca i64
  %l4__t2 = alloca [3 x i64]
  store i64 %arg0, ptr %l1_seed
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_seed
  %t1 = add i64 %t0, 1
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l1_seed
  %t3 = add i64 %t2, 2
  store i64 %t3, ptr %l3__t1
  %t4 = load i64, ptr %l1_seed
  %t5 = load i64, ptr %l2__t0
  %t6 = load i64, ptr %l3__t1
  %t7 = insertvalue [3 x i64] undef, i64 %t4, 0
  %t8 = insertvalue [3 x i64] %t7, i64 %t5, 1
  %t9 = insertvalue [3 x i64] %t8, i64 %t6, 2
  store [3 x i64] %t9, ptr %l4__t2
  %t10 = load [3 x i64], ptr %l4__t2
  store [3 x i64] %t10, ptr %l0__return
  br label %bb1
bb1:
  %t11 = load [3 x i64], ptr %l0__return
  ret [3 x i64] %t11
}

define i64 @ql_4_offset(i64 %arg0) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %l2__t0 = alloca i64
  store i64 %arg0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  %t1 = sub i64 %t0, 2
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l2__t0
  store i64 %t2, ptr %l0__return
  br label %bb1
bb1:
  %t3 = load i64, ptr %l0__return
  ret i64 %t3
}

define i1 @ql_5_enabled({ i1 } %arg0, i1 %arg1) {
entry:
  %l0__return = alloca i1
  %l1_state = alloca { i1 }
  %l2_extra = alloca i1
  %l3__t0 = alloca i1
  store { i1 } %arg0, ptr %l1_state
  store i1 %arg1, ptr %l2_extra
  br label %bb0
bb0:
  %t0 = getelementptr inbounds { i1 }, ptr %l1_state, i32 0, i32 0
  %t1 = load i1, ptr %t0
  br i1 %t1, label %bb3, label %bb4
bb1:
  %t2 = load i1, ptr %l0__return
  ret i1 %t2
bb2:
  %t3 = load i1, ptr %l3__t0
  store i1 %t3, ptr %l0__return
  br label %bb1
bb3:
  %t4 = load i1, ptr %l2_extra
  store i1 %t4, ptr %l3__t0
  br label %bb2
bb4:
  store i1 false, ptr %l3__t0
  br label %bb2
}

define i1 @ql_6_matches(i64 %arg0, i64 %arg1) {
entry:
  %l0__return = alloca i1
  %l1_value = alloca i64
  %l2_expected = alloca i64
  %l3__t0 = alloca i1
  store i64 %arg0, ptr %l1_value
  store i64 %arg1, ptr %l2_expected
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  %t1 = load i64, ptr %l2_expected
  %t2 = icmp eq i64 %t0, %t1
  store i1 %t2, ptr %l3__t0
  %t3 = load i1, ptr %l3__t0
  store i1 %t3, ptr %l0__return
  br label %bb1
bb1:
  %t4 = load i1, ptr %l0__return
  ret i1 %t4
}

define i64 @ql_7_main() {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca i64
  %l2__t1 = alloca i1
  %l3_first = alloca i64
  %l4__t2 = alloca i64
  %l5__t3 = alloca i64
  %l6_current = alloca i64
  %l7_second = alloca i64
  %l8__t4 = alloca i64
  %l9__t5 = alloca i64
  %l10_current = alloca i64
  %l11_third = alloca i64
  %l12__t6 = alloca i64
  %l13__t7 = alloca i64
  br label %bb0
bb0:
  store i1 true, ptr %l2__t1
  %t0 = load i1, ptr %l2__t1
  br i1 %t0, label %bb0_match_guard0, label %bb0_match_dispatch1
bb0_match_guard0:
  %t1 = call [3 x i64] @ql_3_bundle(i64 3)
  %t2 = alloca [3 x i64]
  store [3 x i64] %t1, ptr %t2
  %t3 = call i64 @ql_4_offset(i64 3)
  %t4 = getelementptr inbounds [3 x i64], ptr %t2, i64 0, i64 %t3
  %t5 = load i64, ptr %t4
  %t6 = icmp eq i64 %t5, 4
  %t7 = call { i1 } @ql_2_state(i1 %t6)
  %t8 = alloca { i1 }
  store { i1 } %t7, ptr %t8
  %t9 = load { i1 }, ptr %t8
  %t10 = call [3 x i64] @ql_3_bundle(i64 3)
  %t11 = alloca [3 x i64]
  store [3 x i64] %t10, ptr %t11
  %t12 = call i64 @ql_4_offset(i64 3)
  %t13 = getelementptr inbounds [3 x i64], ptr %t11, i64 0, i64 %t12
  %t14 = load i64, ptr %t13
  %t15 = icmp eq i64 4, %t14
  %t16 = call i1 @ql_5_enabled({ i1 } %t9, i1 %t15)
  br i1 %t16, label %bb3, label %bb0_match_dispatch1
bb0_match_dispatch1:
  br i1 %t0, label %bb2, label %bb4
bb1:
  %t17 = load i64, ptr %l0__return
  ret i64 %t17
bb2:
  %t18 = load i64, ptr %l1__t0
  store i64 %t18, ptr %l3_first
  store i64 3, ptr %l5__t3
  %t19 = load i64, ptr %l5__t3
  br label %bb2_match_guard0
bb2_match_guard0:
  store i64 %t19, ptr %l6_current
  %t20 = call [3 x i64] @ql_3_bundle(i64 %t19)
  %t21 = alloca [3 x i64]
  store [3 x i64] %t20, ptr %t21
  %t22 = call i64 @ql_4_offset(i64 %t19)
  %t23 = getelementptr inbounds [3 x i64], ptr %t21, i64 0, i64 %t22
  %t24 = load i64, ptr %t23
  %t25 = insertvalue [3 x i64] undef, i64 %t24, 0
  %t26 = insertvalue [3 x i64] %t25, i64 8, 1
  %t27 = insertvalue [3 x i64] %t26, i64 9, 2
  %t28 = alloca [3 x i64]
  store [3 x i64] %t27, ptr %t28
  %t29 = getelementptr inbounds [3 x i64], ptr %t28, i64 0, i64 0
  %t30 = load i64, ptr %t29
  %t31 = icmp eq i64 %t30, 4
  br i1 %t31, label %bb6, label %bb7
bb3:
  store i64 10, ptr %l1__t0
  br label %bb2
bb4:
  store i64 0, ptr %l1__t0
  br label %bb2
bb5:
  %t32 = load i64, ptr %l4__t2
  store i64 %t32, ptr %l7_second
  store i64 3, ptr %l9__t5
  %t33 = load i64, ptr %l9__t5
  br label %bb5_match_guard0
bb5_match_guard0:
  store i64 %t33, ptr %l10_current
  %t34 = call [3 x i64] @ql_3_bundle(i64 %t33)
  %t35 = alloca [3 x i64]
  store [3 x i64] %t34, ptr %t35
  %t36 = call i64 @ql_4_offset(i64 %t33)
  %t37 = getelementptr inbounds [3 x i64], ptr %t35, i64 0, i64 %t36
  %t38 = load i64, ptr %t37
  %t39 = insertvalue [3 x i64] undef, i64 %t38, 0
  %t40 = insertvalue [3 x i64] %t39, i64 8, 1
  %t41 = insertvalue [3 x i64] %t40, i64 9, 2
  %t42 = alloca [3 x i64]
  store [3 x i64] %t41, ptr %t42
  %t43 = getelementptr inbounds [3 x i64], ptr %t42, i64 0, i64 0
  %t44 = load i64, ptr %t43
  %t45 = call i1 @ql_6_matches(i64 %t44, i64 4)
  br i1 %t45, label %bb9, label %bb10
bb6:
  %t46 = load i64, ptr %l5__t3
  store i64 %t46, ptr %l6_current
  store i64 12, ptr %l4__t2
  br label %bb5
bb7:
  store i64 0, ptr %l4__t2
  br label %bb5
bb8:
  %t47 = load i64, ptr %l8__t4
  store i64 %t47, ptr %l11_third
  %t48 = load i64, ptr %l3_first
  %t49 = load i64, ptr %l7_second
  %t50 = add i64 %t48, %t49
  store i64 %t50, ptr %l12__t6
  %t51 = load i64, ptr %l12__t6
  %t52 = load i64, ptr %l11_third
  %t53 = add i64 %t51, %t52
  store i64 %t53, ptr %l13__t7
  %t54 = load i64, ptr %l13__t7
  store i64 %t54, ptr %l0__return
  br label %bb1
bb9:
  %t55 = load i64, ptr %l9__t5
  store i64 %t55, ptr %l10_current
  store i64 20, ptr %l8__t4
  br label %bb8
bb10:
  store i64 0, ptr %l8__t4
  br label %bb8
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_7_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
