; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'match_guard_call_backed_nested_call_root_combos'
source_filename = "match_guard_call_backed_nested_call_root_combos.ql"
target triple = "x86_64-pc-windows-msvc"

define { i1 } @ql_1_state(i1 %arg0) {
entry:
  %l0__return = alloca { i1 }
  %l1_flag = alloca i1
  %l2__t0 = alloca { i1 }
  store i1 %arg0, ptr %l1_flag
  br label %bb0
bb0:
  %t0 = load i1, ptr %l1_flag
  %t1 = insertvalue { i1 } undef, i1 %t0, 0
  store { i1 } %t1, ptr %l2__t0
  %t2 = load { i1 }, ptr %l2__t0
  store { i1 } %t2, ptr %l0__return
  br label %bb1
bb1:
  %t3 = load { i1 }, ptr %l0__return
  ret { i1 } %t3
}

define [3 x i64] @ql_2_bundle(i64 %arg0) {
entry:
  %l0__return = alloca [3 x i64]
  %l1_seed = alloca i64
  %l2__t0 = alloca i64
  %l3__t1 = alloca i64
  %l4__t2 = alloca [3 x i64]
  store i64 %arg0, ptr %l1_seed
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_seed
  %t1 = add i64 %t0, 1
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l1_seed
  %t3 = add i64 %t2, 2
  store i64 %t3, ptr %l3__t1
  %t4 = load i64, ptr %l1_seed
  %t5 = load i64, ptr %l2__t0
  %t6 = load i64, ptr %l3__t1
  %t7 = insertvalue [3 x i64] undef, i64 %t4, 0
  %t8 = insertvalue [3 x i64] %t7, i64 %t5, 1
  %t9 = insertvalue [3 x i64] %t8, i64 %t6, 2
  store [3 x i64] %t9, ptr %l4__t2
  %t10 = load [3 x i64], ptr %l4__t2
  store [3 x i64] %t10, ptr %l0__return
  br label %bb1
bb1:
  %t11 = load [3 x i64], ptr %l0__return
  ret [3 x i64] %t11
}

define i64 @ql_3_offset(i64 %arg0) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %l2__t0 = alloca i64
  store i64 %arg0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  %t1 = sub i64 %t0, 2
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l2__t0
  store i64 %t2, ptr %l0__return
  br label %bb1
bb1:
  %t3 = load i64, ptr %l0__return
  ret i64 %t3
}

define i1 @ql_4_ready(i1 %arg0) {
entry:
  %l0__return = alloca i1
  %l1_flag = alloca i1
  store i1 %arg0, ptr %l1_flag
  br label %bb0
bb0:
  %t0 = load i1, ptr %l1_flag
  store i1 %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load i1, ptr %l0__return
  ret i1 %t1
}

define i64 @ql_5_seed(i64 %arg0) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  store i64 %arg0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  store i64 %t0, ptr %l0__return
  br label %bb1
bb1:
  %t1 = load i64, ptr %l0__return
  ret i64 %t1
}

define i1 @ql_6_enabled({ i1 } %arg0, i1 %arg1) {
entry:
  %l0__return = alloca i1
  %l1_state = alloca { i1 }
  %l2_extra = alloca i1
  %l3__t0 = alloca i1
  store { i1 } %arg0, ptr %l1_state
  store i1 %arg1, ptr %l2_extra
  br label %bb0
bb0:
  %t0 = getelementptr inbounds { i1 }, ptr %l1_state, i32 0, i32 0
  %t1 = load i1, ptr %t0
  br i1 %t1, label %bb3, label %bb4
bb1:
  %t2 = load i1, ptr %l0__return
  ret i1 %t2
bb2:
  %t3 = load i1, ptr %l3__t0
  store i1 %t3, ptr %l0__return
  br label %bb1
bb3:
  %t4 = load i1, ptr %l2_extra
  store i1 %t4, ptr %l3__t0
  br label %bb2
bb4:
  store i1 false, ptr %l3__t0
  br label %bb2
}

define i1 @ql_7_matches(i64 %arg0, i64 %arg1) {
entry:
  %l0__return = alloca i1
  %l1_value = alloca i64
  %l2_expected = alloca i64
  %l3__t0 = alloca i1
  store i64 %arg0, ptr %l1_value
  store i64 %arg1, ptr %l2_expected
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  %t1 = load i64, ptr %l2_expected
  %t2 = icmp eq i64 %t0, %t1
  store i1 %t2, ptr %l3__t0
  %t3 = load i1, ptr %l3__t0
  store i1 %t3, ptr %l0__return
  br label %bb1
bb1:
  %t4 = load i1, ptr %l0__return
  ret i1 %t4
}

define i64 @ql_8_main() {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca i64
  %l2__t1 = alloca i1
  %l3_first = alloca i64
  %l4__t2 = alloca i64
  %l5__t3 = alloca i64
  %l6_current = alloca i64
  %l7_second = alloca i64
  %l8__t4 = alloca i64
  %l9__t5 = alloca i64
  %l10_current = alloca i64
  %l11_third = alloca i64
  %l12__t6 = alloca i64
  %l13__t7 = alloca i64
  br label %bb0
bb0:
  store i1 true, ptr %l2__t1
  %t0 = load i1, ptr %l2__t1
  br i1 %t0, label %bb0_match_guard0, label %bb0_match_dispatch1
bb0_match_guard0:
  %t1 = call [3 x i64] @ql_2_bundle(i64 3)
  %t2 = alloca [3 x i64]
  store [3 x i64] %t1, ptr %t2
  %t3 = call i64 @ql_3_offset(i64 3)
  %t4 = getelementptr inbounds [3 x i64], ptr %t2, i64 0, i64 %t3
  %t5 = load i64, ptr %t4
  %t6 = icmp eq i64 %t5, 4
  %t7 = call i1 @ql_4_ready(i1 %t6)
  %t8 = call { i1 } @ql_1_state(i1 %t7)
  %t9 = alloca { i1 }
  store { i1 } %t8, ptr %t9
  %t10 = load { i1 }, ptr %t9
  %t11 = call [3 x i64] @ql_2_bundle(i64 3)
  %t12 = alloca [3 x i64]
  store [3 x i64] %t11, ptr %t12
  %t13 = call i64 @ql_3_offset(i64 3)
  %t14 = getelementptr inbounds [3 x i64], ptr %t12, i64 0, i64 %t13
  %t15 = load i64, ptr %t14
  %t16 = icmp eq i64 %t15, 4
  %t17 = call i1 @ql_4_ready(i1 %t16)
  %t18 = call i1 @ql_6_enabled({ i1 } %t10, i1 %t17)
  br i1 %t18, label %bb3, label %bb0_match_dispatch1
bb0_match_dispatch1:
  br i1 %t0, label %bb2, label %bb4
bb1:
  %t19 = load i64, ptr %l0__return
  ret i64 %t19
bb2:
  %t20 = load i64, ptr %l1__t0
  store i64 %t20, ptr %l3_first
  store i64 3, ptr %l5__t3
  %t21 = load i64, ptr %l5__t3
  br label %bb2_match_guard0
bb2_match_guard0:
  store i64 %t21, ptr %l6_current
  %t22 = call [3 x i64] @ql_2_bundle(i64 %t21)
  %t23 = alloca [3 x i64]
  store [3 x i64] %t22, ptr %t23
  %t24 = call i64 @ql_3_offset(i64 %t21)
  %t25 = getelementptr inbounds [3 x i64], ptr %t23, i64 0, i64 %t24
  %t26 = load i64, ptr %t25
  %t27 = call i64 @ql_5_seed(i64 8)
  %t28 = call i64 @ql_5_seed(i64 9)
  %t29 = insertvalue [3 x i64] undef, i64 %t26, 0
  %t30 = insertvalue [3 x i64] %t29, i64 %t27, 1
  %t31 = insertvalue [3 x i64] %t30, i64 %t28, 2
  %t32 = alloca [3 x i64]
  store [3 x i64] %t31, ptr %t32
  %t33 = getelementptr inbounds [3 x i64], ptr %t32, i64 0, i64 0
  %t34 = load i64, ptr %t33
  %t35 = call i64 @ql_5_seed(i64 4)
  %t36 = icmp eq i64 %t34, %t35
  br i1 %t36, label %bb6, label %bb7
bb3:
  store i64 10, ptr %l1__t0
  br label %bb2
bb4:
  store i64 0, ptr %l1__t0
  br label %bb2
bb5:
  %t37 = load i64, ptr %l4__t2
  store i64 %t37, ptr %l7_second
  store i64 3, ptr %l9__t5
  %t38 = load i64, ptr %l9__t5
  br label %bb5_match_guard0
bb5_match_guard0:
  store i64 %t38, ptr %l10_current
  %t39 = call [3 x i64] @ql_2_bundle(i64 %t38)
  %t40 = alloca [3 x i64]
  store [3 x i64] %t39, ptr %t40
  %t41 = call i64 @ql_3_offset(i64 %t38)
  %t42 = getelementptr inbounds [3 x i64], ptr %t40, i64 0, i64 %t41
  %t43 = load i64, ptr %t42
  %t44 = call i64 @ql_5_seed(i64 8)
  %t45 = insertvalue [3 x i64] undef, i64 %t43, 0
  %t46 = insertvalue [3 x i64] %t45, i64 %t44, 1
  %t47 = insertvalue [3 x i64] %t46, i64 9, 2
  %t48 = alloca [3 x i64]
  store [3 x i64] %t47, ptr %t48
  %t49 = getelementptr inbounds [3 x i64], ptr %t48, i64 0, i64 0
  %t50 = load i64, ptr %t49
  %t51 = call i64 @ql_5_seed(i64 4)
  %t52 = call i1 @ql_7_matches(i64 %t50, i64 %t51)
  br i1 %t52, label %bb9, label %bb10
bb6:
  %t53 = load i64, ptr %l5__t3
  store i64 %t53, ptr %l6_current
  store i64 12, ptr %l4__t2
  br label %bb5
bb7:
  store i64 0, ptr %l4__t2
  br label %bb5
bb8:
  %t54 = load i64, ptr %l8__t4
  store i64 %t54, ptr %l11_third
  %t55 = load i64, ptr %l3_first
  %t56 = load i64, ptr %l7_second
  %t57 = add i64 %t55, %t56
  store i64 %t57, ptr %l12__t6
  %t58 = load i64, ptr %l12__t6
  %t59 = load i64, ptr %l11_third
  %t60 = add i64 %t58, %t59
  store i64 %t60, ptr %l13__t7
  %t61 = load i64, ptr %l13__t7
  store i64 %t61, ptr %l0__return
  br label %bb1
bb9:
  %t62 = load i64, ptr %l9__t5
  store i64 %t62, ptr %l10_current
  store i64 20, ptr %l8__t4
  br label %bb8
bb10:
  store i64 0, ptr %l8__t4
  br label %bb8
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_8_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
