; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'match_guard_nested_call_root_inline_combos'
source_filename = "match_guard_nested_call_root_inline_combos.ql"
target triple = "x86_64-pc-windows-msvc"

define [3 x i64] @ql_0_bundle(i64 %arg0) {
entry:
  %l0__return = alloca [3 x i64]
  %l1_seed = alloca i64
  %l2__t0 = alloca i64
  %l3__t1 = alloca i64
  %l4__t2 = alloca [3 x i64]
  store i64 %arg0, ptr %l1_seed
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_seed
  %t1 = add i64 %t0, 1
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l1_seed
  %t3 = add i64 %t2, 2
  store i64 %t3, ptr %l3__t1
  %t4 = load i64, ptr %l1_seed
  %t5 = load i64, ptr %l2__t0
  %t6 = load i64, ptr %l3__t1
  %t7 = insertvalue [3 x i64] undef, i64 %t4, 0
  %t8 = insertvalue [3 x i64] %t7, i64 %t5, 1
  %t9 = insertvalue [3 x i64] %t8, i64 %t6, 2
  store [3 x i64] %t9, ptr %l4__t2
  %t10 = load [3 x i64], ptr %l4__t2
  store [3 x i64] %t10, ptr %l0__return
  br label %bb1
bb1:
  %t11 = load [3 x i64], ptr %l0__return
  ret [3 x i64] %t11
}

define i64 @ql_1_offset(i64 %arg0) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %l2__t0 = alloca i64
  store i64 %arg0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  %t1 = sub i64 %t0, 2
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l2__t0
  store i64 %t2, ptr %l0__return
  br label %bb1
bb1:
  %t3 = load i64, ptr %l0__return
  ret i64 %t3
}

define i1 @ql_2_matches(i64 %arg0, i64 %arg1) {
entry:
  %l0__return = alloca i1
  %l1_value = alloca i64
  %l2_expected = alloca i64
  %l3__t0 = alloca i1
  store i64 %arg0, ptr %l1_value
  store i64 %arg1, ptr %l2_expected
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  %t1 = load i64, ptr %l2_expected
  %t2 = icmp eq i64 %t0, %t1
  store i1 %t2, ptr %l3__t0
  %t3 = load i1, ptr %l3__t0
  store i1 %t3, ptr %l0__return
  br label %bb1
bb1:
  %t4 = load i1, ptr %l0__return
  ret i1 %t4
}

define { i64, i64 } @ql_3_pair(i64 %arg0, i64 %arg1) {
entry:
  %l0__return = alloca { i64, i64 }
  %l1_left = alloca i64
  %l2_right = alloca i64
  %l3__t0 = alloca { i64, i64 }
  store i64 %arg0, ptr %l1_left
  store i64 %arg1, ptr %l2_right
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_left
  %t1 = load i64, ptr %l2_right
  %t2 = insertvalue { i64, i64 } undef, i64 %t0, 0
  %t3 = insertvalue { i64, i64 } %t2, i64 %t1, 1
  store { i64, i64 } %t3, ptr %l3__t0
  %t4 = load { i64, i64 }, ptr %l3__t0
  store { i64, i64 } %t4, ptr %l0__return
  br label %bb1
bb1:
  %t5 = load { i64, i64 }, ptr %l0__return
  ret { i64, i64 } %t5
}

define i1 @ql_4_contains([3 x i64] %arg0, i64 %arg1) {
entry:
  %l0__return = alloca i1
  %l1_values = alloca [3 x i64]
  %l2_expected = alloca i64
  %l3__t0 = alloca i1
  store [3 x i64] %arg0, ptr %l1_values
  store i64 %arg1, ptr %l2_expected
  br label %bb0
bb0:
  %t0 = getelementptr inbounds [3 x i64], ptr %l1_values, i64 0, i64 0
  %t1 = load i64, ptr %t0
  %t2 = load i64, ptr %l2_expected
  %t3 = icmp eq i64 %t1, %t2
  store i1 %t3, ptr %l3__t0
  %t4 = load i1, ptr %l3__t0
  store i1 %t4, ptr %l0__return
  br label %bb1
bb1:
  %t5 = load i1, ptr %l0__return
  ret i1 %t5
}

define i64 @ql_5_main() {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca i64
  %l2__t1 = alloca i64
  %l3_current = alloca i64
  %l4_first = alloca i64
  %l5__t2 = alloca i64
  %l6__t3 = alloca i64
  %l7_current = alloca i64
  %l8_second = alloca i64
  %l9__t4 = alloca i64
  %l10__t5 = alloca i64
  %l11_current = alloca i64
  %l12_third = alloca i64
  %l13__t6 = alloca i64
  %l14__t7 = alloca i64
  br label %bb0
bb0:
  store i64 3, ptr %l2__t1
  %t0 = load i64, ptr %l2__t1
  br label %bb0_match_guard0
bb0_match_guard0:
  store i64 %t0, ptr %l3_current
  %t1 = call [3 x i64] @ql_0_bundle(i64 %t0)
  %t2 = alloca [3 x i64]
  store [3 x i64] %t1, ptr %t2
  %t3 = call i64 @ql_1_offset(i64 %t0)
  %t4 = getelementptr inbounds [3 x i64], ptr %t2, i64 0, i64 %t3
  %t5 = load i64, ptr %t4
  %t6 = add i64 %t0, 1
  %t7 = insertvalue [3 x i64] undef, i64 %t5, 0
  %t8 = insertvalue [3 x i64] %t7, i64 %t6, 1
  %t9 = insertvalue [3 x i64] %t8, i64 6, 2
  %t10 = alloca [3 x i64]
  store [3 x i64] %t9, ptr %t10
  %t11 = getelementptr inbounds [3 x i64], ptr %t10, i64 0, i64 0
  %t12 = load i64, ptr %t11
  %t13 = icmp eq i64 %t12, 4
  br i1 %t13, label %bb3, label %bb4
bb1:
  %t14 = load i64, ptr %l0__return
  ret i64 %t14
bb2:
  %t15 = load i64, ptr %l1__t0
  store i64 %t15, ptr %l4_first
  store i64 22, ptr %l6__t3
  %t16 = load i64, ptr %l6__t3
  br label %bb2_match_guard0
bb2_match_guard0:
  store i64 %t16, ptr %l7_current
  %t17 = call [3 x i64] @ql_0_bundle(i64 3)
  %t18 = alloca [3 x i64]
  store [3 x i64] %t17, ptr %t18
  %t19 = call i64 @ql_1_offset(i64 3)
  %t20 = getelementptr inbounds [3 x i64], ptr %t18, i64 0, i64 %t19
  %t21 = load i64, ptr %t20
  %t22 = insertvalue [3 x i64] undef, i64 %t21, 0
  %t23 = insertvalue [3 x i64] %t22, i64 %t16, 1
  %t24 = insertvalue [3 x i64] %t23, i64 9, 2
  %t25 = call i1 @ql_4_contains([3 x i64] %t24, i64 4)
  br i1 %t25, label %bb6, label %bb7
bb3:
  %t26 = load i64, ptr %l2__t1
  store i64 %t26, ptr %l3_current
  store i64 10, ptr %l1__t0
  br label %bb2
bb4:
  store i64 0, ptr %l1__t0
  br label %bb2
bb5:
  %t27 = load i64, ptr %l5__t2
  store i64 %t27, ptr %l8_second
  store i64 3, ptr %l10__t5
  %t28 = load i64, ptr %l10__t5
  br label %bb5_match_guard0
bb5_match_guard0:
  store i64 %t28, ptr %l11_current
  %t29 = call [3 x i64] @ql_0_bundle(i64 %t28)
  %t30 = alloca [3 x i64]
  store [3 x i64] %t29, ptr %t30
  %t31 = call i64 @ql_1_offset(i64 %t28)
  %t32 = getelementptr inbounds [3 x i64], ptr %t30, i64 0, i64 %t31
  %t33 = load i64, ptr %t32
  %t34 = call { i64, i64 } @ql_3_pair(i64 %t33, i64 8)
  %t35 = alloca { i64, i64 }
  store { i64, i64 } %t34, ptr %t35
  %t36 = getelementptr inbounds { i64, i64 }, ptr %t35, i32 0, i32 0
  %t37 = load i64, ptr %t36
  %t38 = call i1 @ql_2_matches(i64 %t37, i64 4)
  br i1 %t38, label %bb9, label %bb10
bb6:
  %t39 = load i64, ptr %l6__t3
  store i64 %t39, ptr %l7_current
  store i64 12, ptr %l5__t2
  br label %bb5
bb7:
  store i64 0, ptr %l5__t2
  br label %bb5
bb8:
  %t40 = load i64, ptr %l9__t4
  store i64 %t40, ptr %l12_third
  %t41 = load i64, ptr %l4_first
  %t42 = load i64, ptr %l8_second
  %t43 = add i64 %t41, %t42
  store i64 %t43, ptr %l13__t6
  %t44 = load i64, ptr %l13__t6
  %t45 = load i64, ptr %l12_third
  %t46 = add i64 %t44, %t45
  store i64 %t46, ptr %l14__t7
  %t47 = load i64, ptr %l14__t7
  store i64 %t47, ptr %l0__return
  br label %bb1
bb9:
  %t48 = load i64, ptr %l10__t5
  store i64 %t48, ptr %l11_current
  store i64 20, ptr %l9__t4
  br label %bb8
bb10:
  store i64 0, ptr %l9__t4
  br label %bb8
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_5_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
