; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'match_guard_item_backed_inline_combos'
source_filename = "match_guard_item_backed_inline_combos.ql"
target triple = "x86_64-pc-windows-msvc"

define i1 @ql_3_check({ i1, i64 } %arg0, i1 %arg1) {
entry:
  %l0__return = alloca i1
  %l1_state = alloca { i1, i64 }
  %l2_extra = alloca i1
  %l3__t0 = alloca i1
  store { i1, i64 } %arg0, ptr %l1_state
  store i1 %arg1, ptr %l2_extra
  br label %bb0
bb0:
  %t0 = getelementptr inbounds { i1, i64 }, ptr %l1_state, i32 0, i32 0
  %t1 = load i1, ptr %t0
  br i1 %t1, label %bb3, label %bb4
bb1:
  %t2 = load i1, ptr %l0__return
  ret i1 %t2
bb2:
  %t3 = load i1, ptr %l3__t0
  store i1 %t3, ptr %l0__return
  br label %bb1
bb3:
  %t4 = load i1, ptr %l2_extra
  store i1 %t4, ptr %l3__t0
  br label %bb2
bb4:
  store i1 false, ptr %l3__t0
  br label %bb2
}

define i64 @ql_4_main() {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca { i1, i64 }
  %l2_state = alloca { i1, i64 }
  %l3__t1 = alloca i64
  %l4__t2 = alloca i1
  %l5_first = alloca i64
  %l6__t3 = alloca i64
  %l7__t4 = alloca i64
  %l8_current = alloca i64
  %l9_second = alloca i64
  %l10__t5 = alloca i64
  %l11__t6 = alloca i64
  %l12_current = alloca i64
  %l13_third = alloca i64
  %l14__t7 = alloca i64
  %l15__t8 = alloca i64
  br label %bb0
bb0:
  %t0 = insertvalue { i1, i64 } undef, i1 true, 0
  %t1 = insertvalue { i1, i64 } %t0, i64 7, 1
  store { i1, i64 } %t1, ptr %l1__t0
  %t2 = load { i1, i64 }, ptr %l1__t0
  store { i1, i64 } %t2, ptr %l2_state
  store i1 true, ptr %l4__t2
  %t3 = load i1, ptr %l4__t2
  br i1 %t3, label %bb0_match_guard0, label %bb0_match_dispatch1
bb0_match_guard0:
  %t4 = load { i1, i64 }, ptr %l2_state
  %t5 = call i1 @ql_3_check({ i1, i64 } %t4, i1 true)
  br i1 %t5, label %bb3, label %bb0_match_dispatch1
bb0_match_dispatch1:
  br i1 %t3, label %bb2, label %bb4
bb1:
  %t6 = load i64, ptr %l0__return
  ret i64 %t6
bb2:
  %t7 = load i64, ptr %l3__t1
  store i64 %t7, ptr %l5_first
  store i64 22, ptr %l7__t4
  %t8 = load i64, ptr %l7__t4
  br label %bb2_match_guard0
bb2_match_guard0:
  store i64 %t8, ptr %l8_current
  %t9 = insertvalue { i64, i64 } undef, i64 3, 0
  %t10 = insertvalue { i64, i64 } %t9, i64 %t8, 1
  %t11 = alloca { i64, i64 }
  store { i64, i64 } %t10, ptr %t11
  %t12 = getelementptr inbounds { i64, i64 }, ptr %t11, i32 0, i32 1
  %t13 = load i64, ptr %t12
  %t14 = icmp eq i64 %t13, 22
  br i1 %t14, label %bb6, label %bb7
bb3:
  store i64 10, ptr %l3__t1
  br label %bb2
bb4:
  store i64 0, ptr %l3__t1
  br label %bb2
bb5:
  %t15 = load i64, ptr %l6__t3
  store i64 %t15, ptr %l9_second
  store i64 3, ptr %l11__t6
  %t16 = load i64, ptr %l11__t6
  br label %bb5_match_guard0
bb5_match_guard0:
  store i64 %t16, ptr %l12_current
  %t17 = add i64 %t16, 1
  %t18 = insertvalue [3 x i64] undef, i64 3, 0
  %t19 = insertvalue [3 x i64] %t18, i64 %t17, 1
  %t20 = insertvalue [3 x i64] %t19, i64 5, 2
  %t21 = alloca [3 x i64]
  store [3 x i64] %t20, ptr %t21
  %t22 = sub i64 %t16, 2
  %t23 = getelementptr inbounds [3 x i64], ptr %t21, i64 0, i64 %t22
  %t24 = load i64, ptr %t23
  %t25 = icmp eq i64 %t24, 4
  br i1 %t25, label %bb9, label %bb10
bb6:
  %t26 = load i64, ptr %l7__t4
  store i64 %t26, ptr %l8_current
  store i64 12, ptr %l6__t3
  br label %bb5
bb7:
  store i64 0, ptr %l6__t3
  br label %bb5
bb8:
  %t27 = load i64, ptr %l10__t5
  store i64 %t27, ptr %l13_third
  %t28 = load i64, ptr %l5_first
  %t29 = load i64, ptr %l9_second
  %t30 = add i64 %t28, %t29
  store i64 %t30, ptr %l14__t7
  %t31 = load i64, ptr %l14__t7
  %t32 = load i64, ptr %l13_third
  %t33 = add i64 %t31, %t32
  store i64 %t33, ptr %l15__t8
  %t34 = load i64, ptr %l15__t8
  store i64 %t34, ptr %l0__return
  br label %bb1
bb9:
  %t35 = load i64, ptr %l11__t6
  store i64 %t35, ptr %l12_current
  store i64 20, ptr %l10__t5
  br label %bb8
bb10:
  store i64 0, ptr %l10__t5
  br label %bb8
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_4_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
