; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'match_guard_aggregate_call_args'
source_filename = "match_guard_aggregate_call_args.ql"
target triple = "x86_64-pc-windows-msvc"

define i1 @ql_1_enabled({ i1 } %arg0) {
entry:
  %l0__return = alloca i1
  %l1_state = alloca { i1 }
  store { i1 } %arg0, ptr %l1_state
  br label %bb0
bb0:
  %t0 = getelementptr inbounds { i1 }, ptr %l1_state, i32 0, i32 0
  %t1 = load i1, ptr %t0
  store i1 %t1, ptr %l0__return
  br label %bb1
bb1:
  %t2 = load i1, ptr %l0__return
  ret i1 %t2
}

define { i64, i64 } @ql_2_pair(i64 %arg0) {
entry:
  %l0__return = alloca { i64, i64 }
  %l1_value = alloca i64
  %l2__t0 = alloca { i64, i64 }
  store i64 %arg0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  %t1 = insertvalue { i64, i64 } undef, i64 0, 0
  %t2 = insertvalue { i64, i64 } %t1, i64 %t0, 1
  store { i64, i64 } %t2, ptr %l2__t0
  %t3 = load { i64, i64 }, ptr %l2__t0
  store { i64, i64 } %t3, ptr %l0__return
  br label %bb1
bb1:
  %t4 = load { i64, i64 }, ptr %l0__return
  ret { i64, i64 } %t4
}

define i1 @ql_3_matches({ i64, i64 } %arg0, i64 %arg1) {
entry:
  %l0__return = alloca i1
  %l1_pair = alloca { i64, i64 }
  %l2_expected = alloca i64
  %l3__t0 = alloca i1
  store { i64, i64 } %arg0, ptr %l1_pair
  store i64 %arg1, ptr %l2_expected
  br label %bb0
bb0:
  %t0 = getelementptr inbounds { i64, i64 }, ptr %l1_pair, i32 0, i32 1
  %t1 = load i64, ptr %t0
  %t2 = load i64, ptr %l2_expected
  %t3 = icmp eq i64 %t1, %t2
  store i1 %t3, ptr %l3__t0
  %t4 = load i1, ptr %l3__t0
  store i1 %t4, ptr %l0__return
  br label %bb1
bb1:
  %t5 = load i1, ptr %l0__return
  ret i1 %t5
}

define [3 x i64] @ql_4_values(i64 %arg0) {
entry:
  %l0__return = alloca [3 x i64]
  %l1_seed = alloca i64
  %l2__t0 = alloca i64
  %l3__t1 = alloca i64
  %l4__t2 = alloca [3 x i64]
  store i64 %arg0, ptr %l1_seed
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_seed
  %t1 = add i64 %t0, 1
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l1_seed
  %t3 = add i64 %t2, 2
  store i64 %t3, ptr %l3__t1
  %t4 = load i64, ptr %l1_seed
  %t5 = load i64, ptr %l2__t0
  %t6 = load i64, ptr %l3__t1
  %t7 = insertvalue [3 x i64] undef, i64 %t4, 0
  %t8 = insertvalue [3 x i64] %t7, i64 %t5, 1
  %t9 = insertvalue [3 x i64] %t8, i64 %t6, 2
  store [3 x i64] %t9, ptr %l4__t2
  %t10 = load [3 x i64], ptr %l4__t2
  store [3 x i64] %t10, ptr %l0__return
  br label %bb1
bb1:
  %t11 = load [3 x i64], ptr %l0__return
  ret [3 x i64] %t11
}

define i1 @ql_5_contains([3 x i64] %arg0, i64 %arg1) {
entry:
  %l0__return = alloca i1
  %l1_values = alloca [3 x i64]
  %l2_expected = alloca i64
  %l3__t0 = alloca i1
  store [3 x i64] %arg0, ptr %l1_values
  store i64 %arg1, ptr %l2_expected
  br label %bb0
bb0:
  %t0 = getelementptr inbounds [3 x i64], ptr %l1_values, i64 0, i64 1
  %t1 = load i64, ptr %t0
  %t2 = load i64, ptr %l2_expected
  %t3 = icmp eq i64 %t1, %t2
  store i1 %t3, ptr %l3__t0
  %t4 = load i1, ptr %l3__t0
  store i1 %t4, ptr %l0__return
  br label %bb1
bb1:
  %t5 = load i1, ptr %l0__return
  ret i1 %t5
}

define i64 @ql_6_main() {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca { i1 }
  %l2_state = alloca { i1 }
  %l3__t1 = alloca i64
  %l4__t2 = alloca { i1 }
  %l5_current = alloca { i1 }
  %l6_first = alloca i64
  %l7__t3 = alloca i64
  %l8__t4 = alloca i64
  %l9_current = alloca i64
  %l10_second = alloca i64
  %l11__t5 = alloca i64
  %l12__t6 = alloca i64
  %l13_current = alloca i64
  %l14_third = alloca i64
  %l15__t7 = alloca i64
  %l16__t8 = alloca i64
  br label %bb0
bb0:
  %t0 = insertvalue { i1 } undef, i1 true, 0
  store { i1 } %t0, ptr %l1__t0
  %t1 = load { i1 }, ptr %l1__t0
  store { i1 } %t1, ptr %l2_state
  %t2 = load { i1 }, ptr %l2_state
  store { i1 } %t2, ptr %l4__t2
  %t3 = load { i1 }, ptr %l4__t2
  br label %bb0_match_guard0
bb0_match_guard0:
  store { i1 } %t3, ptr %l5_current
  %t4 = load { i1 }, ptr %l5_current
  %t5 = call i1 @ql_1_enabled({ i1 } %t4)
  br i1 %t5, label %bb3, label %bb4
bb1:
  %t6 = load i64, ptr %l0__return
  ret i64 %t6
bb2:
  %t7 = load i64, ptr %l3__t1
  store i64 %t7, ptr %l6_first
  store i64 22, ptr %l8__t4
  %t8 = load i64, ptr %l8__t4
  br label %bb2_match_guard0
bb2_match_guard0:
  store i64 %t8, ptr %l9_current
  %t9 = call { i64, i64 } @ql_2_pair(i64 %t8)
  %t10 = alloca { i64, i64 }
  store { i64, i64 } %t9, ptr %t10
  %t11 = load { i64, i64 }, ptr %t10
  %t12 = call i1 @ql_3_matches({ i64, i64 } %t11, i64 22)
  br i1 %t12, label %bb6, label %bb7
bb3:
  %t13 = load { i1 }, ptr %l4__t2
  store { i1 } %t13, ptr %l5_current
  store i64 10, ptr %l3__t1
  br label %bb2
bb4:
  store i64 0, ptr %l3__t1
  br label %bb2
bb5:
  %t14 = load i64, ptr %l7__t3
  store i64 %t14, ptr %l10_second
  store i64 3, ptr %l12__t6
  %t15 = load i64, ptr %l12__t6
  br label %bb5_match_guard0
bb5_match_guard0:
  store i64 %t15, ptr %l13_current
  %t16 = call [3 x i64] @ql_4_values(i64 %t15)
  %t17 = alloca [3 x i64]
  store [3 x i64] %t16, ptr %t17
  %t18 = load [3 x i64], ptr %t17
  %t19 = call i1 @ql_5_contains([3 x i64] %t18, i64 4)
  br i1 %t19, label %bb9, label %bb10
bb6:
  %t20 = load i64, ptr %l8__t4
  store i64 %t20, ptr %l9_current
  store i64 12, ptr %l7__t3
  br label %bb5
bb7:
  store i64 0, ptr %l7__t3
  br label %bb5
bb8:
  %t21 = load i64, ptr %l11__t5
  store i64 %t21, ptr %l14_third
  %t22 = load i64, ptr %l6_first
  %t23 = load i64, ptr %l10_second
  %t24 = add i64 %t22, %t23
  store i64 %t24, ptr %l15__t7
  %t25 = load i64, ptr %l15__t7
  %t26 = load i64, ptr %l14_third
  %t27 = add i64 %t25, %t26
  store i64 %t27, ptr %l16__t8
  %t28 = load i64, ptr %l16__t8
  store i64 %t28, ptr %l0__return
  br label %bb1
bb9:
  %t29 = load i64, ptr %l12__t6
  store i64 %t29, ptr %l13_current
  store i64 20, ptr %l11__t5
  br label %bb8
bb10:
  store i64 0, ptr %l11__t5
  br label %bb8
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_6_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
