; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'match_guard_inline_projection_roots'
source_filename = "match_guard_inline_projection_roots.ql"
target triple = "x86_64-pc-windows-msvc"

define i64 @ql_1_main() {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %l2__t0 = alloca i64
  %l3__t1 = alloca i64
  %l4_current = alloca i64
  %l5_first = alloca i64
  %l6__t2 = alloca i64
  %l7__t3 = alloca i64
  %l8_current = alloca i64
  %l9_second = alloca i64
  %l10__t4 = alloca i64
  %l11__t5 = alloca i64
  %l12_current = alloca i64
  %l13_third = alloca i64
  %l14__t6 = alloca i64
  %l15__t7 = alloca i64
  br label %bb0
bb0:
  store i64 22, ptr %l1_value
  %t0 = load i64, ptr %l1_value
  store i64 %t0, ptr %l3__t1
  %t1 = load i64, ptr %l3__t1
  br label %bb0_match_guard0
bb0_match_guard0:
  store i64 %t1, ptr %l4_current
  %t2 = icmp eq i64 %t1, 22
  br i1 %t2, label %bb3, label %bb4
bb1:
  %t3 = load i64, ptr %l0__return
  ret i64 %t3
bb2:
  %t4 = load i64, ptr %l2__t0
  store i64 %t4, ptr %l5_first
  %t5 = load i64, ptr %l1_value
  store i64 %t5, ptr %l7__t3
  %t6 = load i64, ptr %l7__t3
  br label %bb2_match_guard0
bb2_match_guard0:
  store i64 %t6, ptr %l8_current
  %t7 = icmp eq i64 %t6, 22
  br i1 %t7, label %bb6, label %bb7
bb3:
  %t8 = load i64, ptr %l3__t1
  store i64 %t8, ptr %l4_current
  store i64 10, ptr %l2__t0
  br label %bb2
bb4:
  store i64 0, ptr %l2__t0
  br label %bb2
bb5:
  %t9 = load i64, ptr %l6__t2
  store i64 %t9, ptr %l9_second
  store i64 3, ptr %l11__t5
  %t10 = load i64, ptr %l11__t5
  br label %bb5_match_guard0
bb5_match_guard0:
  store i64 %t10, ptr %l12_current
  %t11 = add i64 %t10, 1
  %t12 = icmp eq i64 %t11, 4
  br i1 %t12, label %bb9, label %bb10
bb6:
  %t13 = load i64, ptr %l7__t3
  store i64 %t13, ptr %l8_current
  store i64 12, ptr %l6__t2
  br label %bb5
bb7:
  store i64 0, ptr %l6__t2
  br label %bb5
bb8:
  %t14 = load i64, ptr %l10__t4
  store i64 %t14, ptr %l13_third
  %t15 = load i64, ptr %l5_first
  %t16 = load i64, ptr %l9_second
  %t17 = add i64 %t15, %t16
  store i64 %t17, ptr %l14__t6
  %t18 = load i64, ptr %l14__t6
  %t19 = load i64, ptr %l13_third
  %t20 = add i64 %t18, %t19
  store i64 %t20, ptr %l15__t7
  %t21 = load i64, ptr %l15__t7
  store i64 %t21, ptr %l0__return
  br label %bb1
bb9:
  %t22 = load i64, ptr %l11__t5
  store i64 %t22, ptr %l12_current
  store i64 20, ptr %l10__t4
  br label %bb8
bb10:
  store i64 0, ptr %l10__t4
  br label %bb8
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_1_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
