; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'match_guard_binding_backed_nested_call_root_combos'
source_filename = "match_guard_binding_backed_nested_call_root_combos.ql"
target triple = "x86_64-pc-windows-msvc"

define { i1, i64 } @ql_1_state(i1 %arg0, i64 %arg1) {
entry:
  %l0__return = alloca { i1, i64 }
  %l1_flag = alloca i1
  %l2_value = alloca i64
  %l3__t0 = alloca { i1, i64 }
  store i1 %arg0, ptr %l1_flag
  store i64 %arg1, ptr %l2_value
  br label %bb0
bb0:
  %t0 = load i1, ptr %l1_flag
  %t1 = load i64, ptr %l2_value
  %t2 = insertvalue { i1, i64 } undef, i1 %t0, 0
  %t3 = insertvalue { i1, i64 } %t2, i64 %t1, 1
  store { i1, i64 } %t3, ptr %l3__t0
  %t4 = load { i1, i64 }, ptr %l3__t0
  store { i1, i64 } %t4, ptr %l0__return
  br label %bb1
bb1:
  %t5 = load { i1, i64 }, ptr %l0__return
  ret { i1, i64 } %t5
}

define [3 x i64] @ql_2_bundle(i64 %arg0) {
entry:
  %l0__return = alloca [3 x i64]
  %l1_seed = alloca i64
  %l2__t0 = alloca i64
  %l3__t1 = alloca i64
  %l4__t2 = alloca [3 x i64]
  store i64 %arg0, ptr %l1_seed
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_seed
  %t1 = add i64 %t0, 1
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l1_seed
  %t3 = add i64 %t2, 2
  store i64 %t3, ptr %l3__t1
  %t4 = load i64, ptr %l1_seed
  %t5 = load i64, ptr %l2__t0
  %t6 = load i64, ptr %l3__t1
  %t7 = insertvalue [3 x i64] undef, i64 %t4, 0
  %t8 = insertvalue [3 x i64] %t7, i64 %t5, 1
  %t9 = insertvalue [3 x i64] %t8, i64 %t6, 2
  store [3 x i64] %t9, ptr %l4__t2
  %t10 = load [3 x i64], ptr %l4__t2
  store [3 x i64] %t10, ptr %l0__return
  br label %bb1
bb1:
  %t11 = load [3 x i64], ptr %l0__return
  ret [3 x i64] %t11
}

define i64 @ql_3_offset(i64 %arg0) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %l2__t0 = alloca i64
  store i64 %arg0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  %t1 = sub i64 %t0, 2
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l2__t0
  store i64 %t2, ptr %l0__return
  br label %bb1
bb1:
  %t3 = load i64, ptr %l0__return
  ret i64 %t3
}

define i1 @ql_4_enabled({ i1, i64 } %arg0, i1 %arg1) {
entry:
  %l0__return = alloca i1
  %l1_state = alloca { i1, i64 }
  %l2_extra = alloca i1
  %l3__t0 = alloca i1
  store { i1, i64 } %arg0, ptr %l1_state
  store i1 %arg1, ptr %l2_extra
  br label %bb0
bb0:
  %t0 = getelementptr inbounds { i1, i64 }, ptr %l1_state, i32 0, i32 0
  %t1 = load i1, ptr %t0
  br i1 %t1, label %bb3, label %bb4
bb1:
  %t2 = load i1, ptr %l0__return
  ret i1 %t2
bb2:
  %t3 = load i1, ptr %l3__t0
  store i1 %t3, ptr %l0__return
  br label %bb1
bb3:
  %t4 = load i1, ptr %l2_extra
  store i1 %t4, ptr %l3__t0
  br label %bb2
bb4:
  store i1 false, ptr %l3__t0
  br label %bb2
}

define i1 @ql_5_matches(i64 %arg0, i64 %arg1) {
entry:
  %l0__return = alloca i1
  %l1_value = alloca i64
  %l2_expected = alloca i64
  %l3__t0 = alloca i1
  store i64 %arg0, ptr %l1_value
  store i64 %arg1, ptr %l2_expected
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  %t1 = load i64, ptr %l2_expected
  %t2 = icmp eq i64 %t0, %t1
  store i1 %t2, ptr %l3__t0
  %t3 = load i1, ptr %l3__t0
  store i1 %t3, ptr %l0__return
  br label %bb1
bb1:
  %t4 = load i1, ptr %l0__return
  ret i1 %t4
}

define i64 @ql_6_main() {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca i64
  %l2__t1 = alloca { i1, i64 }
  %l3__t2 = alloca { i1, i64 }
  %l4_current = alloca { i1, i64 }
  %l5_first = alloca i64
  %l6__t3 = alloca i64
  %l7__t4 = alloca { i1, i64 }
  %l8__t5 = alloca { i1, i64 }
  %l9_current = alloca { i1, i64 }
  %l10_second = alloca i64
  %l11__t6 = alloca i64
  %l12__t7 = alloca { i1, i64 }
  %l13__t8 = alloca { i1, i64 }
  %l14_current = alloca { i1, i64 }
  %l15_third = alloca i64
  %l16__t9 = alloca i64
  %l17__t10 = alloca i64
  br label %bb0
bb0:
  %t0 = call { i1, i64 } @ql_1_state(i1 true, i64 3)
  store { i1, i64 } %t0, ptr %l2__t1
  %t1 = load { i1, i64 }, ptr %l2__t1
  store { i1, i64 } %t1, ptr %l3__t2
  %t2 = load { i1, i64 }, ptr %l3__t2
  br label %bb0_match_guard0
bb0_match_guard0:
  store { i1, i64 } %t2, ptr %l4_current
  %t3 = load { i1, i64 }, ptr %l4_current
  %t4 = getelementptr inbounds { i1, i64 }, ptr %l4_current, i32 0, i32 1
  %t5 = load i64, ptr %t4
  %t6 = call [3 x i64] @ql_2_bundle(i64 %t5)
  %t7 = alloca [3 x i64]
  store [3 x i64] %t6, ptr %t7
  %t8 = getelementptr inbounds { i1, i64 }, ptr %l4_current, i32 0, i32 1
  %t9 = load i64, ptr %t8
  %t10 = call i64 @ql_3_offset(i64 %t9)
  %t11 = getelementptr inbounds [3 x i64], ptr %t7, i64 0, i64 %t10
  %t12 = load i64, ptr %t11
  %t13 = icmp eq i64 %t12, 4
  %t14 = call i1 @ql_4_enabled({ i1, i64 } %t3, i1 %t13)
  br i1 %t14, label %bb3, label %bb4
bb1:
  %t15 = load i64, ptr %l0__return
  ret i64 %t15
bb2:
  %t16 = load i64, ptr %l1__t0
  store i64 %t16, ptr %l5_first
  %t17 = call { i1, i64 } @ql_1_state(i1 true, i64 3)
  store { i1, i64 } %t17, ptr %l7__t4
  %t18 = load { i1, i64 }, ptr %l7__t4
  store { i1, i64 } %t18, ptr %l8__t5
  %t19 = load { i1, i64 }, ptr %l8__t5
  br label %bb2_match_guard0
bb2_match_guard0:
  store { i1, i64 } %t19, ptr %l9_current
  %t20 = getelementptr inbounds { i1, i64 }, ptr %l9_current, i32 0, i32 1
  %t21 = load i64, ptr %t20
  %t22 = call [3 x i64] @ql_2_bundle(i64 %t21)
  %t23 = alloca [3 x i64]
  store [3 x i64] %t22, ptr %t23
  %t24 = getelementptr inbounds { i1, i64 }, ptr %l9_current, i32 0, i32 1
  %t25 = load i64, ptr %t24
  %t26 = call i64 @ql_3_offset(i64 %t25)
  %t27 = getelementptr inbounds [3 x i64], ptr %t23, i64 0, i64 %t26
  %t28 = load i64, ptr %t27
  %t29 = icmp eq i64 %t28, 4
  br i1 %t29, label %bb6, label %bb7
bb3:
  %t30 = load { i1, i64 }, ptr %l3__t2
  store { i1, i64 } %t30, ptr %l4_current
  store i64 10, ptr %l1__t0
  br label %bb2
bb4:
  store i64 0, ptr %l1__t0
  br label %bb2
bb5:
  %t31 = load i64, ptr %l6__t3
  store i64 %t31, ptr %l10_second
  %t32 = call { i1, i64 } @ql_1_state(i1 true, i64 3)
  store { i1, i64 } %t32, ptr %l12__t7
  %t33 = load { i1, i64 }, ptr %l12__t7
  store { i1, i64 } %t33, ptr %l13__t8
  %t34 = load { i1, i64 }, ptr %l13__t8
  br label %bb5_match_guard0
bb5_match_guard0:
  store { i1, i64 } %t34, ptr %l14_current
  %t35 = getelementptr inbounds { i1, i64 }, ptr %l14_current, i32 0, i32 1
  %t36 = load i64, ptr %t35
  %t37 = call [3 x i64] @ql_2_bundle(i64 %t36)
  %t38 = alloca [3 x i64]
  store [3 x i64] %t37, ptr %t38
  %t39 = getelementptr inbounds { i1, i64 }, ptr %l14_current, i32 0, i32 1
  %t40 = load i64, ptr %t39
  %t41 = call i64 @ql_3_offset(i64 %t40)
  %t42 = getelementptr inbounds [3 x i64], ptr %t38, i64 0, i64 %t41
  %t43 = load i64, ptr %t42
  %t44 = call i1 @ql_5_matches(i64 %t43, i64 4)
  br i1 %t44, label %bb9, label %bb10
bb6:
  %t45 = load { i1, i64 }, ptr %l8__t5
  store { i1, i64 } %t45, ptr %l9_current
  store i64 12, ptr %l6__t3
  br label %bb5
bb7:
  store i64 0, ptr %l6__t3
  br label %bb5
bb8:
  %t46 = load i64, ptr %l11__t6
  store i64 %t46, ptr %l15_third
  %t47 = load i64, ptr %l5_first
  %t48 = load i64, ptr %l10_second
  %t49 = add i64 %t47, %t48
  store i64 %t49, ptr %l16__t9
  %t50 = load i64, ptr %l16__t9
  %t51 = load i64, ptr %l15_third
  %t52 = add i64 %t50, %t51
  store i64 %t52, ptr %l17__t10
  %t53 = load i64, ptr %l17__t10
  store i64 %t53, ptr %l0__return
  br label %bb1
bb9:
  %t54 = load { i1, i64 }, ptr %l13__t8
  store { i1, i64 } %t54, ptr %l14_current
  store i64 20, ptr %l11__t6
  br label %bb8
bb10:
  store i64 0, ptr %l11__t6
  br label %bb8
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_6_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
