; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'match_guard_call_projection_roots'
source_filename = "match_guard_call_projection_roots.ql"
target triple = "x86_64-pc-windows-msvc"

define { i64, i64 } @ql_1_pair(i64 %arg0) {
entry:
  %l0__return = alloca { i64, i64 }
  %l1_value = alloca i64
  %l2__t0 = alloca { i64, i64 }
  store i64 %arg0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  %t1 = insertvalue { i64, i64 } undef, i64 0, 0
  %t2 = insertvalue { i64, i64 } %t1, i64 %t0, 1
  store { i64, i64 } %t2, ptr %l2__t0
  %t3 = load { i64, i64 }, ptr %l2__t0
  store { i64, i64 } %t3, ptr %l0__return
  br label %bb1
bb1:
  %t4 = load { i64, i64 }, ptr %l0__return
  ret { i64, i64 } %t4
}

define { i64 } @ql_2_state(i64 %arg0) {
entry:
  %l0__return = alloca { i64 }
  %l1_value = alloca i64
  %l2__t0 = alloca { i64 }
  store i64 %arg0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  %t1 = insertvalue { i64 } undef, i64 %t0, 0
  store { i64 } %t1, ptr %l2__t0
  %t2 = load { i64 }, ptr %l2__t0
  store { i64 } %t2, ptr %l0__return
  br label %bb1
bb1:
  %t3 = load { i64 }, ptr %l0__return
  ret { i64 } %t3
}

define [3 x i64] @ql_3_values(i64 %arg0) {
entry:
  %l0__return = alloca [3 x i64]
  %l1_seed = alloca i64
  %l2__t0 = alloca i64
  %l3__t1 = alloca i64
  %l4__t2 = alloca [3 x i64]
  store i64 %arg0, ptr %l1_seed
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_seed
  %t1 = add i64 %t0, 1
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l1_seed
  %t3 = add i64 %t2, 2
  store i64 %t3, ptr %l3__t1
  %t4 = load i64, ptr %l1_seed
  %t5 = load i64, ptr %l2__t0
  %t6 = load i64, ptr %l3__t1
  %t7 = insertvalue [3 x i64] undef, i64 %t4, 0
  %t8 = insertvalue [3 x i64] %t7, i64 %t5, 1
  %t9 = insertvalue [3 x i64] %t8, i64 %t6, 2
  store [3 x i64] %t9, ptr %l4__t2
  %t10 = load [3 x i64], ptr %l4__t2
  store [3 x i64] %t10, ptr %l0__return
  br label %bb1
bb1:
  %t11 = load [3 x i64], ptr %l0__return
  ret [3 x i64] %t11
}

define i64 @ql_4_main() {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca i64
  %l2__t1 = alloca i64
  %l3_current = alloca i64
  %l4_first = alloca i64
  %l5__t2 = alloca i64
  %l6__t3 = alloca i64
  %l7_current = alloca i64
  %l8_second = alloca i64
  %l9__t4 = alloca i64
  %l10__t5 = alloca i64
  %l11_current = alloca i64
  %l12_third = alloca i64
  %l13__t6 = alloca i64
  %l14__t7 = alloca i64
  br label %bb0
bb0:
  store i64 22, ptr %l2__t1
  %t0 = load i64, ptr %l2__t1
  br label %bb0_match_guard0
bb0_match_guard0:
  store i64 %t0, ptr %l3_current
  %t1 = call { i64, i64 } @ql_1_pair(i64 %t0)
  %t2 = alloca { i64, i64 }
  store { i64, i64 } %t1, ptr %t2
  %t3 = getelementptr inbounds { i64, i64 }, ptr %t2, i32 0, i32 1
  %t4 = load i64, ptr %t3
  %t5 = icmp eq i64 %t4, 22
  br i1 %t5, label %bb3, label %bb4
bb1:
  %t6 = load i64, ptr %l0__return
  ret i64 %t6
bb2:
  %t7 = load i64, ptr %l1__t0
  store i64 %t7, ptr %l4_first
  store i64 12, ptr %l6__t3
  %t8 = load i64, ptr %l6__t3
  br label %bb2_match_guard0
bb2_match_guard0:
  store i64 %t8, ptr %l7_current
  %t9 = call { i64 } @ql_2_state(i64 %t8)
  %t10 = alloca { i64 }
  store { i64 } %t9, ptr %t10
  %t11 = getelementptr inbounds { i64 }, ptr %t10, i32 0, i32 0
  %t12 = load i64, ptr %t11
  %t13 = icmp eq i64 %t12, 12
  br i1 %t13, label %bb6, label %bb7
bb3:
  %t14 = load i64, ptr %l2__t1
  store i64 %t14, ptr %l3_current
  store i64 10, ptr %l1__t0
  br label %bb2
bb4:
  store i64 0, ptr %l1__t0
  br label %bb2
bb5:
  %t15 = load i64, ptr %l5__t2
  store i64 %t15, ptr %l8_second
  store i64 3, ptr %l10__t5
  %t16 = load i64, ptr %l10__t5
  br label %bb5_match_guard0
bb5_match_guard0:
  store i64 %t16, ptr %l11_current
  %t17 = call [3 x i64] @ql_3_values(i64 %t16)
  %t18 = alloca [3 x i64]
  store [3 x i64] %t17, ptr %t18
  %t19 = getelementptr inbounds [3 x i64], ptr %t18, i64 0, i64 1
  %t20 = load i64, ptr %t19
  %t21 = icmp eq i64 %t20, 4
  br i1 %t21, label %bb9, label %bb10
bb6:
  %t22 = load i64, ptr %l6__t3
  store i64 %t22, ptr %l7_current
  store i64 12, ptr %l5__t2
  br label %bb5
bb7:
  store i64 0, ptr %l5__t2
  br label %bb5
bb8:
  %t23 = load i64, ptr %l9__t4
  store i64 %t23, ptr %l12_third
  %t24 = load i64, ptr %l4_first
  %t25 = load i64, ptr %l8_second
  %t26 = add i64 %t24, %t25
  store i64 %t26, ptr %l13__t6
  %t27 = load i64, ptr %l13__t6
  %t28 = load i64, ptr %l12_third
  %t29 = add i64 %t27, %t28
  store i64 %t29, ptr %l14__t7
  %t30 = load i64, ptr %l14__t7
  store i64 %t30, ptr %l0__return
  br label %bb1
bb9:
  %t31 = load i64, ptr %l10__t5
  store i64 %t31, ptr %l11_current
  store i64 20, ptr %l9__t4
  br label %bb8
bb10:
  store i64 0, ptr %l9__t4
  br label %bb8
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_4_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
