; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'match_guard_inline_aggregate_call_args'
source_filename = "match_guard_inline_aggregate_call_args.ql"
target triple = "x86_64-pc-windows-msvc"

define i1 @ql_1_enabled({ i1 } %arg0) {
entry:
  %l0__return = alloca i1
  %l1_state = alloca { i1 }
  store { i1 } %arg0, ptr %l1_state
  br label %bb0
bb0:
  %t0 = getelementptr inbounds { i1 }, ptr %l1_state, i32 0, i32 0
  %t1 = load i1, ptr %t0
  store i1 %t1, ptr %l0__return
  br label %bb1
bb1:
  %t2 = load i1, ptr %l0__return
  ret i1 %t2
}

define i1 @ql_2_matches({ i64, i64 } %arg0, i64 %arg1) {
entry:
  %l0__return = alloca i1
  %l1_pair = alloca { i64, i64 }
  %l2_expected = alloca i64
  %l3__t0 = alloca i1
  store { i64, i64 } %arg0, ptr %l1_pair
  store i64 %arg1, ptr %l2_expected
  br label %bb0
bb0:
  %t0 = getelementptr inbounds { i64, i64 }, ptr %l1_pair, i32 0, i32 1
  %t1 = load i64, ptr %t0
  %t2 = load i64, ptr %l2_expected
  %t3 = icmp eq i64 %t1, %t2
  store i1 %t3, ptr %l3__t0
  %t4 = load i1, ptr %l3__t0
  store i1 %t4, ptr %l0__return
  br label %bb1
bb1:
  %t5 = load i1, ptr %l0__return
  ret i1 %t5
}

define i1 @ql_3_contains([3 x i64] %arg0, i64 %arg1) {
entry:
  %l0__return = alloca i1
  %l1_values = alloca [3 x i64]
  %l2_expected = alloca i64
  %l3__t0 = alloca i1
  store [3 x i64] %arg0, ptr %l1_values
  store i64 %arg1, ptr %l2_expected
  br label %bb0
bb0:
  %t0 = getelementptr inbounds [3 x i64], ptr %l1_values, i64 0, i64 1
  %t1 = load i64, ptr %t0
  %t2 = load i64, ptr %l2_expected
  %t3 = icmp eq i64 %t1, %t2
  store i1 %t3, ptr %l3__t0
  %t4 = load i1, ptr %l3__t0
  store i1 %t4, ptr %l0__return
  br label %bb1
bb1:
  %t5 = load i1, ptr %l0__return
  ret i1 %t5
}

define i64 @ql_4_main() {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca i64
  %l2__t1 = alloca i1
  %l3_first = alloca i64
  %l4__t2 = alloca i64
  %l5__t3 = alloca i64
  %l6_current = alloca i64
  %l7_second = alloca i64
  %l8__t4 = alloca i64
  %l9__t5 = alloca i64
  %l10_current = alloca i64
  %l11_third = alloca i64
  %l12__t6 = alloca i64
  %l13__t7 = alloca i64
  br label %bb0
bb0:
  store i1 true, ptr %l2__t1
  %t0 = load i1, ptr %l2__t1
  br i1 %t0, label %bb0_match_guard0, label %bb0_match_dispatch1
bb0_match_guard0:
  %t1 = insertvalue { i1 } undef, i1 true, 0
  %t2 = call i1 @ql_1_enabled({ i1 } %t1)
  br i1 %t2, label %bb3, label %bb0_match_dispatch1
bb0_match_dispatch1:
  br i1 %t0, label %bb2, label %bb4
bb1:
  %t3 = load i64, ptr %l0__return
  ret i64 %t3
bb2:
  %t4 = load i64, ptr %l1__t0
  store i64 %t4, ptr %l3_first
  store i64 22, ptr %l5__t3
  %t5 = load i64, ptr %l5__t3
  br label %bb2_match_guard0
bb2_match_guard0:
  store i64 %t5, ptr %l6_current
  %t6 = insertvalue { i64, i64 } undef, i64 0, 0
  %t7 = insertvalue { i64, i64 } %t6, i64 %t5, 1
  %t8 = call i1 @ql_2_matches({ i64, i64 } %t7, i64 22)
  br i1 %t8, label %bb6, label %bb7
bb3:
  store i64 10, ptr %l1__t0
  br label %bb2
bb4:
  store i64 0, ptr %l1__t0
  br label %bb2
bb5:
  %t9 = load i64, ptr %l4__t2
  store i64 %t9, ptr %l7_second
  store i64 3, ptr %l9__t5
  %t10 = load i64, ptr %l9__t5
  br label %bb5_match_guard0
bb5_match_guard0:
  store i64 %t10, ptr %l10_current
  %t11 = add i64 %t10, 1
  %t12 = add i64 %t10, 2
  %t13 = insertvalue [3 x i64] undef, i64 %t10, 0
  %t14 = insertvalue [3 x i64] %t13, i64 %t11, 1
  %t15 = insertvalue [3 x i64] %t14, i64 %t12, 2
  %t16 = call i1 @ql_3_contains([3 x i64] %t15, i64 4)
  br i1 %t16, label %bb9, label %bb10
bb6:
  %t17 = load i64, ptr %l5__t3
  store i64 %t17, ptr %l6_current
  store i64 12, ptr %l4__t2
  br label %bb5
bb7:
  store i64 0, ptr %l4__t2
  br label %bb5
bb8:
  %t18 = load i64, ptr %l8__t4
  store i64 %t18, ptr %l11_third
  %t19 = load i64, ptr %l3_first
  %t20 = load i64, ptr %l7_second
  %t21 = add i64 %t19, %t20
  store i64 %t21, ptr %l12__t6
  %t22 = load i64, ptr %l12__t6
  %t23 = load i64, ptr %l11_third
  %t24 = add i64 %t22, %t23
  store i64 %t24, ptr %l13__t7
  %t25 = load i64, ptr %l13__t7
  store i64 %t25, ptr %l0__return
  br label %bb1
bb9:
  %t26 = load i64, ptr %l9__t5
  store i64 %t26, ptr %l10_current
  store i64 20, ptr %l8__t4
  br label %bb8
bb10:
  store i64 0, ptr %l8__t4
  br label %bb8
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_4_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
