; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'negated_bool_guard_match'
source_filename = "negated_bool_guard_match.ql"
target triple = "x86_64-pc-windows-msvc"

define i64 @ql_3_main() {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %l2__t0 = alloca { i1 }
  %l3__t1 = alloca [2 x i1]
  %l4__t2 = alloca { { i1 }, [2 x i1] }
  %l5_state = alloca { { i1 }, [2 x i1] }
  %l6__t3 = alloca i1
  %l7_open = alloca i1
  %l8__t4 = alloca i64
  %l9__t5 = alloca i64
  br label %bb0
bb0:
  store i64 3, ptr %l1_value
  %t0 = insertvalue { i1 } undef, i1 false, 0
  store { i1 } %t0, ptr %l2__t0
  %t1 = insertvalue [2 x i1] undef, i1 true, 0
  %t2 = insertvalue [2 x i1] %t1, i1 false, 1
  store [2 x i1] %t2, ptr %l3__t1
  %t3 = load { i1 }, ptr %l2__t0
  %t4 = load [2 x i1], ptr %l3__t1
  %t5 = insertvalue { { i1 }, [2 x i1] } undef, { i1 } %t3, 0
  %t6 = insertvalue { { i1 }, [2 x i1] } %t5, [2 x i1] %t4, 1
  store { { i1 }, [2 x i1] } %t6, ptr %l4__t2
  %t7 = load { { i1 }, [2 x i1] }, ptr %l4__t2
  store { { i1 }, [2 x i1] } %t7, ptr %l5_state
  %t8 = getelementptr inbounds { { i1 }, [2 x i1] }, ptr %l5_state, i32 0, i32 0
  %t9 = getelementptr inbounds { i1 }, ptr %t8, i32 0, i32 0
  %t10 = load i1, ptr %t9
  %t11 = xor i1 %t10, true
  store i1 %t11, ptr %l6__t3
  %t12 = load i1, ptr %l6__t3
  store i1 %t12, ptr %l7_open
  %t13 = load i64, ptr %l1_value
  store i64 %t13, ptr %l9__t5
  %t14 = load i64, ptr %l9__t5
  %t15 = icmp eq i64 %t14, 1
  br i1 %t15, label %bb3, label %bb0_match_dispatch1
bb0_match_dispatch1:
  %t16 = icmp eq i64 %t14, 2
  br i1 %t16, label %bb4, label %bb0_match_dispatch2
bb0_match_dispatch2:
  %t17 = icmp eq i64 %t14, 3
  br i1 %t17, label %bb0_match_guard2, label %bb6
bb0_match_guard2:
  %t18 = load i1, ptr %l7_open
  %t19 = icmp eq i1 %t18, false
  %t20 = xor i1 %t19, true
  br i1 %t20, label %bb5, label %bb6
bb1:
  %t21 = load i64, ptr %l0__return
  ret i64 %t21
bb2:
  %t22 = load i64, ptr %l8__t4
  store i64 %t22, ptr %l0__return
  br label %bb1
bb3:
  store i64 10, ptr %l8__t4
  br label %bb2
bb4:
  store i64 20, ptr %l8__t4
  br label %bb2
bb5:
  store i64 30, ptr %l8__t4
  br label %bb2
bb6:
  store i64 0, ptr %l8__t4
  br label %bb2
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_3_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
