; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'nested_projection_reads'
source_filename = "nested_projection_reads.ql"
target triple = "{{TARGET_TRIPLE}}"

define i64 @ql_2_pick_pair({ { i64, i64 }, [2 x i64] } %arg0) {
entry:
  %l0__return = alloca i64
  %l1_outer = alloca { { i64, i64 }, [2 x i64] }
  store { { i64, i64 }, [2 x i64] } %arg0, ptr %l1_outer
  br label %bb0
bb0:
  %t0 = getelementptr inbounds { { i64, i64 }, [2 x i64] }, ptr %l1_outer, i32 0, i32 0
  %t1 = getelementptr inbounds { i64, i64 }, ptr %t0, i32 0, i32 1
  %t2 = load i64, ptr %t1
  store i64 %t2, ptr %l0__return
  br label %bb1
bb1:
  %t3 = load i64, ptr %l0__return
  ret i64 %t3
}

define i64 @ql_3_pick_array({ { i64, i64 }, [2 x i64] } %arg0, i64 %arg1) {
entry:
  %l0__return = alloca i64
  %l1_outer = alloca { { i64, i64 }, [2 x i64] }
  %l2_index = alloca i64
  store { { i64, i64 }, [2 x i64] } %arg0, ptr %l1_outer
  store i64 %arg1, ptr %l2_index
  br label %bb0
bb0:
  %t0 = getelementptr inbounds { { i64, i64 }, [2 x i64] }, ptr %l1_outer, i32 0, i32 1
  %t1 = load i64, ptr %l2_index
  %t2 = getelementptr inbounds [2 x i64], ptr %t0, i64 0, i64 %t1
  %t3 = load i64, ptr %t2
  store i64 %t3, ptr %l0__return
  br label %bb1
bb1:
  %t4 = load i64, ptr %l0__return
  ret i64 %t4
}

define i64 @ql_4_main() {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca { i64, i64 }
  %l2__t1 = alloca [2 x i64]
  %l3__t2 = alloca { { i64, i64 }, [2 x i64] }
  %l4_outer = alloca { { i64, i64 }, [2 x i64] }
  %l5__t3 = alloca i64
  %l6__t4 = alloca i64
  %l7__t5 = alloca i64
  br label %bb0
bb0:
  %t0 = insertvalue { i64, i64 } undef, i64 1, 0
  %t1 = insertvalue { i64, i64 } %t0, i64 2, 1
  store { i64, i64 } %t1, ptr %l1__t0
  %t2 = insertvalue [2 x i64] undef, i64 3, 0
  %t3 = insertvalue [2 x i64] %t2, i64 4, 1
  store [2 x i64] %t3, ptr %l2__t1
  %t4 = load { i64, i64 }, ptr %l1__t0
  %t5 = load [2 x i64], ptr %l2__t1
  %t6 = insertvalue { { i64, i64 }, [2 x i64] } undef, { i64, i64 } %t4, 0
  %t7 = insertvalue { { i64, i64 }, [2 x i64] } %t6, [2 x i64] %t5, 1
  store { { i64, i64 }, [2 x i64] } %t7, ptr %l3__t2
  %t8 = load { { i64, i64 }, [2 x i64] }, ptr %l3__t2
  store { { i64, i64 }, [2 x i64] } %t8, ptr %l4_outer
  %t9 = load { { i64, i64 }, [2 x i64] }, ptr %l4_outer
  %t10 = call i64 @ql_2_pick_pair({ { i64, i64 }, [2 x i64] } %t9)
  store i64 %t10, ptr %l5__t3
  %t11 = load { { i64, i64 }, [2 x i64] }, ptr %l4_outer
  %t12 = call i64 @ql_3_pick_array({ { i64, i64 }, [2 x i64] } %t11, i64 1)
  store i64 %t12, ptr %l6__t4
  %t13 = load i64, ptr %l5__t3
  %t14 = load i64, ptr %l6__t4
  %t15 = add i64 %t13, %t14
  store i64 %t15, ptr %l7__t5
  %t16 = load i64, ptr %l7__t5
  store i64 %t16, ptr %l0__return
  br label %bb1
bb1:
  %t17 = load i64, ptr %l0__return
  ret i64 %t17
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_4_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
