; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'nested_call_root_fixed_shapes'
source_filename = "nested_call_root_fixed_shapes.ql"
target triple = "x86_64-pc-windows-msvc"

define { { [2 x i64] } } @ql_5_array_env(i64 %arg0) {
entry:
  %l0__return = alloca { { [2 x i64] } }
  %l1_base = alloca i64
  %l2__t0 = alloca [2 x i64]
  %l3__t1 = alloca { [2 x i64] }
  %l4__t2 = alloca { { [2 x i64] } }
  store i64 %arg0, ptr %l1_base
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_base
  %t1 = load i64, ptr %l1_base
  %t2 = insertvalue [2 x i64] undef, i64 %t0, 0
  %t3 = insertvalue [2 x i64] %t2, i64 %t1, 1
  store [2 x i64] %t3, ptr %l2__t0
  %t4 = load [2 x i64], ptr %l2__t0
  %t5 = insertvalue { [2 x i64] } undef, [2 x i64] %t4, 0
  store { [2 x i64] } %t5, ptr %l3__t1
  %t6 = load { [2 x i64] }, ptr %l3__t1
  %t7 = insertvalue { { [2 x i64] } } undef, { [2 x i64] } %t6, 0
  store { { [2 x i64] } } %t7, ptr %l4__t2
  %t8 = load { { [2 x i64] } }, ptr %l4__t2
  store { { [2 x i64] } } %t8, ptr %l0__return
  br label %bb1
bb1:
  %t9 = load { { [2 x i64] } }, ptr %l0__return
  ret { { [2 x i64] } } %t9
}

define { { { i64, i64 } } } @ql_6_tuple_env(i64 %arg0) {
entry:
  %l0__return = alloca { { { i64, i64 } } }
  %l1_base = alloca i64
  %l2__t0 = alloca i64
  %l3__t1 = alloca { i64, i64 }
  %l4__t2 = alloca { { i64, i64 } }
  %l5__t3 = alloca { { { i64, i64 } } }
  store i64 %arg0, ptr %l1_base
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_base
  %t1 = add i64 %t0, 1
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l1_base
  %t3 = load i64, ptr %l2__t0
  %t4 = insertvalue { i64, i64 } undef, i64 %t2, 0
  %t5 = insertvalue { i64, i64 } %t4, i64 %t3, 1
  store { i64, i64 } %t5, ptr %l3__t1
  %t6 = load { i64, i64 }, ptr %l3__t1
  %t7 = insertvalue { { i64, i64 } } undef, { i64, i64 } %t6, 0
  store { { i64, i64 } } %t7, ptr %l4__t2
  %t8 = load { { i64, i64 } }, ptr %l4__t2
  %t9 = insertvalue { { { i64, i64 } } } undef, { { i64, i64 } } %t8, 0
  store { { { i64, i64 } } } %t9, ptr %l5__t3
  %t10 = load { { { i64, i64 } } }, ptr %l5__t3
  store { { { i64, i64 } } } %t10, ptr %l0__return
  br label %bb1
bb1:
  %t11 = load { { { i64, i64 } } }, ptr %l0__return
  ret { { { i64, i64 } } } %t11
}

define { { { [2 x i64] } } } @ql_7_deep_env(i64 %arg0) {
entry:
  %l0__return = alloca { { { [2 x i64] } } }
  %l1_base = alloca i64
  %l2__t0 = alloca i64
  %l3__t1 = alloca [2 x i64]
  %l4__t2 = alloca { [2 x i64] }
  %l5__t3 = alloca { { [2 x i64] } }
  %l6__t4 = alloca { { { [2 x i64] } } }
  store i64 %arg0, ptr %l1_base
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_base
  %t1 = add i64 %t0, 1
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l1_base
  %t3 = load i64, ptr %l2__t0
  %t4 = insertvalue [2 x i64] undef, i64 %t2, 0
  %t5 = insertvalue [2 x i64] %t4, i64 %t3, 1
  store [2 x i64] %t5, ptr %l3__t1
  %t6 = load [2 x i64], ptr %l3__t1
  %t7 = insertvalue { [2 x i64] } undef, [2 x i64] %t6, 0
  store { [2 x i64] } %t7, ptr %l4__t2
  %t8 = load { [2 x i64] }, ptr %l4__t2
  %t9 = insertvalue { { [2 x i64] } } undef, { [2 x i64] } %t8, 0
  store { { [2 x i64] } } %t9, ptr %l5__t3
  %t10 = load { { [2 x i64] } }, ptr %l5__t3
  %t11 = insertvalue { { { [2 x i64] } } } undef, { { [2 x i64] } } %t10, 0
  store { { { [2 x i64] } } } %t11, ptr %l6__t4
  %t12 = load { { { [2 x i64] } } }, ptr %l6__t4
  store { { { [2 x i64] } } } %t12, ptr %l0__return
  br label %bb1
bb1:
  %t13 = load { { { [2 x i64] } } }, ptr %l0__return
  ret { { { [2 x i64] } } } %t13
}

define i64 @ql_8_main() {
entry:
  %l0__return = alloca i64
  %l1_total = alloca i64
  %l2__t0 = alloca { { [2 x i64] } }
  %l3__t1 = alloca { { [2 x i64] } }
  %l4__t2 = alloca i64
  %l5_value = alloca i64
  %l6__t3 = alloca i64
  %l7__t4 = alloca { { { i64, i64 } } }
  %l8__t5 = alloca { { { i64, i64 } } }
  %l9__t6 = alloca i64
  %l10_value = alloca i64
  %l11__t7 = alloca i64
  %l12__t8 = alloca { { { [2 x i64] } } }
  %l13__t9 = alloca { { { [2 x i64] } } }
  %l14__t10 = alloca i64
  %l15_value = alloca i64
  %l16__t11 = alloca i64
  %for_await_index_bb2 = alloca i64
  %for_await_index_bb5 = alloca i64
  %for_await_index_bb8 = alloca i64
  store i64 -1, ptr %for_await_index_bb2
  store i64 -1, ptr %for_await_index_bb5
  store i64 -1, ptr %for_await_index_bb8
  br label %bb0
bb0:
  store i64 0, ptr %l1_total
  %t0 = call { { [2 x i64] } } @ql_5_array_env(i64 10)
  store { { [2 x i64] } } %t0, ptr %l2__t0
  %t1 = load { { [2 x i64] } }, ptr %l2__t0
  store { { [2 x i64] } } %t1, ptr %l3__t1
  %t2 = load i64, ptr %for_await_index_bb2
  %t3 = add i64 %t2, 1
  store i64 %t3, ptr %for_await_index_bb2
  br label %bb2
bb1:
  %t4 = load i64, ptr %l0__return
  ret i64 %t4
bb2:
  %t5 = load i64, ptr %for_await_index_bb2
  %t6 = icmp ult i64 %t5, 2
  br i1 %t6, label %bb2_for_await_setup, label %bb4
bb3:
  %t7 = load i64, ptr %l4__t2
  store i64 %t7, ptr %l5_value
  %t8 = load i64, ptr %l1_total
  %t9 = load i64, ptr %l5_value
  %t10 = add i64 %t8, %t9
  store i64 %t10, ptr %l6__t3
  %t11 = load i64, ptr %l6__t3
  store i64 %t11, ptr %l1_total
  %t12 = load i64, ptr %for_await_index_bb2
  %t13 = add i64 %t12, 1
  store i64 %t13, ptr %for_await_index_bb2
  br label %bb2
bb4:
  %t14 = call { { { i64, i64 } } } @ql_6_tuple_env(i64 7)
  store { { { i64, i64 } } } %t14, ptr %l7__t4
  %t15 = load { { { i64, i64 } } }, ptr %l7__t4
  store { { { i64, i64 } } } %t15, ptr %l8__t5
  %t16 = load i64, ptr %for_await_index_bb5
  %t17 = add i64 %t16, 1
  store i64 %t17, ptr %for_await_index_bb5
  br label %bb5
bb5:
  %t18 = load i64, ptr %for_await_index_bb5
  %t19 = icmp ult i64 %t18, 2
  br i1 %t19, label %bb5_for_await_setup, label %bb7
bb6:
  %t20 = load i64, ptr %l9__t6
  store i64 %t20, ptr %l10_value
  %t21 = load i64, ptr %l1_total
  %t22 = load i64, ptr %l10_value
  %t23 = add i64 %t21, %t22
  store i64 %t23, ptr %l11__t7
  %t24 = load i64, ptr %l11__t7
  store i64 %t24, ptr %l1_total
  %t25 = load i64, ptr %for_await_index_bb5
  %t26 = add i64 %t25, 1
  store i64 %t26, ptr %for_await_index_bb5
  br label %bb5
bb7:
  %t27 = call { { { [2 x i64] } } } @ql_7_deep_env(i64 3)
  store { { { [2 x i64] } } } %t27, ptr %l12__t8
  %t28 = load { { { [2 x i64] } } }, ptr %l12__t8
  store { { { [2 x i64] } } } %t28, ptr %l13__t9
  %t29 = load i64, ptr %for_await_index_bb8
  %t30 = add i64 %t29, 1
  store i64 %t30, ptr %for_await_index_bb8
  br label %bb8
bb8:
  %t31 = load i64, ptr %for_await_index_bb8
  %t32 = icmp ult i64 %t31, 2
  br i1 %t32, label %bb8_for_await_setup, label %bb10
bb9:
  %t33 = load i64, ptr %l14__t10
  store i64 %t33, ptr %l15_value
  %t34 = load i64, ptr %l1_total
  %t35 = load i64, ptr %l15_value
  %t36 = add i64 %t34, %t35
  store i64 %t36, ptr %l16__t11
  %t37 = load i64, ptr %l16__t11
  store i64 %t37, ptr %l1_total
  %t38 = load i64, ptr %for_await_index_bb8
  %t39 = add i64 %t38, 1
  store i64 %t39, ptr %for_await_index_bb8
  br label %bb8
bb10:
  %t40 = load i64, ptr %l1_total
  store i64 %t40, ptr %l0__return
  br label %bb1
bb2_for_await_setup:
  %t41 = load i64, ptr %for_await_index_bb2
  %t42 = getelementptr inbounds { { [2 x i64] } }, ptr %l3__t1, i32 0, i32 0
  %t43 = getelementptr inbounds { [2 x i64] }, ptr %t42, i32 0, i32 0
  %t44 = getelementptr inbounds [2 x i64], ptr %t43, i64 0, i64 %t41
  %t45 = load i64, ptr %t44
  store i64 %t45, ptr %l4__t2
  br label %bb3
bb5_for_await_setup:
  %t46 = load i64, ptr %for_await_index_bb5
  %t47 = getelementptr inbounds { { { i64, i64 } } }, ptr %l8__t5, i32 0, i32 0
  %t48 = getelementptr inbounds { { i64, i64 } }, ptr %t47, i32 0, i32 0
  %t49 = icmp eq i64 %t46, 0
  br i1 %t49, label %bb5_for_await_tuple_item_0, label %bb5_for_await_tuple_check_1
bb5_for_await_tuple_check_1:
  br label %bb5_for_await_tuple_item_1
bb5_for_await_tuple_item_0:
  %t50 = getelementptr inbounds { i64, i64 }, ptr %t48, i32 0, i32 0
  %t51 = load i64, ptr %t50
  store i64 %t51, ptr %l9__t6
  br label %bb6
bb5_for_await_tuple_item_1:
  %t52 = getelementptr inbounds { i64, i64 }, ptr %t48, i32 0, i32 1
  %t53 = load i64, ptr %t52
  store i64 %t53, ptr %l9__t6
  br label %bb6
bb8_for_await_setup:
  %t54 = load i64, ptr %for_await_index_bb8
  %t55 = getelementptr inbounds { { { [2 x i64] } } }, ptr %l13__t9, i32 0, i32 0
  %t56 = getelementptr inbounds { { [2 x i64] } }, ptr %t55, i32 0, i32 0
  %t57 = getelementptr inbounds { [2 x i64] }, ptr %t56, i32 0, i32 0
  %t58 = getelementptr inbounds [2 x i64], ptr %t57, i64 0, i64 %t54
  %t59 = load i64, ptr %t58
  store i64 %t59, ptr %l14__t10
  br label %bb9
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_8_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
