; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'non_capturing_closure_build'
source_filename = "non_capturing_closure_build.ql"
target triple = "x86_64-pc-windows-msvc"

define i64 @ql_0_main() {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca ptr
  %l2_run = alloca ptr
  %l3__t1 = alloca i64
  br label %bb0
bb0:
  store ptr @ql_0_main__closure0, ptr %l1__t0
  %t0 = load ptr, ptr %l1__t0
  store ptr %t0, ptr %l2_run
  %t1 = load ptr, ptr %l2_run
  %t2 = call i64 %t1()
  store i64 %t2, ptr %l3__t1
  %t3 = load i64, ptr %l3__t1
  store i64 %t3, ptr %l0__return
  br label %bb1
bb1:
  %t4 = load i64, ptr %l0__return
  ret i64 %t4
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_0_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}

define i64 @ql_0_main__closure0() {
entry:
  %l0__return = alloca i64
  br label %bb0
bb0:
  store i64 41, ptr %l0__return
  br label %bb1
bb1:
  %t0 = load i64, ptr %l0__return
  ret i64 %t0
}
