; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'projection_reads'
source_filename = "projection_reads.ql"
target triple = "{{TARGET_TRIPLE}}"

define i64 @ql_1_pick_struct({ i1, i64 } %arg0) {
entry:
  %l0__return = alloca i64
  %l1_pair = alloca { i1, i64 }
  store { i1, i64 } %arg0, ptr %l1_pair
  br label %bb0
bb0:
  %t0 = getelementptr inbounds { i1, i64 }, ptr %l1_pair, i32 0, i32 1
  %t1 = load i64, ptr %t0
  store i64 %t1, ptr %l0__return
  br label %bb1
bb1:
  %t2 = load i64, ptr %l0__return
  ret i64 %t2
}

define i64 @ql_2_pick_tuple({ i1, i64 } %arg0) {
entry:
  %l0__return = alloca i64
  %l1_pair = alloca { i1, i64 }
  store { i1, i64 } %arg0, ptr %l1_pair
  br label %bb0
bb0:
  %t0 = getelementptr inbounds { i1, i64 }, ptr %l1_pair, i32 0, i32 1
  %t1 = load i64, ptr %t0
  store i64 %t1, ptr %l0__return
  br label %bb1
bb1:
  %t2 = load i64, ptr %l0__return
  ret i64 %t2
}

define i64 @ql_3_pick_array([3 x i64] %arg0, i64 %arg1) {
entry:
  %l0__return = alloca i64
  %l1_values = alloca [3 x i64]
  %l2_index = alloca i64
  store [3 x i64] %arg0, ptr %l1_values
  store i64 %arg1, ptr %l2_index
  br label %bb0
bb0:
  %t0 = load i64, ptr %l2_index
  %t1 = getelementptr inbounds [3 x i64], ptr %l1_values, i64 0, i64 %t0
  %t2 = load i64, ptr %t1
  store i64 %t2, ptr %l0__return
  br label %bb1
bb1:
  %t3 = load i64, ptr %l0__return
  ret i64 %t3
}

define i64 @ql_4_main() {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca { i1, i64 }
  %l2_pair = alloca { i1, i64 }
  %l3__t1 = alloca { i1, i64 }
  %l4_tuple = alloca { i1, i64 }
  %l5__t2 = alloca [3 x i64]
  %l6_values = alloca [3 x i64]
  %l7__t3 = alloca i64
  %l8__t4 = alloca i64
  %l9__t5 = alloca i64
  %l10__t6 = alloca i64
  %l11__t7 = alloca i64
  br label %bb0
bb0:
  %t0 = insertvalue { i1, i64 } undef, i1 false, 0
  %t1 = insertvalue { i1, i64 } %t0, i64 7, 1
  store { i1, i64 } %t1, ptr %l1__t0
  %t2 = load { i1, i64 }, ptr %l1__t0
  store { i1, i64 } %t2, ptr %l2_pair
  %t3 = insertvalue { i1, i64 } undef, i1 true, 0
  %t4 = insertvalue { i1, i64 } %t3, i64 5, 1
  store { i1, i64 } %t4, ptr %l3__t1
  %t5 = load { i1, i64 }, ptr %l3__t1
  store { i1, i64 } %t5, ptr %l4_tuple
  %t6 = insertvalue [3 x i64] undef, i64 1, 0
  %t7 = insertvalue [3 x i64] %t6, i64 2, 1
  %t8 = insertvalue [3 x i64] %t7, i64 3, 2
  store [3 x i64] %t8, ptr %l5__t2
  %t9 = load [3 x i64], ptr %l5__t2
  store [3 x i64] %t9, ptr %l6_values
  %t10 = load { i1, i64 }, ptr %l2_pair
  %t11 = call i64 @ql_1_pick_struct({ i1, i64 } %t10)
  store i64 %t11, ptr %l7__t3
  %t12 = load { i1, i64 }, ptr %l4_tuple
  %t13 = call i64 @ql_2_pick_tuple({ i1, i64 } %t12)
  store i64 %t13, ptr %l8__t4
  %t14 = load i64, ptr %l7__t3
  %t15 = load i64, ptr %l8__t4
  %t16 = add i64 %t14, %t15
  store i64 %t16, ptr %l9__t5
  %t17 = load [3 x i64], ptr %l6_values
  %t18 = call i64 @ql_3_pick_array([3 x i64] %t17, i64 1)
  store i64 %t18, ptr %l10__t6
  %t19 = load i64, ptr %l9__t5
  %t20 = load i64, ptr %l10__t6
  %t21 = add i64 %t19, %t20
  store i64 %t21, ptr %l11__t7
  %t22 = load i64, ptr %l11__t7
  store i64 %t22, ptr %l0__return
  br label %bb1
bb1:
  %t23 = load i64, ptr %l0__return
  ret i64 %t23
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_4_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
