; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'projected_integer_comparison_guard_match'
source_filename = "projected_integer_comparison_guard_match.ql"
target triple = "x86_64-pc-windows-msvc"

define i64 @ql_2_main() {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %l2__t0 = alloca { i64 }
  %l3__t1 = alloca { i64, i64 }
  %l4__t2 = alloca [2 x i64]
  %l5__t3 = alloca { { i64 }, { i64, i64 }, [2 x i64] }
  %l6_state = alloca { { i64 }, { i64, i64 }, [2 x i64] }
  %l7__t4 = alloca i64
  %l8__t5 = alloca i64
  br label %bb0
bb0:
  store i64 3, ptr %l1_value
  %t0 = insertvalue { i64 } undef, i64 2, 0
  store { i64 } %t0, ptr %l2__t0
  %t1 = insertvalue { i64, i64 } undef, i64 0, 0
  %t2 = insertvalue { i64, i64 } %t1, i64 1, 1
  store { i64, i64 } %t2, ptr %l3__t1
  %t3 = insertvalue [2 x i64] undef, i64 1, 0
  %t4 = insertvalue [2 x i64] %t3, i64 4, 1
  store [2 x i64] %t4, ptr %l4__t2
  %t5 = load { i64 }, ptr %l2__t0
  %t6 = load { i64, i64 }, ptr %l3__t1
  %t7 = load [2 x i64], ptr %l4__t2
  %t8 = insertvalue { { i64 }, { i64, i64 }, [2 x i64] } undef, { i64 } %t5, 0
  %t9 = insertvalue { { i64 }, { i64, i64 }, [2 x i64] } %t8, { i64, i64 } %t6, 1
  %t10 = insertvalue { { i64 }, { i64, i64 }, [2 x i64] } %t9, [2 x i64] %t7, 2
  store { { i64 }, { i64, i64 }, [2 x i64] } %t10, ptr %l5__t3
  %t11 = load { { i64 }, { i64, i64 }, [2 x i64] }, ptr %l5__t3
  store { { i64 }, { i64, i64 }, [2 x i64] } %t11, ptr %l6_state
  %t12 = load i64, ptr %l1_value
  store i64 %t12, ptr %l8__t5
  %t13 = load i64, ptr %l8__t5
  %t14 = icmp eq i64 %t13, 3
  br i1 %t14, label %bb0_match_guard0, label %bb0_match_dispatch1
bb0_match_guard0:
  %t15 = getelementptr inbounds { { i64 }, { i64, i64 }, [2 x i64] }, ptr %l6_state, i32 0, i32 1
  %t16 = getelementptr inbounds { i64, i64 }, ptr %t15, i32 0, i32 1
  %t17 = load i64, ptr %t16
  %t18 = getelementptr inbounds { { i64 }, { i64, i64 }, [2 x i64] }, ptr %l6_state, i32 0, i32 0
  %t19 = getelementptr inbounds { i64 }, ptr %t18, i32 0, i32 0
  %t20 = load i64, ptr %t19
  %t21 = icmp eq i64 %t17, %t20
  br i1 %t21, label %bb3, label %bb0_match_dispatch1
bb0_match_dispatch1:
  %t22 = icmp eq i64 %t13, 3
  br i1 %t22, label %bb0_match_guard1, label %bb5
bb0_match_guard1:
  %t23 = getelementptr inbounds { { i64 }, { i64, i64 }, [2 x i64] }, ptr %l6_state, i32 0, i32 2
  %t24 = getelementptr inbounds [2 x i64], ptr %t23, i64 0, i64 0
  %t25 = load i64, ptr %t24
  %t26 = getelementptr inbounds { { i64 }, { i64, i64 }, [2 x i64] }, ptr %l6_state, i32 0, i32 0
  %t27 = getelementptr inbounds { i64 }, ptr %t26, i32 0, i32 0
  %t28 = load i64, ptr %t27
  %t29 = icmp slt i64 %t25, %t28
  br i1 %t29, label %bb4, label %bb5
bb1:
  %t30 = load i64, ptr %l0__return
  ret i64 %t30
bb2:
  %t31 = load i64, ptr %l7__t4
  store i64 %t31, ptr %l0__return
  br label %bb1
bb3:
  store i64 30, ptr %l7__t4
  br label %bb2
bb4:
  store i64 31, ptr %l7__t4
  br label %bb2
bb5:
  store i64 0, ptr %l7__t4
  br label %bb2
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_2_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}
