; generated by ql-codegen-llvm P4 backend foundation
; ModuleID = 'typed_non_capturing_param_closure_build'
source_filename = "typed_non_capturing_param_closure_build.ql"
target triple = "x86_64-pc-windows-msvc"

define i64 @ql_0_main() {
entry:
  %l0__return = alloca i64
  %l1__t0 = alloca ptr
  %l2_run = alloca ptr
  %l3_alias = alloca ptr
  %l4__t1 = alloca i64
  br label %bb0
bb0:
  store ptr @ql_0_main__closure0, ptr %l1__t0
  %t0 = load ptr, ptr %l1__t0
  store ptr %t0, ptr %l2_run
  %t1 = load ptr, ptr %l2_run
  store ptr %t1, ptr %l3_alias
  %t2 = load ptr, ptr %l3_alias
  %t3 = call i64 %t2(i64 41)
  store i64 %t3, ptr %l4__t1
  %t4 = load i64, ptr %l4__t1
  store i64 %t4, ptr %l0__return
  br label %bb1
bb1:
  %t5 = load i64, ptr %l0__return
  ret i64 %t5
}

define i32 @main() {
entry:
  %entry_ret = call i64 @ql_0_main()
  %entry_exit = trunc i64 %entry_ret to i32
  ret i32 %entry_exit
}

define i64 @ql_0_main__closure0(i64 %arg0) {
entry:
  %l0__return = alloca i64
  %l1_value = alloca i64
  %l2__t0 = alloca i64
  store i64 %arg0, ptr %l1_value
  br label %bb0
bb0:
  %t0 = load i64, ptr %l1_value
  %t1 = add i64 %t0, 1
  store i64 %t1, ptr %l2__t0
  %t2 = load i64, ptr %l2__t0
  store i64 %t2, ptr %l0__return
  br label %bb1
bb1:
  %t3 = load i64, ptr %l0__return
  ret i64 %t3
}
