mod support;

use support::codegen::{FailCase, PassCase, run_fail_case, run_pass_case};
use support::workspace_root;

#[test]
fn codegen_snapshots_match() {
    let workspace_root = workspace_root();

    let pass_cases = vec![
        PassCase {
            name: "async_program_main_exe",
            source_relative: "fixtures/codegen/pass/async_program_main.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "for_array_exe",
            source_relative: "fixtures/codegen/pass/for_array.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "bool_match_exe",
            source_relative: "fixtures/codegen/pass/bool_match.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "integer_match_exe",
            source_relative: "fixtures/codegen/pass/integer_match.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "integer_dynamic_guard_match_exe",
            source_relative: "fixtures/codegen/pass/integer_dynamic_guard_match.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "integer_comparison_guard_match_exe",
            source_relative: "fixtures/codegen/pass/integer_comparison_guard_match.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "projected_integer_comparison_guard_match_exe",
            source_relative: "fixtures/codegen/pass/projected_integer_comparison_guard_match.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "const_projected_integer_comparison_guard_match_exe",
            source_relative: "fixtures/codegen/pass/const_projected_integer_comparison_guard_match.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "integer_dynamic_guard_catch_all_match_exe",
            source_relative: "fixtures/codegen/pass/integer_dynamic_guard_catch_all_match.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "integer_match_binding_exe",
            source_relative: "fixtures/codegen/pass/integer_match_binding.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "literal_guard_match_exe",
            source_relative: "fixtures/codegen/pass/literal_guard_match.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "const_guard_match_exe",
            source_relative: "fixtures/codegen/pass/const_guard_match.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "bool_dynamic_guard_match_exe",
            source_relative: "fixtures/codegen/pass/bool_dynamic_guard_match.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "negated_bool_guard_match_exe",
            source_relative: "fixtures/codegen/pass/negated_bool_guard_match.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "alias_const_guard_match_exe",
            source_relative: "fixtures/codegen/pass/alias_const_guard_match.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "match_guard_direct_calls_exe",
            source_relative: "fixtures/codegen/pass/match_guard_direct_calls.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "match_guard_call_projection_roots_exe",
            source_relative: "fixtures/codegen/pass/match_guard_call_projection_roots.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "match_guard_aggregate_call_args_exe",
            source_relative: "fixtures/codegen/pass/match_guard_aggregate_call_args.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "match_guard_inline_aggregate_call_args_exe",
            source_relative: "fixtures/codegen/pass/match_guard_inline_aggregate_call_args.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "match_guard_inline_projection_roots_exe",
            source_relative: "fixtures/codegen/pass/match_guard_inline_projection_roots.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "match_guard_item_backed_inline_combos_exe",
            source_relative: "fixtures/codegen/pass/match_guard_item_backed_inline_combos.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "match_guard_call_backed_combos_exe",
            source_relative: "fixtures/codegen/pass/match_guard_call_backed_combos.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "match_guard_call_root_nested_runtime_projection_exe",
            source_relative: "fixtures/codegen/pass/match_guard_call_root_nested_runtime_projection.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "match_guard_nested_call_root_inline_combos_exe",
            source_relative: "fixtures/codegen/pass/match_guard_nested_call_root_inline_combos.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "match_guard_item_backed_nested_call_root_combos_exe",
            source_relative: "fixtures/codegen/pass/match_guard_item_backed_nested_call_root_combos.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "match_guard_call_backed_nested_call_root_combos_exe",
            source_relative: "fixtures/codegen/pass/match_guard_call_backed_nested_call_root_combos.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "match_guard_alias_backed_nested_call_root_combos_exe",
            source_relative: "fixtures/codegen/pass/match_guard_alias_backed_nested_call_root_combos.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "match_guard_binding_backed_nested_call_root_combos_exe",
            source_relative: "fixtures/codegen/pass/match_guard_binding_backed_nested_call_root_combos.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "match_guard_projection_backed_nested_call_root_combos_exe",
            source_relative: "fixtures/codegen/pass/match_guard_projection_backed_nested_call_root_combos.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "for_call_root_fixed_shapes_exe",
            source_relative: "fixtures/codegen/pass/for_call_root_fixed_shapes.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "import_alias_call_root_fixed_shapes_exe",
            source_relative: "fixtures/codegen/pass/import_alias_call_root_fixed_shapes.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "nested_call_root_fixed_shapes_exe",
            source_relative: "fixtures/codegen/pass/nested_call_root_fixed_shapes.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "import_alias_nested_call_root_fixed_shapes_exe",
            source_relative: "fixtures/codegen/pass/import_alias_nested_call_root_fixed_shapes.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_for_await_array_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_for_await_array.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_nested_task_handle_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_nested_task_handle.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_task_handle_tuple_payload_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_task_handle_tuple_payload.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_task_handle_array_payload_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_task_handle_array_payload.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_nested_aggregate_task_handle_payload_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_nested_aggregate_task_handle_payload.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_helper_task_handle_flows_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_helper_task_handle_flows.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_zero_sized_helper_task_handle_flows_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_zero_sized_helper_task_handle_flows.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_local_return_task_handle_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_local_return_task_handle.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_direct_handle_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_direct_handle.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_spawn_bound_task_handle_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_spawn_bound_task_handle.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_local_return_zero_sized_task_handle_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_local_return_zero_sized_task_handle.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_zero_sized_aggregate_results_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_zero_sized_aggregate_results.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_spawn_zero_sized_aggregate_result_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_spawn_zero_sized_aggregate_result.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_aggregate_results_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_aggregate_results.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_spawned_aggregate_results_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_spawned_aggregate_results.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_recursive_aggregate_results_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_recursive_aggregate_results.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_spawned_recursive_aggregate_results_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_spawned_recursive_aggregate_results.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_recursive_aggregate_params_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_recursive_aggregate_params.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_spawned_recursive_aggregate_params_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_spawned_recursive_aggregate_params.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_zero_sized_aggregate_params_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_zero_sized_aggregate_params.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_spawned_zero_sized_aggregate_params_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_spawned_zero_sized_aggregate_params.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_projected_task_handle_awaits_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_projected_task_handle_awaits.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_projected_task_handle_spawns_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_projected_task_handle_spawns.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_projected_task_handle_reinit_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_projected_task_handle_reinit.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_projected_task_handle_conditional_reinit_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_projected_task_handle_conditional_reinit.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_zero_sized_nested_task_handle_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_zero_sized_nested_task_handle.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_zero_sized_struct_task_handle_payload_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_zero_sized_struct_task_handle_payload.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_zero_sized_projected_task_handle_awaits_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_zero_sized_projected_task_handle_awaits.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_zero_sized_projected_task_handle_spawns_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_zero_sized_projected_task_handle_spawns.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_zero_sized_projected_task_handle_reinit_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_zero_sized_projected_task_handle_reinit.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_zero_sized_projected_task_handle_conditional_reinit_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_zero_sized_projected_task_handle_conditional_reinit.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_branch_spawned_reinit_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_branch_spawned_reinit.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_zero_sized_branch_spawned_reinit_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_zero_sized_branch_spawned_reinit.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_zero_sized_reverse_branch_spawned_reinit_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_zero_sized_reverse_branch_spawned_reinit.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_conditional_async_call_spawns_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_conditional_async_call_spawns.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_zero_sized_conditional_async_call_spawns_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_zero_sized_conditional_async_call_spawns.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_conditional_helper_task_handle_spawns_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_conditional_helper_task_handle_spawns.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
        PassCase {
            name: "async_program_main_zero_sized_conditional_helper_task_handle_spawns_exe",
            source_relative: "fixtures/codegen/pass/async_program_main_zero_sized_conditional_helper_task_handle_spawns.ql",
            emit: "exe",
            expected_relative: "tests/codegen/pass/minimal_build.exe.txt",
            mock_compiler: true,
            mock_archiver: false,
            archiver_style: None,
            header_surface: None,
            expected_header_relative: None,
        },
    ];
    let fail_cases = vec![
        FailCase {
            name: "unsupported_capturing_closure_build",
            source_relative: "tests/codegen/fail/unsupported_capturing_closure_build.ql",
            emit: "llvm-ir",
            expected_stderr_relative: "tests/codegen/fail/unsupported_capturing_closure_build.stderr",
            extra_args: &[],
        },
        FailCase {
            name: "unsupported_extern_rust_abi_build",
            source_relative: "tests/codegen/fail/unsupported_extern_rust_abi_build.ql",
            emit: "llvm-ir",
            expected_stderr_relative: "tests/codegen/fail/unsupported_extern_rust_abi_build.stderr",
            extra_args: &[],
        },
        FailCase {
            name: "unsupported_extern_rust_abi_definition_build",
            source_relative: "tests/codegen/fail/unsupported_extern_rust_abi_definition_build.ql",
            emit: "llvm-ir",
            expected_stderr_relative: "tests/codegen/fail/unsupported_extern_rust_abi_definition_build.stderr",
            extra_args: &[],
        },
        FailCase {
            name: "unsupported_empty_array_without_expected_build",
            source_relative: "tests/codegen/fail/unsupported_empty_array_without_expected_build.ql",
            emit: "llvm-ir",
            expected_stderr_relative: "tests/codegen/fail/unsupported_empty_array_without_expected_build.stderr",
            extra_args: &[],
        },
        FailCase {
            name: "unsupported_cleanup_capturing_closure_value_build",
            source_relative: "tests/codegen/fail/unsupported_cleanup_capturing_closure_value_build.ql",
            emit: "llvm-ir",
            expected_stderr_relative: "tests/codegen/fail/unsupported_cleanup_capturing_closure_value_build.stderr",
            extra_args: &[],
        },
        FailCase {
            name: "unsupported_for_build",
            source_relative: "tests/codegen/fail/unsupported_for_build.ql",
            emit: "llvm-ir",
            expected_stderr_relative: "tests/codegen/fail/unsupported_for_build.stderr",
            extra_args: &[],
        },
        FailCase {
            name: "unsupported_cleanup_for_build",
            source_relative: "tests/codegen/fail/unsupported_cleanup_for_build.ql",
            emit: "llvm-ir",
            expected_stderr_relative: "tests/codegen/fail/unsupported_cleanup_for_build.stderr",
            extra_args: &[],
        },
        FailCase {
            name: "unsupported_async_generic_main_build",
            source_relative: "tests/codegen/fail/unsupported_async_generic_main_build.ql",
            emit: "llvm-ir",
            expected_stderr_relative: "tests/codegen/fail/unsupported_async_generic_main_build.stderr",
            extra_args: &[],
        },
        FailCase {
            name: "unsupported_deferred_multi_segment_type_build",
            source_relative: "tests/codegen/fail/unsupported_deferred_multi_segment_type_build.ql",
            emit: "dylib",
            expected_stderr_relative: "tests/codegen/fail/unsupported_deferred_multi_segment_type_build.stderr",
            extra_args: &[],
        },
        FailCase {
            name: "dylib_requires_export_build",
            source_relative: "tests/codegen/fail/dylib_requires_export_build.ql",
            emit: "dylib",
            expected_stderr_relative: "tests/codegen/fail/dylib_requires_export_build.stderr",
            extra_args: &[],
        },
        FailCase {
            name: "executable_header_build",
            source_relative: "fixtures/codegen/pass/minimal_build.ql",
            emit: "exe",
            expected_stderr_relative: "tests/codegen/fail/executable_header_build.stderr",
            extra_args: &["--header"],
        },
    ];
    let mut failures = Vec::new();

    for case in pass_cases {
        if let Err(message) = run_pass_case(&workspace_root, &case) {
            failures.push(message);
        }
    }

    for case in fail_cases {
        if let Err(message) = run_fail_case(&workspace_root, &case) {
            failures.push(message);
        }
    }

    assert!(
        failures.is_empty(),
        "codegen snapshot regressions:\n\n{}",
        failures.join("\n\n")
    );
}
